---
title: "Methylation analysis based on signal detection"
subtitle: <h1>Optimal cutpoint estimation with [Methyl-IT](https://github.com/genomaths/MethylIT). 
           A guide for users</h>
author: |
 | Robersy Sanchez
 | rus547@psu.edu
 | Mackenzie's lab
 
 | Department of Biology and Plant Science. 
 | Pennsylvania State University, University Park, PA 16802
 | Maintainer: Robersy Sanchez
date: "05 April 2019"
fontsize: 11pt
fontfamily: "serif"
bibliography: bibliography.bib
output:
  rmarkdown::html_document: 
    toc: true
    toc_depth: 3
    toc_float: 
      collapsed: false
      smooth_scroll: true
    number_sections: true
    highlight: tango
    theme: united
    geometry: margin=1in
    keep_md: yes
  
abstract: |
  The discrimination of the methylation signal from the stochastic methylation
  background resultant from the standard (non-stressful) biological processes is
  a critical step for the genome-wide methylation analysis. Such a
  discrimination requires for the knowledge of the probability distribution of
  the information divergence of methylation levels and a proper evaluation of
  the classification performance of differentially methylated positions (DMPs)
  into two classes: DMPs from control and DMPs from treatment.
  
---

<style type="text/css">

body{ /* Normal  */
      font-size: 18px;
      font-family: "Times New Roman", Times, serif;
      text-align: justify
  }
td {  /* Table  */
  font-size: 8px;
}

h1.title {
  font-size: 38px;
  font-family: "Times New Roman", Times, serif;
  color: DarkRed;
  .subTitle {
  font-size: 24px;
  font-family: "Times New Roman", Times, serif;
  color: DarkRed;
  }
}

h1 { /* Header 1 */
  font-size: 28px;
  font-family: "Times New Roman", Times, serif;
  color: DarkBlue;
}
h2 { /* Header 2 */
    font-size: 22px;
    color: DarkBlue;
    font-family: "Times New Roman", Times, serif;
}
h3 { /* Header 3 */
   font-size: 18px;
   color: DarkBlue;
   font-family: "Times New Roman", Times, serif;
}
code.r{ /* Code block */
    font-size: 12px;
}
pre { /* Code block - determines code spacing between lines */
    font-size: 14px;
}
</style>


# Background
Normally, there is a spontaneous variability in the control group. This is a
consequence of the random fluctuations, or noise, inherent to the methylation
process. The stochasticity of the the methylation process derives from the
stochasticity inherent to biochemical processes. There are fundamental physical
reasons to acknowledge that biochemical processes are subject to noise and
fluctuations [@Samoilov2006; @Eldar2010]. So, regardless constant environment,
statistically significant methylation changes can be found in control population
with probability greater than zero and proportional to a Boltzmann factor
[@Sanchez2016].

Natural signals and those generated by human technology are not free of noise
and, as mentioned above, the methylation signal is no exception. Only signal
detection based approaches are designed to filter out the signal from the noise,
in natural and in human generated signals.

The need for the application of (what is now known as) signal detection in
cancer research was pointed out by Youden in the midst of the last century
[@Youden1950].
  
Note: This example was made with the MethylIT version at https://github.com/genomaths/MethylIT.  
It must NOT run with the current version available at https://git.psu.edu/genomath/MethylIT
  

# Data generation
For the current example on methylation analysis with Methyl-IT we will use
simulated data. Read-count matrices of methylated and unmethylated cytosine are
generated with MethylIT.utils function *simulateCounts*. A standard analysis of this
dataset is given in the web page: [Methylation analysis with Methyl-IT](https://genomaths.github.io/Methylation_analysis_with_Methyl-IT.html)


```r
library(MethylIT.utils)
library(MethylIT)

bmean <- function(alpha, beta) alpha/(alpha + beta)
alpha.ct <- 0.09
alpha.tt <- 0.2

# The number of cytosine sites to generate
sites = 50000 
# Set a seed for pseudo-random number generation
set.seed(124)
control.nam <- c("C1", "C2", "C3")
treatment.nam <- c("T1", "T2", "T3")

# Reference group 
ref0 = simulateCounts(num.samples = 4, sites = sites, alpha = alpha.ct, beta = 0.5,
                      size = 50, theta = 4.5, sample.ids = c("R1", "R2", "R3"))
# Control group
ctrl = simulateCounts(num.samples = 3, sites = sites, alpha = alpha.ct, beta = 0.5,
                      size = 50, theta = 4.5, sample.ids = control.nam)
# Treatment group
treat = simulateCounts(num.samples = 3, sites = sites, alpha = alpha.tt, beta = 0.5,
                       size = 50, theta = 4.5, sample.ids = treatment.nam)

# Reference sample
ref = poolFromGRlist(ref0, stat = "mean", num.cores = 4L, verbose = FALSE)

# Methylation level divergences
DIVs <- estimateDivergence(ref = ref, indiv = c(ctrl, treat), Bayesian = TRUE, 
                           num.cores = 6L, percentile = 1, verbose = FALSE)
divs = DIVs[order(names(DIVs))]

# To remove hd == 0 to estimate. The methylation signal only is given for  
divs = lapply(divs, function(div) div[ abs(div$hdiv) > 0 ], keep.attr = TRUE)
names(divs) <- names(DIVs)

# Potential DMPs estimated with Fisher's exact Test (FT)
ft = FisherTest(LR = divs, tv.cut = 0.926, pAdjustMethod = "BH",
                     pvalCutOff = 0.05, num.cores = 4L,
                     verbose = FALSE, saveAll = FALSE) 

ft.tv <- getPotentialDIMP(LR = ft, div.col = 9L, dist.name = "None",
                          tv.cut = 0.926, tv.col = 7, alpha = 0.05)

# Potential DMPs estimated with 2-parameter gamma distribution model
nlms.g2p <- nonlinearFitDist(divs, column = 9L, verbose = FALSE, num.cores = 6L,
                            dist.name = "Gamma2P")
# Potential DMPs from 'Gamma2P' model
DMPs.g2p <- getPotentialDIMP(LR = divs, nlms = nlms.g2p,  div.col = 9L, 
                             tv.cut = 0.926, tv.col = 7, alpha = 0.05, 
                             dist.name = "Gamma2P")
```

# Cutpoint for the spontaneous variability in the control group 
## Simple cutpoint estimation with classification performance evaluation for FT model

The simple cutpoint estimation available in Methyl-IT is based on the aplication 
of Youden index [@Youden1950]. Although cutpoints are estimated for a single variable,
the classification performance can be evaluated for several variables and appliying
different model classifiers 

In the current example, the column carrying *TV* (*div.col* = 7L) will be used
to estimate the cutpoint. The column values will be expressed in terms of
$TV_d=|p_{tt}-p_{ct}|$. A minimun cutpoint value for *TV* derived from the
minimum 95% quantile (*tv.cut* = 0.92) found in the treatment group will be
applied (see [Methylation analysis with
Methyl-IT](https://genomaths.github.io/Methylation_analysis_with_Methyl-IT.html)).

Next, a logistic model classifier will be fitted with the 60% (*prop* = 0.6)
of the raw data (training set) and then the resting 40% of individual samples
will be used to evaluate the model performance. The predictor variable included
in the model are specified with function parameter *column* (for more detail see [*estimateCutPoint*](https://genomaths.github.io/MethylIT_HTML_Manual/estimateCutPoint.html)
or type ?estimateCutPoint in R console).


```r
# Cutpoint estimation for FT approach
cut.ft = estimateCutPoint(LR = ft.tv, simple = TRUE, 
                            column = c(hdiv = TRUE, TV = TRUE, 
                                       wprob = TRUE, pos = TRUE),
                            classifier1 = "logistic", 
                            interaction = "hdiv:wprob",
                            tv.cut = 0.926, 
                            control.names = control.nam,
                            treatment.names = treatment.nam,
                            clas.perf = TRUE, prop = 0.6, div.col = 7L)

cut.ft
```

```
## Cutpoint estimation with 'Youden Index' 
## Simple cutpoint estimation 
## Cutpoint = 0.98477 
## 
## Cytosine sites from treatment have divergence values >= 0.98477 
## 
## The accessible objects in the output list are: 
##                     Length Class           Mode     
## cutpoint             1     -none-          numeric  
## testSetPerformance   6     confusionMatrix list     
## testSetModel.FDR     1     -none-          numeric  
## model               30     LogisticR       list     
## modelConfMatrix      6     confusionMatrix list     
## initModel            1     -none-          character
## postProbCut          1     -none-          logical  
## classifier           1     -none-          character
## statistic            1     -none-          logical  
## optStatVal           1     -none-          logical  
## initModelConfMatrix  6     confusionMatrix list
```

```r
summary(cut.ft$model)
```

```
## 
## Call:
## glm(formula = formula, family = binomial(link = "logit"), data = dt)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -2.9428  -1.1695   0.6941   0.9599   1.2625  
## 
## Coefficients:
##               Estimate Std. Error z value Pr(>|z|)    
## (Intercept) -3.509e+01  9.267e+00  -3.786 0.000153 ***
## hdiv        -1.530e-01  1.024e-02 -14.945  < 2e-16 ***
## TV           3.431e+01  9.235e+00   3.715 0.000203 ***
## logP        -4.420e-01  2.998e-02 -14.745  < 2e-16 ***
## pos          2.360e-02  1.313e-01   0.180 0.857424    
## hdiv:logP   -9.777e-05  2.331e-05  -4.194 2.74e-05 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 4352.7  on 3437  degrees of freedom
## Residual deviance: 4056.8  on 3432  degrees of freedom
## AIC: 4068.8
## 
## Number of Fisher Scoring iterations: 4
```
As suggested in the above output, the classification performance of the logistic model 
on the training set is retrieved with expression:

```r
cut.ft$testSetPerformance
```

```
## Confusion Matrix and Statistics
## 
##           Reference
## Prediction   CT   TT
##         CT  177    9
##         TT  576 1531
##                                           
##                Accuracy : 0.7449          
##                  95% CI : (0.7265, 0.7626)
##     No Information Rate : 0.6716          
##     P-Value [Acc > NIR] : 1.361e-14       
##                                           
##                   Kappa : 0.2838          
##  Mcnemar's Test P-Value : < 2.2e-16       
##                                           
##             Sensitivity : 0.9942          
##             Specificity : 0.2351          
##          Pos Pred Value : 0.7266          
##          Neg Pred Value : 0.9516          
##              Prevalence : 0.6716          
##          Detection Rate : 0.6677          
##    Detection Prevalence : 0.9189          
##       Balanced Accuracy : 0.6146          
##                                           
##        'Positive' Class : TT              
## 
```
Notice that the low accuracy value reported here is mostly originated by
cytosine postitions found in the individual samples from control group that have
been predicted as treatment DMPs by FT test, but they are not from treatment. In
natural experimental samples, these DMPs (576 from the test-set) spontaneously
happend in the control group and they are not induced by the treatament.

In the current case, after the application of logistic model the classfication
performance improves a little bit, but this cannot solve the fundamental issue
derived from the FT classification.

```r
cut.ft$modelConfMatrix
```

```
## Confusion Matrix and Statistics
## 
##           Reference
## Prediction   CT   TT
##         CT  489   28
##         TT 1393 3821
##                                           
##                Accuracy : 0.7521          
##                  95% CI : (0.7407, 0.7632)
##     No Information Rate : 0.6716          
##     P-Value [Acc > NIR] : < 2.2e-16       
##                                           
##                   Kappa : 0.31            
##  Mcnemar's Test P-Value : < 2.2e-16       
##                                           
##             Sensitivity : 0.9927          
##             Specificity : 0.2598          
##          Pos Pred Value : 0.7328          
##          Neg Pred Value : 0.9458          
##              Prevalence : 0.6716          
##          Detection Rate : 0.6667          
##    Detection Prevalence : 0.9098          
##       Balanced Accuracy : 0.6263          
##                                           
##        'Positive' Class : TT              
## 
```
## On Fisher's exact Test (FT) low classification performance
It seems to be that the poor classification performance from Fisher's exact Test (FT)
is due to variable $log_{10}(p.value)$, derived from FT, is not a good predictor.


```r
# Potential DMPs from 'Gamma2P' model
x <- ft
class(x) <- class(divs)
names(x) <- names(divs)

dmp.ft.g2p <- getPotentialDIMP(LR = x, nlms = nlms.g2p,  div.col = 9L,
                             tv.cut = 0.926, tv.col = 7, alpha = 0.5,
                             dist.name = "Gamma2P")

# Cutpoint estimation for FT approach
cutg2p = estimateCutPoint(LR = dmp.ft.g2p, simple = TRUE, 
                            column = c(hdiv = TRUE, TV = TRUE, 
                                       wprob = TRUE, pos = TRUE),
                            classifier1 = "logistic", 
                            interaction = "hdiv:wprob",
                            tv.cut = 0.926, 
                            control.names = control.nam,
                            treatment.names = treatment.nam,
                            clas.perf = TRUE, prop = 0.6, div.col = 9L)
c(cutpoint = cutg2p$cutpoint)
```

```
## cutpoint 
## 50.48789
```

```r
cutg2p$testSetPerformance
```

```
## Confusion Matrix and Statistics
## 
##           Reference
## Prediction   CT   TT
##         CT 1450    0
##         TT    0 2859
##                                      
##                Accuracy : 1          
##                  95% CI : (0.9991, 1)
##     No Information Rate : 0.6635     
##     P-Value [Acc > NIR] : < 2.2e-16  
##                                      
##                   Kappa : 1          
##  Mcnemar's Test P-Value : NA         
##                                      
##             Sensitivity : 1.0000     
##             Specificity : 1.0000     
##          Pos Pred Value : 1.0000     
##          Neg Pred Value : 1.0000     
##              Prevalence : 0.6635     
##          Detection Rate : 0.6635     
##    Detection Prevalence : 0.6635     
##       Balanced Accuracy : 1.0000     
##                                      
##        'Positive' Class : TT         
## 
```

```r
cutg2p$modelConfMatrix
```

```
## Confusion Matrix and Statistics
## 
##           Reference
## Prediction   CT   TT
##         CT 3625    0
##         TT    0 7146
##                                      
##                Accuracy : 1          
##                  95% CI : (0.9997, 1)
##     No Information Rate : 0.6634     
##     P-Value [Acc > NIR] : < 2.2e-16  
##                                      
##                   Kappa : 1          
##  Mcnemar's Test P-Value : NA         
##                                      
##             Sensitivity : 1.0000     
##             Specificity : 1.0000     
##          Pos Pred Value : 1.0000     
##          Neg Pred Value : 1.0000     
##              Prevalence : 0.6634     
##          Detection Rate : 0.6634     
##    Detection Prevalence : 0.6634     
##       Balanced Accuracy : 1.0000     
##                                      
##        'Positive' Class : TT         
## 
```
Now with QDA classifier:

```r
# Potential DMPs from 'Gamma2P' model
x <- ft
class(x) <- class(divs)
names(x) <- names(divs)

dmp.ft.g2p <- getPotentialDIMP(LR = x, nlms = nlms.g2p,  div.col = 9L,
                             tv.cut = 0.926, tv.col = 7, alpha = 0.5,
                             dist.name = "Gamma2P")

# Cutpoint estimation for FT approach
cutg2p = estimateCutPoint(LR = dmp.ft.g2p, simple = TRUE, 
                            column = c(hdiv = TRUE, TV = TRUE, 
                                       wprob = TRUE, pos = TRUE),
                            classifier1 = "qda", tv.cut = 0.926, 
                            control.names = control.nam,
                            treatment.names = treatment.nam,
                            clas.perf = TRUE, prop = 0.6, div.col = 9L)
c(cutpoint = cutg2p$cutpoint)
```

```
## cutpoint 
## 50.48789
```

```r
cutg2p$testSetPerformance
```

```
## Confusion Matrix and Statistics
## 
##           Reference
## Prediction   CT   TT
##         CT 1450    2
##         TT    0 2857
##                                           
##                Accuracy : 0.9995          
##                  95% CI : (0.9983, 0.9999)
##     No Information Rate : 0.6635          
##     P-Value [Acc > NIR] : <2e-16          
##                                           
##                   Kappa : 0.999           
##  Mcnemar's Test P-Value : 0.4795          
##                                           
##             Sensitivity : 0.9993          
##             Specificity : 1.0000          
##          Pos Pred Value : 1.0000          
##          Neg Pred Value : 0.9986          
##              Prevalence : 0.6635          
##          Detection Rate : 0.6630          
##    Detection Prevalence : 0.6630          
##       Balanced Accuracy : 0.9997          
##                                           
##        'Positive' Class : TT              
## 
```

```r
cutg2p$modelConfMatrix
```

```
## Confusion Matrix and Statistics
## 
##           Reference
## Prediction   CT   TT
##         CT 3625    5
##         TT    0 7141
##                                           
##                Accuracy : 0.9995          
##                  95% CI : (0.9989, 0.9998)
##     No Information Rate : 0.6634          
##     P-Value [Acc > NIR] : < 2e-16         
##                                           
##                   Kappa : 0.999           
##  Mcnemar's Test P-Value : 0.07364         
##                                           
##             Sensitivity : 0.9993          
##             Specificity : 1.0000          
##          Pos Pred Value : 1.0000          
##          Neg Pred Value : 0.9986          
##              Prevalence : 0.6634          
##          Detection Rate : 0.6630          
##    Detection Prevalence : 0.6630          
##       Balanced Accuracy : 0.9997          
##                                           
##        'Positive' Class : TT              
## 
```

After filtering the FT results with 2P gamma distribution

```r
rbind(ft = unlist(lapply(ft, function(x) length(x))),
  dmp.ft.g2p = unlist(lapply(dmp.ft.g2p, function(x) length(x))))
```

```
##              C1   C2   C3   T1   T2   T3
## ft         1253 1221 1280 2504 2464 2408
## dmp.ft.g2p 1253 1221 1280 2504 2464 2408
```


After the cutpoint application to select DMPs, a Monte Carlo (boostrap) analysis
reporting several classifier performance indicators can be accomplished by
using function
[*evaluateDIMPclass*](https://genomaths.github.io/MethylIT_HTML_Manual/evaluateDIMPclass.html)
and its settings *output = "mc.val"* and *num.boot*.

```r
ft.DMPs <- selectDIMP(dmp.ft.g2p, div.col = 7L, cutpoint = 0.98477, absolute = TRUE)
ft.class = evaluateDIMPclass(LR = ft.DMPs, 
                            column = c(hdiv = TRUE, TV = TRUE, 
                                       wprob = TRUE, pos = TRUE),
                            classifier = "logistic", 
                            interaction = "hdiv:wprob", 
                            control.names = control.nam,
                            treatment.names = treatment.nam, 
                            output = "mc.val", num.boot = 300, 
                            prop = 0.6)

ft.class
```

```
##     Accuracy          Kappa        AccuracyLower    AccuracyUpper   
##  Min.   :0.9991   Min.   :0.9980   Min.   :0.9969   Min.   :0.9999  
##  1st Qu.:1.0000   1st Qu.:1.0000   1st Qu.:0.9984   1st Qu.:1.0000  
##  Median :1.0000   Median :1.0000   Median :0.9984   Median :1.0000  
##  Mean   :0.9999   Mean   :0.9997   Mean   :0.9981   Mean   :1.0000  
##  3rd Qu.:1.0000   3rd Qu.:1.0000   3rd Qu.:0.9984   3rd Qu.:1.0000  
##  Max.   :1.0000   Max.   :1.0000   Max.   :0.9984   Max.   :1.0000  
##                                                                     
##   AccuracyNull    AccuracyPValue McnemarPValue     Sensitivity    
##  Min.   :0.6713   Min.   :0      Min.   :0.4795   Min.   :0.9987  
##  1st Qu.:0.6713   1st Qu.:0      1st Qu.:0.4795   1st Qu.:1.0000  
##  Median :0.6713   Median :0      Median :0.4795   Median :1.0000  
##  Mean   :0.6713   Mean   :0      Mean   :0.4901   Mean   :0.9998  
##  3rd Qu.:0.6713   3rd Qu.:0      3rd Qu.:0.4795   3rd Qu.:1.0000  
##  Max.   :0.6713   Max.   :0      Max.   :1.0000   Max.   :1.0000  
##                                  NA's   :251                      
##   Specificity Pos Pred Value Neg Pred Value     Precision     Recall      
##  Min.   :1    Min.   :1      Min.   :0.9974   Min.   :1   Min.   :0.9987  
##  1st Qu.:1    1st Qu.:1      1st Qu.:1.0000   1st Qu.:1   1st Qu.:1.0000  
##  Median :1    Median :1      Median :1.0000   Median :1   Median :1.0000  
##  Mean   :1    Mean   :1      Mean   :0.9996   Mean   :1   Mean   :0.9998  
##  3rd Qu.:1    3rd Qu.:1      3rd Qu.:1.0000   3rd Qu.:1   3rd Qu.:1.0000  
##  Max.   :1    Max.   :1      Max.   :1.0000   Max.   :1   Max.   :1.0000  
##                                                                           
##        F1           Prevalence     Detection Rate   Detection Prevalence
##  Min.   :0.9994   Min.   :0.6713   Min.   :0.6704   Min.   :0.6704      
##  1st Qu.:1.0000   1st Qu.:0.6713   1st Qu.:0.6713   1st Qu.:0.6713      
##  Median :1.0000   Median :0.6713   Median :0.6713   Median :0.6713      
##  Mean   :0.9999   Mean   :0.6713   Mean   :0.6712   Mean   :0.6712      
##  3rd Qu.:1.0000   3rd Qu.:0.6713   3rd Qu.:0.6713   3rd Qu.:0.6713      
##  Max.   :1.0000   Max.   :0.6713   Max.   :0.6713   Max.   :0.6713      
##                                                                         
##  Balanced Accuracy
##  Min.   :0.9994   
##  1st Qu.:1.0000   
##  Median :1.0000   
##  Mean   :0.9999   
##  3rd Qu.:1.0000   
##  Max.   :1.0000   
## 
```
Notice that function *evaluateDIMPclass* uses function *estimateCutPoint* to estimate the cutpoint.
So, all the classification performance evaluation made by calling function *estimateCutPoint*
can be redone with function *evaluateDIMPclass*, and even to use different classifiers.

## Simple cutpoint estimation with classification performance evaluation for 2P gamma model
Here, we use the results of modeling the distribution of the Hellinger divergence (*HD*) of methylation levels 
through a 2-parameter gamma probability distribution model. The critical values for $HD_{\alpha = 0.05}^{CT_{G2P}}$ used to get potential DMPs were:


```r
nams <- names(nlms.g2p)
crit <- unlist(lapply(nlms.g2p, function(x) qgamma(0.95, shape = x$Estimate[1],
                                                   scale = x$Estimate[2])))
names(crit) <- nams
crit
```

```
##        C1        C2        C3        T1        T2        T3 
##  97.40329  97.19037  96.98129 123.78138 123.55315 120.30413
```

As before the cutpoint is estimated based on 'Youden Index' [@Youden1950]. A
PCA+LDA model classifier (*classifier* = "pca.lda") is applied. That is, a
principal component analyis (PCA) is applied on the original raw matrix of data
and the four possible component (*n.pc* = 4) derived from the analysis are used
in a further linear discriminant analysis (LDA). A scaling step is applied to
the raw matrix of data before the application of the mentioned procedure
(*center* = TRUE, *scale* = TRUE). Here, PCA will yield new orthogonal
(non-correlated) variables, the principal components, which prevent any
potential bias effect originated by any correlation or association of the
original variables.

We can estimate the cutpoint, based on *HD* (*div.col* = 9L) or on 
$TV_d$ (*div.col* = 7L): 

```r
# Cutpoint estimation for the FT approach using the ECDF critical value
cut.g2p = estimateCutPoint(LR = DMPs.g2p, simple = TRUE,
                            column = c(hdiv = TRUE, TV = TRUE, 
                                       wprob = TRUE, pos = TRUE),
                            classifier1 = "pca.lda", n.pc = 4, 
                            tv.cut = 0.926, control.names = control.nam,
                            treatment.names = treatment.nam,
                            center = TRUE, scale = TRUE,
                            clas.perf = TRUE, prop = 0.6, div.col = 7L)
cut.g2p
```

```
## Cutpoint estimation with 'Youden Index' 
## Simple cutpoint estimation 
## Cutpoint = 0.98477 
## 
## Cytosine sites from treatment have divergence values >= 0.98477 
## 
## The accessible objects in the output list are: 
##                     Length Class           Mode     
## cutpoint            1      -none-          numeric  
## testSetPerformance  6      confusionMatrix list     
## testSetModel.FDR    1      -none-          numeric  
## model               2      pcaLDA          list     
## modelConfMatrix     6      confusionMatrix list     
## initModel           1      -none-          character
## postProbCut         1      -none-          logical  
## classifier          1      -none-          character
## statistic           1      -none-          logical  
## optStatVal          1      -none-          logical  
## initModelConfMatrix 6      confusionMatrix list
```

As indicated above, the model classifier perfromance and its corresponding false
discovery rate can be retrieved as:

```r
cut.g2p$testSetPerformance
```

```
## Confusion Matrix and Statistics
## 
##           Reference
## Prediction  CT  TT
##         CT 597   0
##         TT   0 970
##                                      
##                Accuracy : 1          
##                  95% CI : (0.9976, 1)
##     No Information Rate : 0.619      
##     P-Value [Acc > NIR] : < 2.2e-16  
##                                      
##                   Kappa : 1          
##  Mcnemar's Test P-Value : NA         
##                                      
##             Sensitivity : 1.000      
##             Specificity : 1.000      
##          Pos Pred Value : 1.000      
##          Neg Pred Value : 1.000      
##              Prevalence : 0.619      
##          Detection Rate : 0.619      
##    Detection Prevalence : 0.619      
##       Balanced Accuracy : 1.000      
##                                      
##        'Positive' Class : TT         
## 
```

```r
cut.g2p$testSetModel.FDR
```

```
## [1] 0
```

Next, a different model classifier can be applied to model the classification derived
from the previous cutpoint estimation and the evaluation of its performance can
be done (altoguether) with function
[evaluateDIMPclass](https://genomaths.github.io/MethylIT_HTML_Manual/evaluateDIMPclass.html)
Herein, the DMP classifiction is modelled with PCA+QDA classifier (*classifier* =
"pca.qda"). That is, principal component analyis (PCA) is applied on
the original raw matrix of data and the four possible component (*n.pc* = 4) are
used in a further quadratic discriminant analysis (QDA). A scaling step is
applied to the raw matrix of data before the application of the mentioned
procedure (*center* = TRUE, "scale" = TRUE).


```r
g2p.DMPs <- selectDIMP(DMPs.g2p, div.col = 7L, cutpoint = 0.98477, absolute = TRUE)
g2p.class = evaluateDIMPclass(LR = g2p.DMPs, control.names = control.nam,
                           treatment.names = treatment.nam,
                           column = c(hdiv = TRUE, TV = TRUE, 
                                      wprob = TRUE, pos = TRUE),
                           classifier = "pca.qda", n.pc = 4, pval.col = 10L, 
                           center = TRUE, scale = TRUE,
                           output = "conf.mat", prop = 0.6
)
g2p.class
```

```
## $Performance
## Confusion Matrix and Statistics
## 
##           Reference
## Prediction  CT  TT
##         CT 598   0
##         TT   0 970
##                                      
##                Accuracy : 1          
##                  95% CI : (0.9977, 1)
##     No Information Rate : 0.6186     
##     P-Value [Acc > NIR] : < 2.2e-16  
##                                      
##                   Kappa : 1          
##  Mcnemar's Test P-Value : NA         
##                                      
##             Sensitivity : 1.0000     
##             Specificity : 1.0000     
##          Pos Pred Value : 1.0000     
##          Neg Pred Value : 1.0000     
##              Prevalence : 0.6186     
##          Detection Rate : 0.6186     
##    Detection Prevalence : 0.6186     
##       Balanced Accuracy : 1.0000     
##                                      
##        'Positive' Class : TT         
##                                      
## 
## $FDR
## [1] 0
## 
## $model
## $qda
## Call:
## qda(ind.coord, grouping = data[resp][, 1], tol = tol, method = method)
## 
## Prior probabilities of groups:
##        CT        TT 
## 0.3810132 0.6189868 
## 
## Group means:
##            PC1         PC2           PC3        PC4
## CT -0.11455996  0.03207960 -0.0012963203 -0.3369857
## TT  0.07051662 -0.01974638  0.0007979413  0.2074293
## 
## $pca
## Standard deviations (1, .., p=4):
## [1] 1.3930696 1.0001401 0.9920407 0.2737373
## 
## Rotation (n x k) = (4 x 4):
##               PC1           PC2         PC3           PC4
## hdiv -0.701359198 -1.127938e-02 -0.08897711  0.7071429315
## TV   -0.127479041  1.390019e-01  0.98205252 -0.0006512804
## logP  0.701246018 -1.914564e-05  0.09149949  0.7070232427
## pos  -0.009919288 -9.902279e-01  0.13886599 -0.0081599359
## 
## attr(,"class")
## [1] "pcaQDA"
```
The model obtained can be used for futher prediction. For example, we would take a
random sample and run:

```r
set.seed(1)
randsampl <- unlist(DMPs.g2p)
randsampl <- randsampl[sample.int(length(randsampl), 10)]

pred <- predict(g2p.class$model, newdata = randsampl)
pred
```

```
## $class
##  [1] CT TT TT TT CT TT TT TT TT CT
## Levels: CT TT
## 
## $posterior
##                  CT           TT
##  [1,]  1.000000e+00 1.283002e-30
##  [2,]  0.000000e+00 1.000000e+00
##  [3,] 7.732669e-115 1.000000e+00
##  [4,]  1.103598e-95 1.000000e+00
##  [5,]  1.000000e+00 2.642030e-52
##  [6,] 3.098610e-151 1.000000e+00
##  [7,]  6.097946e-96 1.000000e+00
##  [8,] 1.333577e-100 1.000000e+00
##  [9,] 3.874624e-113 1.000000e+00
## [10,]  1.000000e+00 2.207002e-23
```
The variable *pred$posterior* provides the posterior classification probabilities that
a DMP could belong to control (*CT*) or to treatment (*TT*) group. Notice that,
for each row, the sum of posterior probabilities is equal 1. By default, individuals with *TT*
posterior probabilities greater than 0.5 are predicted to belong to the treatment class. 
For example:

```r
classfiction = rep("CT", 10)
classfiction[pred$posterior[, 2] > 0.5] <- "TT"
classfiction
```

```
##  [1] "CT" "TT" "TT" "TT" "CT" "TT" "TT" "TT" "TT" "CT"
```
We can be more strict increasing the posterior classification probability cutoff

```r
classfiction = rep("CT", 10)
classfiction[pred$posterior[, 2] > 0.7] <- "TT"
classfiction
```

```
##  [1] "CT" "TT" "TT" "TT" "CT" "TT" "TT" "TT" "TT" "CT"
```
In this case there is not change, but it could.

The model classifier can be evaluated on the whole dataset as well, before 
take potential DMPs.

```r
g2p.class = evaluateDIMPclass(LR = DMPs.g2p, control.names = control.nam,
                           treatment.names = treatment.nam,
                           column = c(hdiv = TRUE, TV = TRUE, 
                                      wprob = TRUE, pos = TRUE),
                           classifier = "pca.qda", n.pc = 4, pval.col = 10L, 
                           center = TRUE, scale = TRUE,
                           output = "conf.mat", prop = 0.6
)
g2p.class
```

```
## $Performance
## Confusion Matrix and Statistics
## 
##           Reference
## Prediction   CT   TT
##         CT 1123    1
##         TT    0 1631
##                                     
##                Accuracy : 0.9996    
##                  95% CI : (0.998, 1)
##     No Information Rate : 0.5924    
##     P-Value [Acc > NIR] : <2e-16    
##                                     
##                   Kappa : 0.9992    
##  Mcnemar's Test P-Value : 1         
##                                     
##             Sensitivity : 0.9994    
##             Specificity : 1.0000    
##          Pos Pred Value : 1.0000    
##          Neg Pred Value : 0.9991    
##              Prevalence : 0.5924    
##          Detection Rate : 0.5920    
##    Detection Prevalence : 0.5920    
##       Balanced Accuracy : 0.9997    
##                                     
##        'Positive' Class : TT        
##                                     
## 
## $FDR
## [1] 0
## 
## $model
## $qda
## Call:
## qda(ind.coord, grouping = data[resp][, 1], tol = tol, method = method)
## 
## Prior probabilities of groups:
##        CT        TT 
## 0.4076495 0.5923505 
## 
## Group means:
##            PC1          PC2         PC3        PC4
## CT  0.04944467  0.003189233 -0.07416336 -0.3238868
## TT -0.03402731 -0.002194797  0.05103845  0.2228955
## 
## $pca
## Standard deviations (1, .., p=4):
## [1] 1.3905556 1.0000085 0.9944165 0.2783412
## 
## Rotation (n x k) = (4 x 4):
##               PC1          PC2         PC3           PC4
## hdiv  0.703462106 -0.003673427 -0.06600687  0.7076515133
## TV    0.109632991  0.039907915  0.99303934 -0.0161500955
## logP -0.702225282  0.004189085  0.08884637  0.7063769736
## pos   0.001151509  0.999187828 -0.04027750  0.0002851813
## 
## attr(,"class")
## [1] "pcaQDA"
```

Classification performance results obtained with Monte Carlos sampling for the 
2P gamma model are quite different from those obtained with FT: 

```r
g2p.class = evaluateDIMPclass(LR = DMPs.g2p, control.names = control.nam,
                           treatment.names = treatment.nam, 
                           column = c(hdiv = TRUE, TV = TRUE, 
                                      wprob = TRUE, pos = TRUE),
                           classifier = "pca.qda", n.pc = 4, pval.col = 10L, 
                           center = TRUE, scale = TRUE, num.boot = 300,
                           output = "mc.val", prop = 0.6
)
g2p.class
```

```
##     Accuracy          Kappa        AccuracyLower    AccuracyUpper   
##  Min.   :0.9978   Min.   :0.9955   Min.   :0.9953   Min.   :0.9992  
##  1st Qu.:0.9996   1st Qu.:0.9992   1st Qu.:0.9980   1st Qu.:1.0000  
##  Median :1.0000   Median :1.0000   Median :0.9987   Median :1.0000  
##  Mean   :0.9998   Mean   :0.9997   Mean   :0.9984   Mean   :1.0000  
##  3rd Qu.:1.0000   3rd Qu.:1.0000   3rd Qu.:0.9987   3rd Qu.:1.0000  
##  Max.   :1.0000   Max.   :1.0000   Max.   :0.9987   Max.   :1.0000  
##                                                                     
##   AccuracyNull    AccuracyPValue McnemarPValue      Sensitivity    
##  Min.   :0.5924   Min.   :0      Min.   :0.04123   Min.   :0.9994  
##  1st Qu.:0.5924   1st Qu.:0      1st Qu.:1.00000   1st Qu.:0.9994  
##  Median :0.5924   Median :0      Median :1.00000   Median :1.0000  
##  Mean   :0.5924   Mean   :0      Mean   :0.98389   Mean   :0.9998  
##  3rd Qu.:0.5924   3rd Qu.:0      3rd Qu.:1.00000   3rd Qu.:1.0000  
##  Max.   :0.5924   Max.   :0      Max.   :1.00000   Max.   :1.0000  
##                                  NA's   :181                       
##   Specificity     Pos Pred Value   Neg Pred Value     Precision     
##  Min.   :0.9947   Min.   :0.9963   Min.   :0.9991   Min.   :0.9963  
##  1st Qu.:1.0000   1st Qu.:1.0000   1st Qu.:0.9991   1st Qu.:1.0000  
##  Median :1.0000   Median :1.0000   Median :1.0000   Median :1.0000  
##  Mean   :1.0000   Mean   :1.0000   Mean   :0.9997   Mean   :1.0000  
##  3rd Qu.:1.0000   3rd Qu.:1.0000   3rd Qu.:1.0000   3rd Qu.:1.0000  
##  Max.   :1.0000   Max.   :1.0000   Max.   :1.0000   Max.   :1.0000  
##                                                                     
##      Recall             F1           Prevalence     Detection Rate  
##  Min.   :0.9994   Min.   :0.9982   Min.   :0.5924   Min.   :0.5920  
##  1st Qu.:0.9994   1st Qu.:0.9997   1st Qu.:0.5924   1st Qu.:0.5920  
##  Median :1.0000   Median :1.0000   Median :0.5924   Median :0.5924  
##  Mean   :0.9998   Mean   :0.9999   Mean   :0.5924   Mean   :0.5922  
##  3rd Qu.:1.0000   3rd Qu.:1.0000   3rd Qu.:0.5924   3rd Qu.:0.5924  
##  Max.   :1.0000   Max.   :1.0000   Max.   :0.5924   Max.   :0.5924  
##                                                                     
##  Detection Prevalence Balanced Accuracy
##  Min.   :0.5920       Min.   :0.9973   
##  1st Qu.:0.5920       1st Qu.:0.9997   
##  Median :0.5924       Median :1.0000   
##  Mean   :0.5923       Mean   :0.9999   
##  3rd Qu.:0.5924       3rd Qu.:1.0000   
##  Max.   :0.5946       Max.   :1.0000   
## 
```

# To search for the best cutpoint
In the next example the cutpoint estimation for the Hellinger divergence of
methylation levels (*div.col* = 9L) is accomplished. Function *estimateCutPoint*
can be used to search for a cutpoint as well. Two model classifiers can be used.
*classifiers1* will be used to estimate the posterior classification
probabilities of DMP into those from control and those from treatment. These
probabilities are then used to estimate the cutpoint in the range of values
from, say, 0.5 to 0.8. Next, a *classifier2* will be used to evaluate the
classification performance. In this case, the search for an optimal cutpoin is
accomplished maximinzing the accuracy (*stat* = 0) of *classifier2*.

Below potential DMPs will be selected with probability alpha = 0.5 and then check whether 
the combination of model classifiers PCA+QDA and PCA+LDA is able to distinguish 
control DMPs from treataments:

```r
dmp.g2p <- getPotentialDIMP(LR = divs, nlms = nlms.g2p,  div.col = 9L, 
                             tv.cut = 0.926, tv.col = 7, alpha = 0.5, 
                             dist.name = "Gamma2P")

cut.g2p = estimateCutPoint(LR = dmp.g2p, simple = FALSE,
                            column = c(hdiv = TRUE, TV = TRUE, 
                                       wprob = TRUE, pos = TRUE),
                            classifier1 = "pca.lda", tv.cut = 0.92,
                            classifier2 = "pca.qda", stat = 0,
                            control.names = control.nam, 
                            treatment.names = treatment.nam, find.cut = TRUE,
                            cut.interval = c(0.5, 0.8), post.cut = 0.5,
                            clas.perf = TRUE, prop = 0.6,
                            center = TRUE, scale = TRUE,
                            n.pc = 4, div.col = 9L)
cut.g2p
```

```
## Cutpoint estimation with 'pca.lda' classifier 
## Cutpoint search performed using model posterior probabilities 
## 
## Posterior probability used to get the cutpoint = 0.5 
## Optimized statistic: Accuracy = 0.99281 
## Cutpoint = 17.739 
## 
## Cytosine sites with treatment PostProbCut >= 0.5 have a 
## divergence value >= 17.739 
## 
## Model classifier 'pca.qda' 
## 
## The accessible objects in the output list are: 
##                    Length Class           Mode     
## cutpoint           1      -none-          numeric  
## testSetPerformance 6      confusionMatrix list     
## testSetModel.FDR   1      -none-          numeric  
## model              2      pcaQDA          list     
## modelConfMatrix    6      confusionMatrix list     
## initModel          1      -none-          character
## postProbCut        1      -none-          numeric  
## classifier         1      -none-          character
## statistic          1      -none-          character
## optStatVal         1      -none-          numeric
```


```r
cut.g2p$testSetPerformance
```

```
## Confusion Matrix and Statistics
## 
##           Reference
## Prediction   CT   TT
##         CT 1470    0
##         TT   32 2950
##                                           
##                Accuracy : 0.9928          
##                  95% CI : (0.9899, 0.9951)
##     No Information Rate : 0.6626          
##     P-Value [Acc > NIR] : < 2.2e-16       
##                                           
##                   Kappa : 0.9838          
##  Mcnemar's Test P-Value : 4.251e-08       
##                                           
##             Sensitivity : 1.0000          
##             Specificity : 0.9787          
##          Pos Pred Value : 0.9893          
##          Neg Pred Value : 1.0000          
##              Prevalence : 0.6626          
##          Detection Rate : 0.6626          
##    Detection Prevalence : 0.6698          
##       Balanced Accuracy : 0.9893          
##                                           
##        'Positive' Class : TT              
## 
```

```r
cut.g2p$testSetModel.FDR
```

```
## [1] 0.01073105
```

```r
dmp.g2p <- getPotentialDIMP(LR = divs, nlms = nlms.g2p,  div.col = 9L,
                             tv.cut = 0.926, tv.col = 7, alpha = 0.98,
                             dist.name = "Gamma2P")

cut.g2p = estimateCutPoint(LR = dmp.g2p, simple = FALSE,
                            column = c(hdiv = TRUE, TV = TRUE, 
                                       wprob = TRUE, pos = TRUE),
                            classifier1 = "pca.lda", tv.cut = 0.92,
                            classifier2 = "pca.qda", stat = 0,
                            control.names = control.nam, 
                            treatment.names = treatment.nam, find.cut = TRUE,
                            cut.interval = c(0.5, 0.8), post.cut = 0.5,
                            clas.perf = TRUE, prop = 0.6,
                            center = TRUE, scale = TRUE,
                            n.pc = 4, div.col = 9L)
cut.g2p
```

```
## Cutpoint estimation with 'pca.lda' classifier 
## Cutpoint search performed using model posterior probabilities 
## 
## Posterior probability used to get the cutpoint = 0.5 
## Optimized statistic: Accuracy = 0.99281 
## Cutpoint = 17.739 
## 
## Cytosine sites with treatment PostProbCut >= 0.5 have a 
## divergence value >= 17.739 
## 
## Model classifier 'pca.qda' 
## 
## The accessible objects in the output list are: 
##                    Length Class           Mode     
## cutpoint           1      -none-          numeric  
## testSetPerformance 6      confusionMatrix list     
## testSetModel.FDR   1      -none-          numeric  
## model              2      pcaQDA          list     
## modelConfMatrix    6      confusionMatrix list     
## initModel          1      -none-          character
## postProbCut        1      -none-          numeric  
## classifier         1      -none-          character
## statistic          1      -none-          character
## optStatVal         1      -none-          numeric
```

The probabilities $P(HD \le 17.739)$ to observe a cytosine site with $HD \le 17.739$ on each 
individual is:

```r
nams <- names(nlms.g2p)
crit <- unlist(lapply(nlms.g2p, function(x) pgamma(cut.g2p$cutpoint, shape = x$Estimate[1],
                                                   scale = x$Estimate[2])))
names(crit) <- nams
crit
```

```
##        C1        C2        C3        T1        T2        T3 
## 0.6607198 0.6615046 0.6612050 0.6020936 0.6022784 0.6057928
```

That is, the probility to observe a cytosine site with $HD \le 17.739$ is greater in
the control than in the treatmetn group. This basic information is cashed by the
model classifier and quantitatively manifest on its performance:


```r
cut.g2p$testSetPerformance
```

```
## Confusion Matrix and Statistics
## 
##           Reference
## Prediction   CT   TT
##         CT 1470    0
##         TT   32 2950
##                                           
##                Accuracy : 0.9928          
##                  95% CI : (0.9899, 0.9951)
##     No Information Rate : 0.6626          
##     P-Value [Acc > NIR] : < 2.2e-16       
##                                           
##                   Kappa : 0.9838          
##  Mcnemar's Test P-Value : 4.251e-08       
##                                           
##             Sensitivity : 1.0000          
##             Specificity : 0.9787          
##          Pos Pred Value : 0.9893          
##          Neg Pred Value : 1.0000          
##              Prevalence : 0.6626          
##          Detection Rate : 0.6626          
##    Detection Prevalence : 0.6698          
##       Balanced Accuracy : 0.9893          
##                                           
##        'Positive' Class : TT              
## 
```

```r
cut.g2p$testSetModel.FDR
```

```
## [1] 0.01073105
```


For the current dataset, a more conservative and interesting ctupoint can be
scrutinized by setting alpha = 0.1 when in the function *getPotentialDIMP*:

```r
dmp.g2p <- getPotentialDIMP(LR = divs, nlms = nlms.g2p,  div.col = 9L,
                             tv.cut = 0.926, tv.col = 7, alpha = 0.1,
                             dist.name = "Gamma2P")

cut.g2p = estimateCutPoint(LR = dmp.g2p, simple = FALSE,
                            column = c(hdiv = TRUE, TV = TRUE, 
                                       wprob = TRUE, pos = TRUE),
                            classifier1 = "pca.qda", tv.cut = 0.92, 
                            control.names = control.nam, stat = 0,
                            treatment.names = treatment.nam, find.cut = TRUE,
                            cut.interval = c(0.5, 0.8), post.cut = 0.5,
                            clas.perf = TRUE, prop = 0.6,
                            center = TRUE, scale = TRUE,
                            n.pc = 4, div.col = 9L)
cut.g2p
```

```
## Cutpoint estimation with 'pca.qda' classifier 
## Cutpoint search performed using model posterior probabilities 
## 
## Posterior probability used to get the cutpoint = 0.5 
## Optimized statistic: Accuracy = 0.99919 
## Cutpoint = 81.594 
## 
## Cytosine sites with treatment PostProbCut >= 0.5 have a 
## divergence value >= 81.594 
## 
## Model classifier 'pca.qda' 
## 
## The accessible objects in the output list are: 
##                    Length Class           Mode     
## cutpoint           1      -none-          numeric  
## testSetPerformance 6      confusionMatrix list     
## testSetModel.FDR   1      -none-          numeric  
## model              2      pcaQDA          list     
## modelConfMatrix    6      confusionMatrix list     
## initModel          1      -none-          character
## postProbCut        1      -none-          numeric  
## classifier         1      -none-          character
## statistic          1      -none-          character
## optStatVal         1      -none-          numeric
```

The probabilities $P(HD \le 81.6)$ to observe a cytosine site with $HD \le 81.6$ on each 
individual is:

```r
nams <- names(nlms.g2p)
crit <- unlist(lapply(nlms.g2p, function(x) pgamma(cut.g2p$cutpoint, shape = x$Estimate[1],
                                                   scale = x$Estimate[2])))
names(crit) <- nams
crit
```

```
##        C1        C2        C3        T1        T2        T3 
## 0.9302251 0.9305094 0.9307369 0.8961976 0.8964575 0.9002940
```
The cutpoint for *HD* = 81.6 is lower than the critical values $HD_{\alpha = 0.05}^{Emp}=114.5$
estimated based on the empirical cumulative function, as shown in the previous
example: [Methylation analysis with Methyl-IT](https://genomaths.github.io/Methylation_analysis_with_Methyl-IT.html).
That is, in this case, the model classifier *PCA+QDA* has enough discriminatory 
power to discriminate control DMP from those induced by the treament for *HD* values
$HD_{\alpha = 0.05}^{CT_{Emp}}=81.5 < 81.6 \le HD \le HD_{\alpha = 0.05}^{TT_{Emp}}=114.5$.

Notice that although the same *HD* value could be found in the same differentially
methylated cytosine site in control and treatment, if the probabilities
distributions of the information divergences from control and treatment are
diferent, then these DMPs can be distinguished.


```r
cut.g2p$testSetPerformance
```

```
## Confusion Matrix and Statistics
## 
##           Reference
## Prediction   CT   TT
##         CT 1276    3
##         TT    0 2442
##                                           
##                Accuracy : 0.9992          
##                  95% CI : (0.9976, 0.9998)
##     No Information Rate : 0.6571          
##     P-Value [Acc > NIR] : <2e-16          
##                                           
##                   Kappa : 0.9982          
##  Mcnemar's Test P-Value : 0.2482          
##                                           
##             Sensitivity : 0.9988          
##             Specificity : 1.0000          
##          Pos Pred Value : 1.0000          
##          Neg Pred Value : 0.9977          
##              Prevalence : 0.6571          
##          Detection Rate : 0.6563          
##    Detection Prevalence : 0.6563          
##       Balanced Accuracy : 0.9994          
##                                           
##        'Positive' Class : TT              
## 
```

# Conclusions 

1. A proper discrimination of the methylation signal from the stochastic
methylation background requires for the knowledge of probability distributions
of the methylation signal from control and treatment population. Such a
knowledge permits a suitable estimation of the cutoff value to discriminate the
methylation signal induced by the treatment from the stochastic methylation
background detected in the control group.   

2. It does not matter how significant a differentially methylation event for a
given cytosine position would be (after the application of some statistical
test), but on how big the probability to be oberved in the control group is. In
simple words, if for a given DMP the probability of to be oberved in the control
is *big enough*, then such a DMP did not result from a treatment effect.   

3. A suitable evaluation on how much the mentioned probability can be *big
enough* derives by estimating an optimal cutpoint. But a classification into two
groups results from the cutpoint estimation and the problem on the estimation of
such a cutpoint is equivalent to find a discriminatory function (as set by
Fisher, [@Fisher1938; @Green1979]). Cases with function values below some cutoff
are classified in one group, while values above the cutoff are put in the other
group.   

4. MethylIT function
[estimateCutPoint](https://genomaths.github.io/MethylIT_HTML_Manual/estimateCutPoint.html)
permits the estimation and search for an optimal cutpoint by confronting the
problem as in the spirit of the classical signal detection and as a
classification problem. The best model classifier will depend on the dataset
under study.So, uses must check for which is the model classifier with the best
classification performance for his/her dataset.

# References 













