<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Optimal cutpoint for the methylation signal • MethylIT</title>
<!-- favicons --><link rel="icon" type="image/png" sizes="16x16" href="../favicon-16x16.png">
<link rel="icon" type="image/png" sizes="32x32" href="../favicon-32x32.png">
<link rel="apple-touch-icon" type="image/png" sizes="180x180" href="../apple-touch-icon.png">
<link rel="apple-touch-icon" type="image/png" sizes="120x120" href="../apple-touch-icon-120x120.png">
<link rel="apple-touch-icon" type="image/png" sizes="76x76" href="../apple-touch-icon-76x76.png">
<link rel="apple-touch-icon" type="image/png" sizes="60x60" href="../apple-touch-icon-60x60.png">
<!-- jquery --><script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script><!-- Bootstrap --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha256-916EbMg70RQy9LHiGkXzG8hSg9EdNy97GazNG/aiY1w=" crossorigin="anonymous">
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha256-U5ZEeKfGNOja007MMD3YBI0A3OSZOQbeG6z2f2Y0hu8=" crossorigin="anonymous"></script><!-- Font Awesome icons --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.1/css/all.min.css" integrity="sha256-PbSmjxuVAzJ6FPvNYsrXygfGhNJYyZ2GktDbkMBqQZg=" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.1/css/v4-shims.min.css" integrity="sha256-A6jcAdwFD48VMjlI3GDxUd+eCQa7/KWy6G9oe/ovaPA=" crossorigin="anonymous">
<!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.4/clipboard.min.js" integrity="sha256-FiZwavyI2V6+EXO1U+xzLG3IKldpiTFf3153ea9zikQ=" crossorigin="anonymous"></script><!-- headroom.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.9.4/headroom.min.js" integrity="sha256-DJFC1kqIhelURkuza0AvYal5RxMtpzLjFhsnVIeuk+U=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.9.4/jQuery.headroom.min.js" integrity="sha256-ZX/yNShbjqsohH1k95liqY9Gd8uOiE1S4vZc+9KQ1K4=" crossorigin="anonymous"></script><!-- pkgdown --><link href="../pkgdown.css" rel="stylesheet">
<script src="../pkgdown.js"></script><link href="../extra.css" rel="stylesheet">
<meta property="og:title" content="Optimal cutpoint for the methylation signal">
<meta property="og:description" content="">
<meta property="og:image" content="https://genomaths.github.io/methylit/logo.png">
<meta name="twitter:card" content="summary">
<!-- mathjax --><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" integrity="sha256-nvJJv9wWKEm88qvoQl9ekL2J+k/RWIsaSScxxlsrv8k=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/TeX-AMS-MML_HTMLorMML.js" integrity="sha256-84DKXVJXs0/F8OTMzX4UR909+jtl4G7SPypPavF+GfA=" crossorigin="anonymous"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body>
    <div class="container template-article">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">MethylIT</a>
        <span class="version label label-default" data-toggle="tooltip" data-placement="bottom" title="Released version">0.3.2</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../index.html">
    <span class="fas fa fas fa-home fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="../articles/MethylIT.html">Get started</a>
</li>
<li>
  <a href="../reference/index.html">Package functions</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Articles
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li>
      <a href="../articles/MethylIT.html">MethylIT</a>
    </li>
    <li class="divider">
    <li>
      <a href="../articles/Methylation_analysis_with_Methyl-IT.html">Methylation analysis with Methyl-IT</a>
    </li>
    <li class="divider">
    <li>
      <a href="../articles/cancer_example.html">Example of Methylome Analysis with MethylIT using Cancer Datasets</a>
    </li>
    <li class="divider">
    <li>
      <a href="../articles/Cutpoint_estimation_with_Methyl-IT.html">Optimal cutpoint for the methylation signal</a>
    </li>
  </ul>
</li>
<li>
  <a href="../news/index.html">News</a>
</li>
<li>
  <a href="https://github.com/genomaths/MethylIT">
    <span class="fab fa fab fa-github fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="http://twitter.com/robersysr">
    <span class="fab fa fab fa-twitter fa-lg"></span>
     
  </a>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right"></ul>
</div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      

      </header><div class="row">
  <div class="col-md-9 contents">
    <div class="page-header toc-ignore">
      <h1>Optimal cutpoint for the methylation signal</h1>
            <h3 class="subtitle">Detection of the methylation signal with Methyl-IT</h3>
                        <h4 class="author">
<div class="line-block">Robersy Sanchez<br><a href="mailto:rus547@psu.edu" class="email">rus547@psu.edu</a><br>
Mackenzie’s lab</div>
<div class="line-block">Department of Biology and Plant Science.<br>
Pennsylvania State University, University Park, PA 16802<br>
Maintainer: Robersy Sanchez</div>
</h4>
            
            <h4 class="date">23 February 2020</h4>
      
      <small class="dont-index">Source: <a href="https://github.com/genomaths/MethylIT/blob/master/vignettes/Cutpoint_estimation_with_Methyl-IT.Rmd"><code>vignettes/Cutpoint_estimation_with_Methyl-IT.Rmd</code></a></small>
      <div class="hidden name"><code>Cutpoint_estimation_with_Methyl-IT.Rmd</code></div>

    </div>

    
        <div class="abstract">
      <p class="abstract">Abstract</p>
      The discrimination of the methylation signal from the stochastic methylation background resultant from the standard (non-stressful) biological processes is a critical step for the genome-wide methylation analysis. Such a discrimination requires for the knowledge of the probability distribution of the information divergence of methylation levels and a proper evaluation of the classification performance of differentially methylated positions (DMPs) into two classes: DMPs from control and DMPs from treatment.
    </div>
    
<style type="text/css">

.list-group-item.active, .list-group-item.active:focus, 
.list-group-item.active:hover {
    z-index: 2;
    color: #fff;
    background-color: #337ab7;
    border-color: #337ab7;
}

.tocify-subheader .tocify-item {
  font-size: 0.80em;
  padding-left: 25px;
  text-indent: 0;
}

.tocify-header .tocify-item {
  font-size: 0.85em;
  padding-left: 20px;
  text-indent: 0;
}

body{ /* Normal  */
      font-size: 18px;
      font-family: "Times New Roman", Times, serif;
      text-align: justify
  }
td {  /* Table  */
  font-size: 8px;
}

h1.title {
  font-size: 38px;
  font-family: "Times New Roman", Times, serif;
  color: DarkRed;
  .subTitle {
  font-size: 24px;
  font-family: "Times New Roman", Times, serif;
  color: DarkRed;
  }
}

h1 { /* Header 1 */
  font-size: 28px;
  font-family: "Times New Roman", Times, serif;
  color: DarkBlue;
}
h2 { /* Header 2 */
    font-size: 22px;
    color: DarkBlue;
    font-family: "Times New Roman", Times, serif;
}
h3 { /* Header 3 */
   font-size: 18px;
   color: DarkBlue;
   font-family: "Times New Roman", Times, serif;
}
code.r{ /* Code block */
    font-size: 14px;
}
pre { /* Code block - determines code spacing between lines */
    font-size: 14px;
}
</style>
<div id="motivation" class="section level2">
<h2 class="hasAnchor">
<a href="#motivation" class="anchor"></a>Motivation</h2>
<p>The probability of extreme methylation changes occurring spontaneously in a control population by the stochastic fluctuations inherent to biochemical processes and DNA maintenance <span class="citation">(Ngo et al. 2016)</span>, requires the discrimination of this background variation from a biological treatment signal. The stochasticity of the the methylation process derives from the stochasticity inherent to biochemical processes <span class="citation">(Min et al. 2005; Koslover and Spakowitz 2012)</span>. There are fundamental physical reasons to acknowledge that biochemical processes are subject to noise and fluctuations <span class="citation">(Samoilov, Price, and Arkin 2006; Eldar and Elowitz 2010)</span>. So, regardless constant environment, statistically significant methylation changes can be found in control population with probability greater than zero and proportional to a Boltzmann factor <span class="citation">(Sanchez and Mackenzie 2016)</span>.</p>
<p>Natural signals and those generated by human technology are not free of noise and, as mentioned above, the methylation signal is no exception. Only signal detection based approaches are designed to filter out the signal from the noise, in natural and in human generated signals.</p>
<p>The stochasticity of methylation regulatory machinery effects is presumed to reflect system heterogeneity; cells from the same tissue are not necessarily in the same state, and therefore, corresponding cytosine sites differ in their methylation status. Consequently, overall organismal response is conveyed as a statistical outcome that distinguishes the regulatory methylation signal from statistical background “noise”. Estimation of optimal cutoff value for the signal is an additional step to remove any remaining potential methylation background noise with probability <span class="math inline">\(0 ≤ \alpha ≤ 0.05\)</span>. We define as a methylation signal (DMP) each cytosine site with Hellinger Divergence values above the cutpoint (shown <span class="citation">(Sanchez et al. 2019)</span>.</p>
<p>As a result, a differentially methylated position (DMP) as a cytosine position with high probability to be altered in methylation due to a treatment effect, distinct from spontaneous variation detected in the control population.</p>
<p>Note: This example was made with the MethylIT version 0.3.2 available at <a href="https://github.com/genomaths/MethylIT" class="uri">https://github.com/genomaths/MethylIT</a>.</p>
</div>
<div id="data-generation" class="section level2">
<h2 class="hasAnchor">
<a href="#data-generation" class="anchor"></a>Data generation</h2>
<p>For the current example on methylation analysis with Methyl-IT we will use simulated data. Read-count matrices of methylated and unmethylated cytosine are generated with MethylIT.utils function <em>simulateCounts</em>. A standard analysis of this dataset is given in the web page: <a href="https://genomaths.github.io/Methylation_analysis_with_Methyl-IT.html">Methylation analysis with Methyl-IT</a></p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1-1" data-line-number="1"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span>(MethylIT)</a>
<a class="sourceLine" id="cb1-2" data-line-number="2"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span>(MethylIT.utils)</a>
<a class="sourceLine" id="cb1-3" data-line-number="3"></a>
<a class="sourceLine" id="cb1-4" data-line-number="4">bmean &lt;-<span class="st"> </span><span class="cf">function</span>(alpha, beta) alpha<span class="op">/</span>(alpha <span class="op">+</span><span class="st"> </span>beta)</a>
<a class="sourceLine" id="cb1-5" data-line-number="5">alpha.ct &lt;-<span class="st"> </span><span class="fl">0.09</span></a>
<a class="sourceLine" id="cb1-6" data-line-number="6">alpha.tt &lt;-<span class="st"> </span><span class="fl">0.2</span></a>
<a class="sourceLine" id="cb1-7" data-line-number="7"></a>
<a class="sourceLine" id="cb1-8" data-line-number="8"><span class="co"># The number of cytosine sites to generate</span></a>
<a class="sourceLine" id="cb1-9" data-line-number="9">sites =<span class="st"> </span><span class="dv">50000</span> </a>
<a class="sourceLine" id="cb1-10" data-line-number="10"><span class="co"># Set a seed for pseudo-random number generation</span></a>
<a class="sourceLine" id="cb1-11" data-line-number="11"><span class="kw"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span>(<span class="dv">124</span>)</a>
<a class="sourceLine" id="cb1-12" data-line-number="12">control.nam &lt;-<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="st">"C1"</span>, <span class="st">"C2"</span>, <span class="st">"C3"</span>)</a>
<a class="sourceLine" id="cb1-13" data-line-number="13">treatment.nam &lt;-<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="st">"T1"</span>, <span class="st">"T2"</span>, <span class="st">"T3"</span>)</a>
<a class="sourceLine" id="cb1-14" data-line-number="14"></a>
<a class="sourceLine" id="cb1-15" data-line-number="15"><span class="co"># Reference group </span></a>
<a class="sourceLine" id="cb1-16" data-line-number="16">ref0 =<span class="st"> </span><span class="kw"><a href="https://rdrr.io/pkg/MethylIT.utils/man/simulateCounts.html">simulateCounts</a></span>(<span class="dt">num.samples =</span> <span class="dv">4</span>, <span class="dt">sites =</span> sites, <span class="dt">alpha =</span> alpha.ct, <span class="dt">beta =</span> <span class="fl">0.5</span>,</a>
<a class="sourceLine" id="cb1-17" data-line-number="17">                      <span class="dt">size =</span> <span class="dv">50</span>, <span class="dt">theta =</span> <span class="fl">4.5</span>, <span class="dt">sample.ids =</span> <span class="kw"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="st">"R1"</span>, <span class="st">"R2"</span>, <span class="st">"R3"</span>, <span class="st">"R4"</span>))</a>
<a class="sourceLine" id="cb1-18" data-line-number="18"><span class="co"># Control group</span></a>
<a class="sourceLine" id="cb1-19" data-line-number="19">ctrl =<span class="st"> </span><span class="kw"><a href="https://rdrr.io/pkg/MethylIT.utils/man/simulateCounts.html">simulateCounts</a></span>(<span class="dt">num.samples =</span> <span class="dv">3</span>, <span class="dt">sites =</span> sites, <span class="dt">alpha =</span> alpha.ct, <span class="dt">beta =</span> <span class="fl">0.5</span>,</a>
<a class="sourceLine" id="cb1-20" data-line-number="20">                      <span class="dt">size =</span> <span class="dv">50</span>, <span class="dt">theta =</span> <span class="fl">4.5</span>, <span class="dt">sample.ids =</span> control.nam)</a>
<a class="sourceLine" id="cb1-21" data-line-number="21"><span class="co"># Treatment group</span></a>
<a class="sourceLine" id="cb1-22" data-line-number="22">treat =<span class="st"> </span><span class="kw"><a href="https://rdrr.io/pkg/MethylIT.utils/man/simulateCounts.html">simulateCounts</a></span>(<span class="dt">num.samples =</span> <span class="dv">3</span>, <span class="dt">sites =</span> sites, <span class="dt">alpha =</span> alpha.tt, <span class="dt">beta =</span> <span class="fl">0.5</span>,</a>
<a class="sourceLine" id="cb1-23" data-line-number="23">                       <span class="dt">size =</span> <span class="dv">50</span>, <span class="dt">theta =</span> <span class="fl">4.5</span>, <span class="dt">sample.ids =</span> treatment.nam)</a>
<a class="sourceLine" id="cb1-24" data-line-number="24"></a>
<a class="sourceLine" id="cb1-25" data-line-number="25"><span class="co"># Reference sample</span></a>
<a class="sourceLine" id="cb1-26" data-line-number="26">ref =<span class="st"> </span><span class="kw"><a href="../reference/poolFromGRlist.html">poolFromGRlist</a></span>(ref0, <span class="dt">stat =</span> <span class="st">"mean"</span>, <span class="dt">num.cores =</span> 4L, <span class="dt">verbose =</span> <span class="ot">FALSE</span>)</a></code></pre></div>
</div>
<div id="methylation-level-divergences" class="section level2">
<h2 class="hasAnchor">
<a href="#methylation-level-divergences" class="anchor"></a>Methylation level divergences</h2>
<p>Total variation distance and Hellinger divergence are computed with <a href="https://genomaths.github.io/methylit/reference/estimateDivergence.html">estimateDivergence</a> function</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb2-1" data-line-number="1">divs &lt;-<span class="st"> </span><span class="kw"><a href="../reference/estimateDivergence.html">estimateDivergence</a></span>(<span class="dt">ref =</span> ref, <span class="dt">indiv =</span> <span class="kw"><a href="https://rdrr.io/r/base/c.html">c</a></span>(ctrl, treat), <span class="dt">Bayesian =</span> <span class="ot">TRUE</span>, </a>
<a class="sourceLine" id="cb2-2" data-line-number="2">                           <span class="dt">num.cores =</span> 6L, <span class="dt">percentile =</span> <span class="dv">1</span>, <span class="dt">verbose =</span> <span class="ot">FALSE</span>)</a></code></pre></div>
<p>To get some statistical description about the sample is useful. Here, empirical critical values for the probability distribution of <span class="math inline">\(H\)</span> and <span class="math inline">\(TV\)</span> can is obtained using <em>quantile</em> function from the R package <em>stats</em>.</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb3-1" data-line-number="1">critical.val &lt;-<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/do.call.html">do.call</a></span>(rbind, <span class="kw"><a href="../reference/lapply.html">lapply</a></span>(divs, <span class="cf">function</span>(x) {</a>
<a class="sourceLine" id="cb3-2" data-line-number="2">  x &lt;-<span class="st"> </span>x[x<span class="op">$</span>hdiv <span class="op">&gt;</span><span class="st"> </span><span class="dv">0</span>]</a>
<a class="sourceLine" id="cb3-3" data-line-number="3">  hd<span class="fl">.95</span> =<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/stats/quantile.html">quantile</a></span>(x<span class="op">$</span>hdiv, <span class="fl">0.95</span>)</a>
<a class="sourceLine" id="cb3-4" data-line-number="4">  tv<span class="fl">.95</span> =<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/stats/quantile.html">quantile</a></span>(<span class="kw"><a href="https://rdrr.io/r/base/MathFun.html">abs</a></span>(x<span class="op">$</span>TV), <span class="fl">0.95</span>)</a>
<a class="sourceLine" id="cb3-5" data-line-number="5">  <span class="kw"><a href="https://rdrr.io/r/base/function.html">return</a></span>(<span class="kw"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="dt">tv =</span> tv<span class="fl">.95</span>, <span class="dt">hd =</span> hd<span class="fl">.95</span>))</a>
<a class="sourceLine" id="cb3-6" data-line-number="6">}))</a>
<a class="sourceLine" id="cb3-7" data-line-number="7">critical.val</a></code></pre></div>
<pre><code>##       tv.95%    hd.95%
## C1 0.6842105  66.76081
## C2 0.6800000  66.71995
## C3 0.6777456  65.98495
## T1 0.9397681 138.68237
## T2 0.9478351 141.72637
## T3 0.9466565 141.77241</code></pre>
</div>
<div id="estimation-of-potential-dmps-with-methyl-it" class="section level2">
<h2 class="hasAnchor">
<a href="#estimation-of-potential-dmps-with-methyl-it" class="anchor"></a>Estimation of potential DMPs with Methyl-IT</h2>
<p>In Methyl-IT, DMP estimation requires for the knowledge of the probability distribution of the noise (plus signal), which is used as null hypothesis.</p>
<p>The best fitted distribution model can be estimated with function <a href="https://genomaths.github.io/methylit/reference/gofReport.html">gofReport</a>. Here, for illustration purposes, we will use specific estimations based on 2- and 3-parameter gamma distribution models directly using function <a href="https://genomaths.github.io/methylit/reference/nonlinearFitDist.html">nonlinearFitDist</a>.</p>
<div id="potential-dmps-estimated-with-2-parameter-gamma-distribution-model" class="section level3">
<h3 class="hasAnchor">
<a href="#potential-dmps-estimated-with-2-parameter-gamma-distribution-model" class="anchor"></a>Potential DMPs estimated with 2-parameter gamma distribution model</h3>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb5-1" data-line-number="1">nlms.g2p &lt;-<span class="st"> </span><span class="kw"><a href="../reference/nonlinearFitDist.html">nonlinearFitDist</a></span>(divs, <span class="dt">column =</span> 9L, <span class="dt">verbose =</span> <span class="ot">FALSE</span>, <span class="dt">num.cores =</span> 6L,</a>
<a class="sourceLine" id="cb5-2" data-line-number="2">                            <span class="dt">dist.name =</span> <span class="st">"Gamma2P"</span>)</a>
<a class="sourceLine" id="cb5-3" data-line-number="3"></a>
<a class="sourceLine" id="cb5-4" data-line-number="4"><span class="co"># Potential DMPs from 'Gamma2P' model</span></a>
<a class="sourceLine" id="cb5-5" data-line-number="5">pDMPs.g2p &lt;-<span class="st"> </span><span class="kw"><a href="../reference/getPotentialDIMP.html">getPotentialDIMP</a></span>(<span class="dt">LR =</span> divs, <span class="dt">nlms =</span> nlms.g2p,  <span class="dt">div.col =</span> 9L, </a>
<a class="sourceLine" id="cb5-6" data-line-number="6">                             <span class="dt">tv.cut =</span> <span class="fl">0.68</span>, <span class="dt">tv.col =</span> <span class="dv">7</span>, <span class="dt">alpha =</span> <span class="fl">0.05</span>, </a>
<a class="sourceLine" id="cb5-7" data-line-number="7">                             <span class="dt">dist.name =</span> <span class="st">"Gamma2P"</span>)</a></code></pre></div>
</div>
<div id="potential-dmps-estimated-with-3-parameter-gamma-distribution-model" class="section level3">
<h3 class="hasAnchor">
<a href="#potential-dmps-estimated-with-3-parameter-gamma-distribution-model" class="anchor"></a>Potential DMPs estimated with 3-parameter gamma distribution model</h3>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb6-1" data-line-number="1">nlms.g3p &lt;-<span class="st"> </span><span class="kw"><a href="../reference/nonlinearFitDist.html">nonlinearFitDist</a></span>(divs, <span class="dt">column =</span> 9L, <span class="dt">verbose =</span> <span class="ot">FALSE</span>, <span class="dt">num.cores =</span> 6L,</a>
<a class="sourceLine" id="cb6-2" data-line-number="2">                            <span class="dt">dist.name =</span> <span class="st">"Gamma3P"</span>)</a>
<a class="sourceLine" id="cb6-3" data-line-number="3"></a>
<a class="sourceLine" id="cb6-4" data-line-number="4"><span class="co"># Potential DMPs from 'Gamma2P' model</span></a>
<a class="sourceLine" id="cb6-5" data-line-number="5">pDMPs.g3p &lt;-<span class="st"> </span><span class="kw"><a href="../reference/getPotentialDIMP.html">getPotentialDIMP</a></span>(<span class="dt">LR =</span> divs, <span class="dt">nlms =</span> nlms.g3p,  <span class="dt">div.col =</span> 9L, </a>
<a class="sourceLine" id="cb6-6" data-line-number="6">                             <span class="dt">tv.cut =</span> <span class="fl">0.68</span>, <span class="dt">tv.col =</span> <span class="dv">7</span>, <span class="dt">alpha =</span> <span class="fl">0.05</span>, </a>
<a class="sourceLine" id="cb6-7" data-line-number="7">                             <span class="dt">dist.name =</span> <span class="st">"Gamma3P"</span>)</a></code></pre></div>
</div>
</div>
<div id="cutpoint-estimation" class="section level2">
<h2 class="hasAnchor">
<a href="#cutpoint-estimation" class="anchor"></a>Cutpoint estimation</h2>
<p>As a result of the natural spontaneous variation, naturally occurring DMPs can be identified in samples from the control and treatment populations. Machine-learning algorithms implemented in Methyl-IT are applied to discriminate treatment-induced DMPs from those naturally generated.</p>
<p>The simple cutpoint estimation available in Methyl-IT is based on the application of Youden index <span class="citation">(Youden 1950)</span>. Although cutpoints are estimated for a single variable, the classification performance can be evaluated for several variables and applying different model classifiers.</p>
<p>In the current example, the column carrying <em>TV</em> (<em>div.col</em> = 7L) will be used to estimate the cutpoint. The column values will be expressed in terms of <span class="math inline">\(TV_d=|p_{tt}-p_{ct}|\)</span>. A minimum cutpoint value for <em>TV</em> derived from the minimum 95% quantile (<em>tv.cut</em> = 0.92) found in the treatment group will be applied (see <a href="https://genomaths.github.io/Methylation_analysis_with_Methyl-IT.html">Methylation analysis with Methyl-IT</a>).</p>
<p>Next, a logistic model classifier will be fitted with the 60% (<em>prop</em> = 0.6) of the raw data (training set) and then the resting 40% of individual samples will be used to evaluate the model performance. The predictor variable included in the model are specified with function parameter <em>column</em> (for more detail see <a href="https://genomaths.github.io/methylit/reference/estimateCutPoint.html"><em>estimateCutPoint</em></a> or type ?estimateCutPoint in R console).</p>
<div id="simple-cutpoint-estimation-for-gamma2p-model" class="section level3">
<h3 class="hasAnchor">
<a href="#simple-cutpoint-estimation-for-gamma2p-model" class="anchor"></a>Simple cutpoint estimation for Gamma2P model</h3>
<p>Here, we use the results of modeling the distribution of the Hellinger divergence (<em>HD</em>) of methylation levels through a 2-parameter gamma probability distribution model. The critical values for <span class="math inline">\(HD_{\alpha = 0.05}^{CT_{G2P}}\)</span> used to get potential DMPs were:</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb7-1" data-line-number="1">nams &lt;-<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/names.html">names</a></span>(nlms.g2p)</a>
<a class="sourceLine" id="cb7-2" data-line-number="2">crit &lt;-<span class="st"> </span><span class="kw"><a href="../reference/unlist.html">unlist</a></span>(<span class="kw"><a href="../reference/lapply.html">lapply</a></span>(nlms.g2p, <span class="cf">function</span>(x) <span class="kw"><a href="https://rdrr.io/r/stats/GammaDist.html">qgamma</a></span>(<span class="fl">0.95</span>, <span class="dt">shape =</span> x<span class="op">$</span>Estimate[<span class="dv">1</span>],</a>
<a class="sourceLine" id="cb7-3" data-line-number="3">                                                   <span class="dt">scale =</span> x<span class="op">$</span>Estimate[<span class="dv">2</span>])))</a>
<a class="sourceLine" id="cb7-4" data-line-number="4"><span class="kw"><a href="https://rdrr.io/r/base/names.html">names</a></span>(crit) &lt;-<span class="st"> </span>nams</a>
<a class="sourceLine" id="cb7-5" data-line-number="5">crit</a></code></pre></div>
<pre><code>##        C1        C2        C3        T1        T2        T3 
##  58.59180  57.99972  57.81016 112.40001 113.92362 114.48802</code></pre>
<p>As before the cutpoint is estimated based on ‘Youden Index’ <span class="citation">(Youden 1950)</span>. A PCA+LDA model classifier (<em>classifier</em> = “pca.lda”) is applied. That is, a principal component analysis (PCA) is applied on the original raw matrix of data and the four possible component (<em>n.pc</em> = 4) derived from the analysis are used in a further linear discriminant analysis (LDA). A scaling step is applied to the raw matrix of data before the application of the mentioned procedure (<em>center</em> = TRUE, <em>scale</em> = TRUE). Here, PCA will yield new orthogonal (non-correlated) variables, the principal components, which prevent any potential bias effect originated by any correlation or association of the original variables.</p>
<p>By using function <a href="https://genomaths.github.io/methylit/reference/estimateCutPoint.html">estimateCutPoint</a>, we can estimate the cutpoint, based on <em>HD</em> (<em>div.col</em> = 9L) or on <span class="math inline">\(TV_d\)</span> (<em>div.col</em> = 7L):</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb9-1" data-line-number="1"><span class="co"># Cutpoint estimation for the FT approach using the ECDF critical value</span></a>
<a class="sourceLine" id="cb9-2" data-line-number="2">cut.g2p =<span class="st"> </span><span class="kw"><a href="../reference/estimateCutPoint.html">estimateCutPoint</a></span>(<span class="dt">LR =</span> pDMPs.g2p, <span class="dt">simple =</span> <span class="ot">TRUE</span>,</a>
<a class="sourceLine" id="cb9-3" data-line-number="3">                            <span class="dt">column =</span> <span class="kw"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="dt">hdiv =</span> <span class="ot">TRUE</span>, <span class="dt">bay.TV =</span> <span class="ot">TRUE</span>, </a>
<a class="sourceLine" id="cb9-4" data-line-number="4">                                       <span class="dt">wprob =</span> <span class="ot">TRUE</span>, <span class="dt">pos =</span> <span class="ot">TRUE</span>),</a>
<a class="sourceLine" id="cb9-5" data-line-number="5">                            <span class="dt">classifier1 =</span> <span class="st">"pca.lda"</span>, <span class="dt">n.pc =</span> <span class="dv">4</span>, </a>
<a class="sourceLine" id="cb9-6" data-line-number="6">                            <span class="dt">control.names =</span> control.nam,</a>
<a class="sourceLine" id="cb9-7" data-line-number="7">                            <span class="dt">treatment.names =</span> treatment.nam,</a>
<a class="sourceLine" id="cb9-8" data-line-number="8">                            <span class="dt">center =</span> <span class="ot">TRUE</span>, <span class="dt">scale =</span> <span class="ot">TRUE</span>,</a>
<a class="sourceLine" id="cb9-9" data-line-number="9">                            <span class="dt">clas.perf =</span> <span class="ot">TRUE</span>, <span class="dt">prop =</span> <span class="fl">0.6</span>,</a>
<a class="sourceLine" id="cb9-10" data-line-number="10">                           <span class="dt">div.col =</span> 9L)</a>
<a class="sourceLine" id="cb9-11" data-line-number="11">cut.g2p</a></code></pre></div>
<pre><code>## Cutpoint estimation with 'Youden Index' 
## Simple cutpoint estimation 
## Cutpoint = 114.22 
## 
## Cytosine sites from treatment have divergence values &gt;= 114.22 
## 
## The accessible objects in the output list are: 
##                     Length Class           Mode     
## cutpoint            1      -none-          numeric  
## testSetPerformance  6      confusionMatrix list     
## testSetModel.FDR    1      -none-          numeric  
## model               2      pcaLDA          list     
## modelConfMatrix     6      confusionMatrix list     
## initModel           1      -none-          character
## postProbCut         1      -none-          logical  
## postCut             1      -none-          logical  
## classifier          1      -none-          character
## statistic           1      -none-          logical  
## optStatVal          1      -none-          logical  
## cutpData            1      -none-          logical  
## initModelConfMatrix 6      confusionMatrix list</code></pre>
<p>As indicated above, the model classifier performance and its corresponding false discovery rate can be retrieved as:</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb11-1" data-line-number="1">cut.g2p<span class="op">$</span>testSetPerformance</a></code></pre></div>
<pre><code>## Confusion Matrix and Statistics
## 
##           Reference
## Prediction   CT   TT
##         CT  319    0
##         TT    0 3544
##                                     
##                Accuracy : 1         
##                  95% CI : (0.999, 1)
##     No Information Rate : 0.9174    
##     P-Value [Acc &gt; NIR] : &lt; 2.2e-16 
##                                     
##                   Kappa : 1         
##                                     
##  Mcnemar's Test P-Value : NA        
##                                     
##             Sensitivity : 1.0000    
##             Specificity : 1.0000    
##          Pos Pred Value : 1.0000    
##          Neg Pred Value : 1.0000    
##              Prevalence : 0.9174    
##          Detection Rate : 0.9174    
##    Detection Prevalence : 0.9174    
##       Balanced Accuracy : 1.0000    
##                                     
##        'Positive' Class : TT        
## </code></pre>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb13-1" data-line-number="1">cut.g2p<span class="op">$</span>testSetModel.FDR</a></code></pre></div>
<pre><code>## [1] 0</code></pre>
<p>Here, DMP classification is modeled with PCA+QDA classifier (<em>classifier</em> = “pca.lda”). That is, principal component analysis (PCA) is applied on the original raw matrix of data and the four possible component (<em>n.pc</em> = 4) are used in a further linear discriminant analysis (LDA). A scaling step is applied to the raw matrix of data before the application of the mentioned procedure (<em>center</em> = TRUE, <em>scale</em> = TRUE). Next, a different model classifier can be applied to model the classification derived from the previous cutpoint estimation.</p>
</div>
<div id="simple-cutpoint-estimation-for-gamma3p-model" class="section level3">
<h3 class="hasAnchor">
<a href="#simple-cutpoint-estimation-for-gamma3p-model" class="anchor"></a>Simple cutpoint estimation for Gamma3P model</h3>
<p>The same analyses for the cutpoint estimation can be performed for 3P gamma model</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb15-1" data-line-number="1"><span class="co"># Cutpoint estimation for the FT approach using the ECDF critical value</span></a>
<a class="sourceLine" id="cb15-2" data-line-number="2">cut.g3p =<span class="st"> </span><span class="kw"><a href="../reference/estimateCutPoint.html">estimateCutPoint</a></span>(<span class="dt">LR =</span> pDMPs.g3p, <span class="dt">simple =</span> <span class="ot">TRUE</span>,</a>
<a class="sourceLine" id="cb15-3" data-line-number="3">                            <span class="dt">column =</span> <span class="kw"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="dt">hdiv =</span> <span class="ot">TRUE</span>, <span class="dt">bay.TV =</span> <span class="ot">TRUE</span>, </a>
<a class="sourceLine" id="cb15-4" data-line-number="4">                                       <span class="dt">wprob =</span> <span class="ot">TRUE</span>, <span class="dt">pos =</span> <span class="ot">TRUE</span>),</a>
<a class="sourceLine" id="cb15-5" data-line-number="5">                            <span class="dt">classifier1 =</span> <span class="st">"pca.lda"</span>, <span class="dt">n.pc =</span> <span class="dv">4</span>, </a>
<a class="sourceLine" id="cb15-6" data-line-number="6">                            <span class="dt">control.names =</span> control.nam,</a>
<a class="sourceLine" id="cb15-7" data-line-number="7">                            <span class="dt">treatment.names =</span> treatment.nam,</a>
<a class="sourceLine" id="cb15-8" data-line-number="8">                            <span class="dt">center =</span> <span class="ot">TRUE</span>, <span class="dt">scale =</span> <span class="ot">TRUE</span>,</a>
<a class="sourceLine" id="cb15-9" data-line-number="9">                            <span class="dt">clas.perf =</span> <span class="ot">TRUE</span>, <span class="dt">prop =</span> <span class="fl">0.6</span>,</a>
<a class="sourceLine" id="cb15-10" data-line-number="10">                           <span class="dt">div.col =</span> 9L)</a>
<a class="sourceLine" id="cb15-11" data-line-number="11">cut.g3p</a></code></pre></div>
<pre><code>## Cutpoint estimation with 'Youden Index' 
## Simple cutpoint estimation 
## Cutpoint = 115.24 
## 
## Cytosine sites from treatment have divergence values &gt;= 115.24 
## 
## The accessible objects in the output list are: 
##                     Length Class           Mode     
## cutpoint            1      -none-          numeric  
## testSetPerformance  6      confusionMatrix list     
## testSetModel.FDR    1      -none-          numeric  
## model               2      pcaLDA          list     
## modelConfMatrix     6      confusionMatrix list     
## initModel           1      -none-          character
## postProbCut         1      -none-          logical  
## postCut             1      -none-          logical  
## classifier          1      -none-          character
## statistic           1      -none-          logical  
## optStatVal          1      -none-          logical  
## cutpData            1      -none-          logical  
## initModelConfMatrix 6      confusionMatrix list</code></pre>
<p>As indicated above, the model classifier performance and its corresponding false discovery rate can be retrieved as:</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb17-1" data-line-number="1">cut.g3p<span class="op">$</span>testSetPerformance</a></code></pre></div>
<pre><code>## Confusion Matrix and Statistics
## 
##           Reference
## Prediction   CT   TT
##         CT  309    0
##         TT    0 3483
##                                     
##                Accuracy : 1         
##                  95% CI : (0.999, 1)
##     No Information Rate : 0.9185    
##     P-Value [Acc &gt; NIR] : &lt; 2.2e-16 
##                                     
##                   Kappa : 1         
##                                     
##  Mcnemar's Test P-Value : NA        
##                                     
##             Sensitivity : 1.0000    
##             Specificity : 1.0000    
##          Pos Pred Value : 1.0000    
##          Neg Pred Value : 1.0000    
##              Prevalence : 0.9185    
##          Detection Rate : 0.9185    
##    Detection Prevalence : 0.9185    
##       Balanced Accuracy : 1.0000    
##                                     
##        'Positive' Class : TT        
## </code></pre>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb19-1" data-line-number="1">cut.g3p<span class="op">$</span>testSetModel.FDR</a></code></pre></div>
<pre><code>## [1] 0</code></pre>
</div>
<div id="dmp-prediction-based-on-classification-models" class="section level3">
<h3 class="hasAnchor">
<a href="#dmp-prediction-based-on-classification-models" class="anchor"></a>DMP prediction based on classification models</h3>
<p>The model obtained in the previous step can be used for further prediction with function <a href="https://rdrr.io/github/genomaths/MethylIT.utils/man/predict.ProbDistr.html">predict</a> from MethylIT.utils package. For example, we would take a random sample and run:</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb21-1" data-line-number="1"><span class="kw"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span>(<span class="dv">1</span>)</a>
<a class="sourceLine" id="cb21-2" data-line-number="2">randsampl &lt;-<span class="st"> </span><span class="kw"><a href="../reference/unlist.html">unlist</a></span>(pDMPs.g3p)</a>
<a class="sourceLine" id="cb21-3" data-line-number="3">randsampl &lt;-<span class="st"> </span>randsampl[<span class="kw"><a href="https://rdrr.io/r/base/sample.html">sample.int</a></span>(<span class="kw"><a href="https://rdrr.io/r/base/length.html">length</a></span>(randsampl), <span class="dv">10</span>)]</a>
<a class="sourceLine" id="cb21-4" data-line-number="4"></a>
<a class="sourceLine" id="cb21-5" data-line-number="5">pred &lt;-<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span>(cut.g3p<span class="op">$</span>model, <span class="dt">newdata =</span> randsampl)</a>
<a class="sourceLine" id="cb21-6" data-line-number="6">pred</a></code></pre></div>
<pre><code>## $class
##  [1] CT TT TT TT TT TT TT TT TT TT
## Levels: CT TT
## 
## $posterior
##                 CT          TT
##  [1,] 1.000000e+00 1.19242e-08
##  [2,] 5.231187e-46 1.00000e+00
##  [3,] 2.136182e-45 1.00000e+00
##  [4,] 6.739051e-47 1.00000e+00
##  [5,] 2.015394e-46 1.00000e+00
##  [6,] 2.379968e-46 1.00000e+00
##  [7,] 3.473689e-46 1.00000e+00
##  [8,] 1.760048e-46 1.00000e+00
##  [9,] 7.640639e-47 1.00000e+00
## [10,] 3.254017e-47 1.00000e+00
## 
## $x
##             LD1
##  [1,] -7.465499
##  [2,]  1.041471
##  [3,]  0.943772
##  [4,]  1.183774
##  [5,]  1.107704
##  [6,]  1.096158
##  [7,]  1.069901
##  [8,]  1.117111
##  [9,]  1.175055
## [10,]  1.234328</code></pre>
<p>The variable <em>pred$posterior</em> provides the posterior classification probabilities that a DMP could belong to control (<em>CT</em>) or to treatment (<em>TT</em>) group. The variable ‘<em>x</em>’ provides the cytosine methylation changes in terms of its values in the linear discriminant function LD1. Notice that, for each row, the sum of posterior probabilities is equal 1. By default, individuals with <em>TT</em> posterior probabilities greater than 0.5 are predicted to belong to the treatment class. For example:</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb23-1" data-line-number="1">classfiction =<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/rep.html">rep</a></span>(<span class="st">"CT"</span>, <span class="dv">10</span>)</a>
<a class="sourceLine" id="cb23-2" data-line-number="2">classfiction[pred<span class="op">$</span>posterior[, <span class="dv">2</span>] <span class="op">&gt;</span><span class="st"> </span><span class="fl">0.5</span>] &lt;-<span class="st"> "TT"</span></a>
<a class="sourceLine" id="cb23-3" data-line-number="3">classfiction</a></code></pre></div>
<pre><code>##  [1] "CT" "TT" "TT" "TT" "TT" "TT" "TT" "TT" "TT" "TT"</code></pre>
<p>We can be more strict increasing the posterior classification probability cutoff</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb25-1" data-line-number="1">classfiction =<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/rep.html">rep</a></span>(<span class="st">"CT"</span>, <span class="dv">10</span>)</a>
<a class="sourceLine" id="cb25-2" data-line-number="2">classfiction[pred<span class="op">$</span>posterior[, <span class="dv">2</span>] <span class="op">&gt;</span><span class="st"> </span><span class="fl">0.7</span>] &lt;-<span class="st"> "TT"</span></a>
<a class="sourceLine" id="cb25-3" data-line-number="3">classfiction</a></code></pre></div>
<pre><code>##  [1] "CT" "TT" "TT" "TT" "TT" "TT" "TT" "TT" "TT" "TT"</code></pre>
<p>The posterior classification probability cutoff can be controlled with parameter <em>post.cut</em> from <a href="https://genomaths.github.io/methylit/reference/estimateCutPoint.html">estimateCutPoint</a> function (default: <span class="math inline">\(post.cut=0.5\)</span>).</p>
</div>
</div>
<div id="machine-learning-ml-based-approach-to-search-for-an-optimal-cutpoint" class="section level2">
<h2 class="hasAnchor">
<a href="#machine-learning-ml-based-approach-to-search-for-an-optimal-cutpoint" class="anchor"></a>Machine-learning (ML) based approach to search for an optimal cutpoint</h2>
<p>In the next example the cutpoint estimation for the Hellinger divergence of methylation levels (<em>div.col</em> = 9L) is accomplished. Function <em>estimateCutPoint</em> can be used to search for a cutpoint as well. Two model classifiers can be used. <em>classifiers1</em> will be used to estimate the posterior classification probabilities of DMP into those from control and those from treatment. These probabilities are then used to estimate the cutpoint in the range of values from, say, 0.5 to 0.8. Next, a <em>classifier2</em> will be used to evaluate the classification performance. In this case, the search for an optimal cutpoint is accomplished maximizing the accuracy (<em>stat</em> = 0) of <em>classifier2</em>.</p>
<div id="ml-cutpoint-estimation-for-potential-dmps-based-on-gamma2p-model" class="section level3">
<h3 class="hasAnchor">
<a href="#ml-cutpoint-estimation-for-potential-dmps-based-on-gamma2p-model" class="anchor"></a>ML cutpoint estimation for potential DMPs based on Gamma2P model</h3>
<p>The ML search for an optimal cutpoint is accomplished in the set of potential DMPs, which were identified using a Gamma2P probability distribution model as null hypothesis.</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb27-1" data-line-number="1">cut.g2p =<span class="st"> </span><span class="kw"><a href="../reference/estimateCutPoint.html">estimateCutPoint</a></span>(<span class="dt">LR =</span> pDMPs.g2p, <span class="dt">simple =</span> <span class="ot">FALSE</span>,</a>
<a class="sourceLine" id="cb27-2" data-line-number="2">                            <span class="dt">column =</span> <span class="kw"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="dt">hdiv =</span> <span class="ot">TRUE</span>, <span class="dt">bay.TV =</span> <span class="ot">TRUE</span>, </a>
<a class="sourceLine" id="cb27-3" data-line-number="3">                                       <span class="dt">wprob =</span> <span class="ot">TRUE</span>, <span class="dt">pos =</span> <span class="ot">TRUE</span>),</a>
<a class="sourceLine" id="cb27-4" data-line-number="4">                            <span class="dt">classifier1 =</span> <span class="st">"pca.lda"</span>, </a>
<a class="sourceLine" id="cb27-5" data-line-number="5">                            <span class="dt">classifier2 =</span> <span class="st">"pca.qda"</span>, <span class="dt">stat =</span> <span class="dv">0</span>,</a>
<a class="sourceLine" id="cb27-6" data-line-number="6">                            <span class="dt">control.names =</span> control.nam, </a>
<a class="sourceLine" id="cb27-7" data-line-number="7">                            <span class="dt">treatment.names =</span> treatment.nam, </a>
<a class="sourceLine" id="cb27-8" data-line-number="8">                            <span class="dt">cut.values =</span> <span class="kw"><a href="https://rdrr.io/r/base/seq.html">seq</a></span>(<span class="dv">45</span>, <span class="dv">114</span>, <span class="dv">1</span>), <span class="dt">post.cut =</span> <span class="fl">0.5</span>,</a>
<a class="sourceLine" id="cb27-9" data-line-number="9">                            <span class="dt">clas.perf =</span> <span class="ot">TRUE</span>, <span class="dt">prop =</span> <span class="fl">0.6</span>,</a>
<a class="sourceLine" id="cb27-10" data-line-number="10">                            <span class="dt">center =</span> <span class="ot">TRUE</span>, <span class="dt">scale =</span> <span class="ot">TRUE</span>,</a>
<a class="sourceLine" id="cb27-11" data-line-number="11">                            <span class="dt">n.pc =</span> <span class="dv">4</span>, <span class="dt">div.col =</span> 9L)</a>
<a class="sourceLine" id="cb27-12" data-line-number="12">cut.g2p</a></code></pre></div>
<pre><code>## Cutpoint estimation with 'pca.lda' classifier 
## Cutpoint search performed using model posterior probabilities 
## 
## Posterior probability used to get the cutpoint = 0.5 
## Cytosine sites with treatment PostProbCut &gt;= 0.5 have a 
## divergence value &gt;= 112.4247 
## 
## Optimized statistic: Accuracy = 1 
## Cutpoint = 112.42 
## 
## Model classifier 'pca.qda' 
## 
## The accessible objects in the output list are: 
##                    Length Class           Mode     
## cutpoint           1      -none-          numeric  
## testSetPerformance 6      confusionMatrix list     
## testSetModel.FDR   1      -none-          numeric  
## model              2      pcaQDA          list     
## modelConfMatrix    6      confusionMatrix list     
## initModel          1      -none-          character
## postProbCut        1      -none-          numeric  
## postCut            1      -none-          numeric  
## classifier         1      -none-          character
## statistic          1      -none-          character
## optStatVal         1      -none-          numeric  
## cutpData           1      -none-          logical</code></pre>
<p>Model performance in the test dataset is:</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb29-1" data-line-number="1">cut.g2p<span class="op">$</span>testSetPerformance</a></code></pre></div>
<pre><code>## Confusion Matrix and Statistics
## 
##           Reference
## Prediction   CT   TT
##         CT 1274    0
##         TT    0 3580
##                                      
##                Accuracy : 1          
##                  95% CI : (0.9992, 1)
##     No Information Rate : 0.7375     
##     P-Value [Acc &gt; NIR] : &lt; 2.2e-16  
##                                      
##                   Kappa : 1          
##                                      
##  Mcnemar's Test P-Value : NA         
##                                      
##             Sensitivity : 1.0000     
##             Specificity : 1.0000     
##          Pos Pred Value : 1.0000     
##          Neg Pred Value : 1.0000     
##              Prevalence : 0.7375     
##          Detection Rate : 0.7375     
##    Detection Prevalence : 0.7375     
##       Balanced Accuracy : 1.0000     
##                                      
##        'Positive' Class : TT         
## </code></pre>
<p>Model performance in in the whole dataset is:</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb31-1" data-line-number="1">cut.g2p<span class="op">$</span>modelConfMatrix</a></code></pre></div>
<pre><code>## Confusion Matrix and Statistics
## 
##           Reference
## Prediction   CT   TT
##         CT 3184    0
##         TT    0 8948
##                                      
##                Accuracy : 1          
##                  95% CI : (0.9997, 1)
##     No Information Rate : 0.7376     
##     P-Value [Acc &gt; NIR] : &lt; 2.2e-16  
##                                      
##                   Kappa : 1          
##                                      
##  Mcnemar's Test P-Value : NA         
##                                      
##             Sensitivity : 1.0000     
##             Specificity : 1.0000     
##          Pos Pred Value : 1.0000     
##          Neg Pred Value : 1.0000     
##              Prevalence : 0.7376     
##          Detection Rate : 0.7376     
##    Detection Prevalence : 0.7376     
##       Balanced Accuracy : 1.0000     
##                                      
##        'Positive' Class : TT         
## </code></pre>
<p>The False discovery rate is:</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb33-1" data-line-number="1">cut.g2p<span class="op">$</span>testSetModel.FDR</a></code></pre></div>
<pre><code>## [1] 0</code></pre>
<p>The model classifier <em>PCA+LDA</em> has enough discriminatory power to discriminate control DMP from those induced by the treatment for <em>HD</em> values <span class="math inline">\(112.4247 \le HD\)</span>.</p>
<p>The probabilities <span class="math inline">\(P(HD \le 122.43)\)</span> to observe a cytosine site with <span class="math inline">\(HD \le 112.4247\)</span> on each individual is:</p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb35-1" data-line-number="1">nams &lt;-<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/names.html">names</a></span>(nlms.g2p)</a>
<a class="sourceLine" id="cb35-2" data-line-number="2">crit &lt;-<span class="st"> </span><span class="kw"><a href="../reference/unlist.html">unlist</a></span>(<span class="kw"><a href="../reference/lapply.html">lapply</a></span>(nlms.g2p, <span class="cf">function</span>(x) <span class="kw"><a href="https://rdrr.io/r/stats/GammaDist.html">pgamma</a></span>(cut.g2p<span class="op">$</span>cutpoint, <span class="dt">shape =</span> x<span class="op">$</span>Estimate[<span class="dv">1</span>],</a>
<a class="sourceLine" id="cb35-3" data-line-number="3">                                                   <span class="dt">scale =</span> x<span class="op">$</span>Estimate[<span class="dv">2</span>])))</a>
<a class="sourceLine" id="cb35-4" data-line-number="4"><span class="kw"><a href="https://rdrr.io/r/base/names.html">names</a></span>(crit) &lt;-<span class="st"> </span>nams</a>
<a class="sourceLine" id="cb35-5" data-line-number="5">crit</a></code></pre></div>
<pre><code>##        C1        C2        C3        T1        T2        T3 
## 0.9964704 0.9966560 0.9967314 0.9500279 0.9483024 0.9476610</code></pre>
<p>In other words, most of the methylation changes are not (and should not be) considered DMPs. Notice that although the same <em>HD</em> value could be found in the same differentially methylated cytosine site in control and treatment, if the probabilities distributions of the information divergences (null hypotheses) from control and treatment are different, then these DMPs can be distinguished.</p>
</div>
<div id="ml-cutpoint-estimation-for-potential-dmps-based-on-gamma3p-model" class="section level3">
<h3 class="hasAnchor">
<a href="#ml-cutpoint-estimation-for-potential-dmps-based-on-gamma3p-model" class="anchor"></a>ML cutpoint estimation for potential DMPs based on Gamma3P model</h3>
<p>Likewise, for the 3-parameter gamma model we can search for an optimal cutpoint:</p>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb37-1" data-line-number="1">cut.g3p =<span class="st"> </span><span class="kw"><a href="../reference/estimateCutPoint.html">estimateCutPoint</a></span>(<span class="dt">LR =</span> pDMPs.g3p, <span class="dt">simple =</span> <span class="ot">FALSE</span>,</a>
<a class="sourceLine" id="cb37-2" data-line-number="2">                            <span class="dt">column =</span> <span class="kw"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="dt">hdiv =</span> <span class="ot">TRUE</span>, <span class="dt">TV =</span> <span class="ot">TRUE</span>, </a>
<a class="sourceLine" id="cb37-3" data-line-number="3">                                       <span class="dt">wprob =</span> <span class="ot">TRUE</span>, <span class="dt">pos =</span> <span class="ot">TRUE</span>),</a>
<a class="sourceLine" id="cb37-4" data-line-number="4">                            <span class="dt">classifier1 =</span> <span class="st">"pca.lda"</span>, </a>
<a class="sourceLine" id="cb37-5" data-line-number="5">                            <span class="dt">classifier2 =</span> <span class="st">"pca.qda"</span>, <span class="dt">stat =</span> <span class="dv">0</span>,</a>
<a class="sourceLine" id="cb37-6" data-line-number="6">                            <span class="dt">control.names =</span> control.nam, </a>
<a class="sourceLine" id="cb37-7" data-line-number="7">                            <span class="dt">treatment.names =</span> treatment.nam, </a>
<a class="sourceLine" id="cb37-8" data-line-number="8">                            <span class="dt">cut.values =</span> <span class="kw"><a href="https://rdrr.io/r/base/seq.html">seq</a></span>(<span class="dv">45</span>, <span class="dv">114</span>, <span class="dv">1</span>), <span class="dt">post.cut =</span> <span class="fl">0.5</span>,</a>
<a class="sourceLine" id="cb37-9" data-line-number="9">                            <span class="dt">clas.perf =</span> <span class="ot">TRUE</span>, <span class="dt">prop =</span> <span class="fl">0.6</span>,</a>
<a class="sourceLine" id="cb37-10" data-line-number="10">                            <span class="dt">center =</span> <span class="ot">TRUE</span>, <span class="dt">scale =</span> <span class="ot">TRUE</span>,</a>
<a class="sourceLine" id="cb37-11" data-line-number="11">                            <span class="dt">n.pc =</span> <span class="dv">4</span>, <span class="dt">div.col =</span> 9L)</a>
<a class="sourceLine" id="cb37-12" data-line-number="12">cut.g3p</a></code></pre></div>
<pre><code>## Cutpoint estimation with 'pca.lda' classifier 
## Cutpoint search performed using model posterior probabilities 
## 
## Posterior probability used to get the cutpoint = 0.5 
## Cytosine sites with treatment PostProbCut &gt;= 0.5 have a 
## divergence value &gt;= 113.497 
## 
## Optimized statistic: Accuracy = 1 
## Cutpoint = 113.5 
## 
## Model classifier 'pca.qda' 
## 
## The accessible objects in the output list are: 
##                    Length Class           Mode     
## cutpoint           1      -none-          numeric  
## testSetPerformance 6      confusionMatrix list     
## testSetModel.FDR   1      -none-          numeric  
## model              2      pcaQDA          list     
## modelConfMatrix    6      confusionMatrix list     
## initModel          1      -none-          character
## postProbCut        1      -none-          numeric  
## postCut            1      -none-          numeric  
## classifier         1      -none-          character
## statistic          1      -none-          character
## optStatVal         1      -none-          numeric  
## cutpData           1      -none-          logical</code></pre>
<p>DMPs are identified with function <a href="https://genomaths.github.io/methylit/reference/selectDIMP.html">selectDIMP</a></p>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb39-1" data-line-number="1">g2p.dmps &lt;-<span class="st"> </span><span class="kw"><a href="../reference/selectDIMP.html">selectDIMP</a></span>(pDMPs.g2p, <span class="dt">div.col =</span> 9L, <span class="dt">cutpoint =</span> cut.g2p<span class="op">$</span>cutpoint)</a>
<a class="sourceLine" id="cb39-2" data-line-number="2">g3p.dmps &lt;-<span class="st"> </span><span class="kw"><a href="../reference/selectDIMP.html">selectDIMP</a></span>(pDMPs.g3p, <span class="dt">div.col =</span> 9L, <span class="dt">cutpoint =</span> cut.g3p<span class="op">$</span>cutpoint)</a></code></pre></div>
</div>
</div>
<div id="dmps-estimated-with-fishers-exact-test-ft" class="section level2">
<h2 class="hasAnchor">
<a href="#dmps-estimated-with-fishers-exact-test-ft" class="anchor"></a>DMPs estimated with Fisher’s exact Test (FT)</h2>
<p>For comparison purposes DMPs are estimated with Fisher’s exact test as well.</p>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb40-1" data-line-number="1">ft. =<span class="st"> </span><span class="kw"><a href="../reference/FisherTest.html">FisherTest</a></span>(<span class="dt">LR =</span> divs, <span class="dt">tv.cut =</span> <span class="fl">0.68</span>, <span class="dt">pAdjustMethod =</span> <span class="st">"BH"</span>,</a>
<a class="sourceLine" id="cb40-2" data-line-number="2">                     <span class="dt">pvalCutOff =</span> <span class="fl">0.05</span>, <span class="dt">num.cores =</span> 4L,</a>
<a class="sourceLine" id="cb40-3" data-line-number="3">                     <span class="dt">verbose =</span> <span class="ot">FALSE</span>, <span class="dt">saveAll =</span> <span class="ot">FALSE</span>) </a>
<a class="sourceLine" id="cb40-4" data-line-number="4"></a>
<a class="sourceLine" id="cb40-5" data-line-number="5">ft.dmps &lt;-<span class="st"> </span><span class="kw"><a href="../reference/getPotentialDIMP.html">getPotentialDIMP</a></span>(<span class="dt">LR =</span> ft., <span class="dt">div.col =</span> 9L, <span class="dt">dist.name =</span> <span class="st">"None"</span>,</a>
<a class="sourceLine" id="cb40-6" data-line-number="6">                            <span class="dt">tv.cut =</span> <span class="fl">0.68</span>, <span class="dt">tv.col =</span> <span class="dv">7</span>, <span class="dt">alpha =</span> <span class="fl">0.05</span>)</a></code></pre></div>
</div>
<div id="classification-performance-of-dmp-classification" class="section level2">
<h2 class="hasAnchor">
<a href="#classification-performance-of-dmp-classification" class="anchor"></a>Classification performance of DMP classification</h2>
<p>After the cutpoint application to select DMPs, a Monte Carlo (bootstrap) analysis reporting several classifier performance indicators can be accomplished by using function <a href="https://genomaths.github.io/MethylIT_HTML_Manual/evaluateDIMPclass.html"><em>evaluateDIMPclass</em></a> and its settings <em>output = “mc.val”</em> and <em>num.boot</em>.</p>
<div id="classification-performance-for-dmps-based-on-gamma2p-model" class="section level3">
<h3 class="hasAnchor">
<a href="#classification-performance-for-dmps-based-on-gamma2p-model" class="anchor"></a>Classification performance for DMPs based on Gamma2P model</h3>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb41-1" data-line-number="1">g2p.class =<span class="st"> </span><span class="kw"><a href="../reference/evaluateDIMPclass.html">evaluateDIMPclass</a></span>(<span class="dt">LR =</span> g2p.dmps, <span class="dt">control.names =</span> control.nam,</a>
<a class="sourceLine" id="cb41-2" data-line-number="2">                           <span class="dt">treatment.names =</span> treatment.nam,</a>
<a class="sourceLine" id="cb41-3" data-line-number="3">                           <span class="dt">column =</span> <span class="kw"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="dt">hdiv =</span> <span class="ot">TRUE</span>, <span class="dt">TV =</span> <span class="ot">TRUE</span>, </a>
<a class="sourceLine" id="cb41-4" data-line-number="4">                                      <span class="dt">wprob =</span> <span class="ot">TRUE</span>, <span class="dt">pos =</span> <span class="ot">TRUE</span>),</a>
<a class="sourceLine" id="cb41-5" data-line-number="5">                           <span class="dt">classifier =</span> <span class="st">"pca.qda"</span>, <span class="dt">n.pc =</span> <span class="dv">4</span>, </a>
<a class="sourceLine" id="cb41-6" data-line-number="6">                           <span class="dt">center =</span> <span class="ot">TRUE</span>, <span class="dt">scale =</span> <span class="ot">TRUE</span>, <span class="dt">num.boot =</span> <span class="dv">300</span>,</a>
<a class="sourceLine" id="cb41-7" data-line-number="7">                           <span class="dt">output =</span> <span class="st">"all"</span>, <span class="dt">prop =</span> <span class="fl">0.6</span></a>
<a class="sourceLine" id="cb41-8" data-line-number="8">)</a>
<a class="sourceLine" id="cb41-9" data-line-number="9">g2p.class<span class="op">$</span>mc.val</a></code></pre></div>
<pre><code>##     Accuracy     Kappa   AccuracyLower    AccuracyUpper  AccuracyNull   
##  Min.   :1   Min.   :1   Min.   :0.9991   Min.   :1     Min.   :0.9139  
##  1st Qu.:1   1st Qu.:1   1st Qu.:0.9991   1st Qu.:1     1st Qu.:0.9139  
##  Median :1   Median :1   Median :0.9991   Median :1     Median :0.9139  
##  Mean   :1   Mean   :1   Mean   :0.9991   Mean   :1     Mean   :0.9139  
##  3rd Qu.:1   3rd Qu.:1   3rd Qu.:0.9991   3rd Qu.:1     3rd Qu.:0.9139  
##  Max.   :1   Max.   :1   Max.   :0.9991   Max.   :1     Max.   :0.9139  
##                                                                         
##  AccuracyPValue       McnemarPValue  Sensitivity  Specificity Pos Pred Value
##  Min.   :9.096e-154   Min.   : NA   Min.   :1    Min.   :1    Min.   :1     
##  1st Qu.:9.096e-154   1st Qu.: NA   1st Qu.:1    1st Qu.:1    1st Qu.:1     
##  Median :9.096e-154   Median : NA   Median :1    Median :1    Median :1     
##  Mean   :9.096e-154   Mean   :NaN   Mean   :1    Mean   :1    Mean   :1     
##  3rd Qu.:9.096e-154   3rd Qu.: NA   3rd Qu.:1    3rd Qu.:1    3rd Qu.:1     
##  Max.   :9.096e-154   Max.   : NA   Max.   :1    Max.   :1    Max.   :1     
##                       NA's   :300                                           
##  Neg Pred Value   Precision     Recall        F1      Prevalence    
##  Min.   :1      Min.   :1   Min.   :1   Min.   :1   Min.   :0.9139  
##  1st Qu.:1      1st Qu.:1   1st Qu.:1   1st Qu.:1   1st Qu.:0.9139  
##  Median :1      Median :1   Median :1   Median :1   Median :0.9139  
##  Mean   :1      Mean   :1   Mean   :1   Mean   :1   Mean   :0.9139  
##  3rd Qu.:1      3rd Qu.:1   3rd Qu.:1   3rd Qu.:1   3rd Qu.:0.9139  
##  Max.   :1      Max.   :1   Max.   :1   Max.   :1   Max.   :0.9139  
##                                                                     
##  Detection Rate   Detection Prevalence Balanced Accuracy
##  Min.   :0.9139   Min.   :0.9139       Min.   :1        
##  1st Qu.:0.9139   1st Qu.:0.9139       1st Qu.:1        
##  Median :0.9139   Median :0.9139       Median :1        
##  Mean   :0.9139   Mean   :0.9139       Mean   :1        
##  3rd Qu.:0.9139   3rd Qu.:0.9139       3rd Qu.:1        
##  Max.   :0.9139   Max.   :0.9139       Max.   :1        
## </code></pre>
</div>
<div id="classification-performance-for-dmps-based-on-gamma3p-model" class="section level3">
<h3 class="hasAnchor">
<a href="#classification-performance-for-dmps-based-on-gamma3p-model" class="anchor"></a>Classification performance for DMPs based on Gamma3P model</h3>
<p>Likewise the evaluation of the DMP classification performance can be accomplished for DMPs estimated based on the <span class="math inline">\('Gamma3P'\)</span> model:</p>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb43-1" data-line-number="1">g3p.class =<span class="st"> </span><span class="kw"><a href="../reference/evaluateDIMPclass.html">evaluateDIMPclass</a></span>(<span class="dt">LR =</span> g3p.dmps, <span class="dt">control.names =</span> control.nam,</a>
<a class="sourceLine" id="cb43-2" data-line-number="2">                           <span class="dt">treatment.names =</span> treatment.nam,</a>
<a class="sourceLine" id="cb43-3" data-line-number="3">                           <span class="dt">column =</span> <span class="kw"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="dt">hdiv =</span> <span class="ot">TRUE</span>, <span class="dt">TV =</span> <span class="ot">TRUE</span>, </a>
<a class="sourceLine" id="cb43-4" data-line-number="4">                                      <span class="dt">wprob =</span> <span class="ot">TRUE</span>, <span class="dt">pos =</span> <span class="ot">TRUE</span>),</a>
<a class="sourceLine" id="cb43-5" data-line-number="5">                           <span class="dt">classifier =</span> <span class="st">"pca.qda"</span>, <span class="dt">n.pc =</span> <span class="dv">4</span>, </a>
<a class="sourceLine" id="cb43-6" data-line-number="6">                           <span class="dt">center =</span> <span class="ot">TRUE</span>, <span class="dt">scale =</span> <span class="ot">TRUE</span>, <span class="dt">num.boot =</span> <span class="dv">300</span>,</a>
<a class="sourceLine" id="cb43-7" data-line-number="7">                           <span class="dt">output =</span> <span class="st">"all"</span>, <span class="dt">prop =</span> <span class="fl">0.6</span></a>
<a class="sourceLine" id="cb43-8" data-line-number="8">)</a>
<a class="sourceLine" id="cb43-9" data-line-number="9">g3p.class<span class="op">$</span>mc.val</a></code></pre></div>
<pre><code>##     Accuracy     Kappa   AccuracyLower   AccuracyUpper  AccuracyNull  
##  Min.   :1   Min.   :1   Min.   :0.999   Min.   :1     Min.   :0.914  
##  1st Qu.:1   1st Qu.:1   1st Qu.:0.999   1st Qu.:1     1st Qu.:0.914  
##  Median :1   Median :1   Median :0.999   Median :1     Median :0.914  
##  Mean   :1   Mean   :1   Mean   :0.999   Mean   :1     Mean   :0.914  
##  3rd Qu.:1   3rd Qu.:1   3rd Qu.:0.999   3rd Qu.:1     3rd Qu.:0.914  
##  Max.   :1   Max.   :1   Max.   :0.999   Max.   :1     Max.   :0.914  
##                                                                       
##  AccuracyPValue       McnemarPValue  Sensitivity  Specificity Pos Pred Value
##  Min.   :1.393e-150   Min.   : NA   Min.   :1    Min.   :1    Min.   :1     
##  1st Qu.:1.393e-150   1st Qu.: NA   1st Qu.:1    1st Qu.:1    1st Qu.:1     
##  Median :1.393e-150   Median : NA   Median :1    Median :1    Median :1     
##  Mean   :1.393e-150   Mean   :NaN   Mean   :1    Mean   :1    Mean   :1     
##  3rd Qu.:1.393e-150   3rd Qu.: NA   3rd Qu.:1    3rd Qu.:1    3rd Qu.:1     
##  Max.   :1.393e-150   Max.   : NA   Max.   :1    Max.   :1    Max.   :1     
##                       NA's   :300                                           
##  Neg Pred Value   Precision     Recall        F1      Prevalence   
##  Min.   :1      Min.   :1   Min.   :1   Min.   :1   Min.   :0.914  
##  1st Qu.:1      1st Qu.:1   1st Qu.:1   1st Qu.:1   1st Qu.:0.914  
##  Median :1      Median :1   Median :1   Median :1   Median :0.914  
##  Mean   :1      Mean   :1   Mean   :1   Mean   :1   Mean   :0.914  
##  3rd Qu.:1      3rd Qu.:1   3rd Qu.:1   3rd Qu.:1   3rd Qu.:0.914  
##  Max.   :1      Max.   :1   Max.   :1   Max.   :1   Max.   :0.914  
##                                                                    
##  Detection Rate  Detection Prevalence Balanced Accuracy
##  Min.   :0.914   Min.   :0.914        Min.   :1        
##  1st Qu.:0.914   1st Qu.:0.914        1st Qu.:1        
##  Median :0.914   Median :0.914        Median :1        
##  Mean   :0.914   Mean   :0.914        Mean   :1        
##  3rd Qu.:0.914   3rd Qu.:0.914        3rd Qu.:1        
##  Max.   :0.914   Max.   :0.914        Max.   :1        
## </code></pre>
<p>We do not have evidence to support statistical differences between the classification performances estimated for <em>‘Gamma2P’</em> and <em>‘Gamma3P’</em> probability distribution models. Hence, in this case we select the model that yield the lowest cutpoint</p>
</div>
<div id="classification-performance-for-dmps-based-on-fishers-exact-test" class="section level3">
<h3 class="hasAnchor">
<a href="#classification-performance-for-dmps-based-on-fishers-exact-test" class="anchor"></a>Classification performance for DMPs based on Fisher’s exact test</h3>
<p>Classification performance results obtained with Monte Carlos sampling for the <span class="math inline">\(Gamma2P\)</span> and <span class="math inline">\(Gamma3P\)</span> models are quite different from those obtained with FT:</p>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb45-1" data-line-number="1">ft.class =<span class="st"> </span><span class="kw"><a href="../reference/evaluateDIMPclass.html">evaluateDIMPclass</a></span>(<span class="dt">LR =</span> ft.dmps, <span class="dt">control.names =</span> control.nam,</a>
<a class="sourceLine" id="cb45-2" data-line-number="2">                           <span class="dt">treatment.names =</span> treatment.nam, </a>
<a class="sourceLine" id="cb45-3" data-line-number="3">                           <span class="dt">column =</span> <span class="kw"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="dt">hdiv =</span> <span class="ot">TRUE</span>, <span class="dt">TV =</span> <span class="ot">TRUE</span>, </a>
<a class="sourceLine" id="cb45-4" data-line-number="4">                                      <span class="dt">wprob =</span> <span class="ot">TRUE</span>, <span class="dt">pos =</span> <span class="ot">TRUE</span>),</a>
<a class="sourceLine" id="cb45-5" data-line-number="5">                           <span class="dt">classifier =</span> <span class="st">"pca.lda"</span>, <span class="dt">n.pc =</span> <span class="dv">4</span>, </a>
<a class="sourceLine" id="cb45-6" data-line-number="6">                           <span class="dt">center =</span> <span class="ot">TRUE</span>, <span class="dt">scale =</span> <span class="ot">TRUE</span>, <span class="dt">num.boot =</span> <span class="dv">300</span>,</a>
<a class="sourceLine" id="cb45-7" data-line-number="7">                           <span class="dt">output =</span> <span class="st">"all"</span>, <span class="dt">prop =</span> <span class="fl">0.6</span></a>
<a class="sourceLine" id="cb45-8" data-line-number="8">)</a>
<a class="sourceLine" id="cb45-9" data-line-number="9">ft.class<span class="op">$</span>mc.val</a></code></pre></div>
<pre><code>##     Accuracy          Kappa           AccuracyLower    AccuracyUpper   
##  Min.   :0.8076   Min.   :-0.007635   Min.   :0.8001   Min.   :0.8148  
##  1st Qu.:0.8105   1st Qu.: 0.005355   1st Qu.:0.8031   1st Qu.:0.8177  
##  Median :0.8110   Median : 0.007678   Median :0.8036   Median :0.8182  
##  Mean   :0.8110   Mean   : 0.007553   Mean   :0.8036   Mean   :0.8182  
##  3rd Qu.:0.8115   3rd Qu.: 0.009748   3rd Qu.:0.8041   3rd Qu.:0.8187  
##  Max.   :0.8137   Max.   : 0.020669   Max.   :0.8064   Max.   :0.8209  
##   AccuracyNull    AccuracyPValue   McnemarPValue  Sensitivity    
##  Min.   :0.8188   Min.   :0.9205   Min.   :0     Min.   :0.9835  
##  1st Qu.:0.8188   1st Qu.:0.9781   1st Qu.:0     1st Qu.:0.9857  
##  Median :0.8188   Median :0.9847   Median :0     Median :0.9863  
##  Mean   :0.8188   Mean   :0.9827   Mean   :0     Mean   :0.9863  
##  3rd Qu.:0.8188   3rd Qu.:0.9888   3rd Qu.:0     3rd Qu.:0.9868  
##  Max.   :0.8188   Max.   :0.9990   Max.   :0     Max.   :0.9893  
##   Specificity      Pos Pred Value   Neg Pred Value     Precision     
##  Min.   :0.01134   Min.   :0.8181   Min.   :0.1337   Min.   :0.8181  
##  1st Qu.:0.01726   1st Qu.:0.8193   1st Qu.:0.2150   1st Qu.:0.8193  
##  Median :0.01874   Median :0.8196   Median :0.2318   Median :0.8196  
##  Mean   :0.01858   Mean   :0.8196   Mean   :0.2304   Mean   :0.8196  
##  3rd Qu.:0.02022   3rd Qu.:0.8198   3rd Qu.:0.2455   3rd Qu.:0.8198  
##  Max.   :0.02663   Max.   :0.8208   Max.   :0.3187   Max.   :0.8208  
##      Recall             F1           Prevalence     Detection Rate  
##  Min.   :0.9835   Min.   :0.8933   Min.   :0.8188   Min.   :0.8053  
##  1st Qu.:0.9857   1st Qu.:0.8950   1st Qu.:0.8188   1st Qu.:0.8071  
##  Median :0.9863   Median :0.8952   Median :0.8188   Median :0.8076  
##  Mean   :0.9863   Mean   :0.8952   Mean   :0.8188   Mean   :0.8076  
##  3rd Qu.:0.9868   3rd Qu.:0.8955   3rd Qu.:0.8188   3rd Qu.:0.8080  
##  Max.   :0.9893   Max.   :0.8969   Max.   :0.8188   Max.   :0.8101  
##  Detection Prevalence Balanced Accuracy
##  Min.   :0.9825       Min.   :0.4975   
##  1st Qu.:0.9848       1st Qu.:0.5017   
##  Median :0.9853       Median :0.5025   
##  Mean   :0.9854       Mean   :0.5024   
##  3rd Qu.:0.9860       3rd Qu.:0.5031   
##  Max.   :0.9879       Max.   :0.5066</code></pre>
<p>A quite different story is found when information on the probability distribution of noise (null hypothesis) is added to the classifier:</p>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb47-1" data-line-number="1">ft.g2p.dmps &lt;-<span class="st"> </span><span class="kw"><a href="../reference/getPotentialDIMP.html">getPotentialDIMP</a></span>(<span class="dt">LR =</span> ft., <span class="dt">nlms =</span> nlms.g2p,  <span class="dt">div.col =</span> 9L, </a>
<a class="sourceLine" id="cb47-2" data-line-number="2">                                <span class="dt">tv.cut =</span> <span class="fl">0.68</span>, <span class="dt">tv.col =</span> <span class="dv">7</span>, <span class="dt">alpha =</span> <span class="fl">0.05</span>, </a>
<a class="sourceLine" id="cb47-3" data-line-number="3">                                <span class="dt">dist.name =</span> <span class="st">"Gamma2P"</span>)</a>
<a class="sourceLine" id="cb47-4" data-line-number="4"></a>
<a class="sourceLine" id="cb47-5" data-line-number="5">ft.g2p.class =<span class="st"> </span><span class="kw"><a href="../reference/evaluateDIMPclass.html">evaluateDIMPclass</a></span>(<span class="dt">LR =</span> ft.g2p.dmps, <span class="dt">control.names =</span> control.nam,</a>
<a class="sourceLine" id="cb47-6" data-line-number="6">                                 <span class="dt">treatment.names =</span> treatment.nam,</a>
<a class="sourceLine" id="cb47-7" data-line-number="7">                                 <span class="dt">column =</span> <span class="kw"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="dt">hdiv =</span> <span class="ot">TRUE</span>, <span class="dt">TV =</span> <span class="ot">TRUE</span>, </a>
<a class="sourceLine" id="cb47-8" data-line-number="8">                                            <span class="dt">wprob =</span> <span class="ot">TRUE</span>, <span class="dt">pos =</span> <span class="ot">TRUE</span>),</a>
<a class="sourceLine" id="cb47-9" data-line-number="9">                                 <span class="dt">classifier =</span> <span class="st">"pca.lda"</span>, <span class="dt">n.pc =</span> <span class="dv">4</span>, </a>
<a class="sourceLine" id="cb47-10" data-line-number="10">                                 <span class="dt">center =</span> <span class="ot">TRUE</span>, <span class="dt">scale =</span> <span class="ot">TRUE</span>, <span class="dt">num.boot =</span> <span class="dv">300</span>,</a>
<a class="sourceLine" id="cb47-11" data-line-number="11">                                 <span class="dt">output =</span> <span class="st">"all"</span>, <span class="dt">prop =</span> <span class="fl">0.6</span></a>
<a class="sourceLine" id="cb47-12" data-line-number="12">)</a>
<a class="sourceLine" id="cb47-13" data-line-number="13">ft.g2p.class<span class="op">$</span>mc.val</a></code></pre></div>
<pre><code>##     Accuracy     Kappa   AccuracyLower    AccuracyUpper  AccuracyNull   
##  Min.   :1   Min.   :1   Min.   :0.9992   Min.   :1     Min.   :0.7375  
##  1st Qu.:1   1st Qu.:1   1st Qu.:0.9992   1st Qu.:1     1st Qu.:0.7375  
##  Median :1   Median :1   Median :0.9992   Median :1     Median :0.7375  
##  Mean   :1   Mean   :1   Mean   :0.9992   Mean   :1     Mean   :0.7375  
##  3rd Qu.:1   3rd Qu.:1   3rd Qu.:0.9992   3rd Qu.:1     3rd Qu.:0.7375  
##  Max.   :1   Max.   :1   Max.   :0.9992   Max.   :1     Max.   :0.7375  
##                                                                         
##  AccuracyPValue McnemarPValue  Sensitivity  Specificity Pos Pred Value
##  Min.   :0      Min.   : NA   Min.   :1    Min.   :1    Min.   :1     
##  1st Qu.:0      1st Qu.: NA   1st Qu.:1    1st Qu.:1    1st Qu.:1     
##  Median :0      Median : NA   Median :1    Median :1    Median :1     
##  Mean   :0      Mean   :NaN   Mean   :1    Mean   :1    Mean   :1     
##  3rd Qu.:0      3rd Qu.: NA   3rd Qu.:1    3rd Qu.:1    3rd Qu.:1     
##  Max.   :0      Max.   : NA   Max.   :1    Max.   :1    Max.   :1     
##                 NA's   :300                                           
##  Neg Pred Value   Precision     Recall        F1      Prevalence    
##  Min.   :1      Min.   :1   Min.   :1   Min.   :1   Min.   :0.7375  
##  1st Qu.:1      1st Qu.:1   1st Qu.:1   1st Qu.:1   1st Qu.:0.7375  
##  Median :1      Median :1   Median :1   Median :1   Median :0.7375  
##  Mean   :1      Mean   :1   Mean   :1   Mean   :1   Mean   :0.7375  
##  3rd Qu.:1      3rd Qu.:1   3rd Qu.:1   3rd Qu.:1   3rd Qu.:0.7375  
##  Max.   :1      Max.   :1   Max.   :1   Max.   :1   Max.   :0.7375  
##                                                                     
##  Detection Rate   Detection Prevalence Balanced Accuracy
##  Min.   :0.7375   Min.   :0.7375       Min.   :1        
##  1st Qu.:0.7375   1st Qu.:0.7375       1st Qu.:1        
##  Median :0.7375   Median :0.7375       Median :1        
##  Mean   :0.7375   Mean   :0.7375       Mean   :1        
##  3rd Qu.:0.7375   3rd Qu.:0.7375       3rd Qu.:1        
##  Max.   :0.7375   Max.   :0.7375       Max.   :1        
## </code></pre>
<p>Now, we add additional information about the optimal cutpoint</p>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb49-1" data-line-number="1">ft.g2p_cutp.dmps &lt;-<span class="st"> </span><span class="kw"><a href="../reference/selectDIMP.html">selectDIMP</a></span>(ft.g2p.dmps, <span class="dt">div.col =</span> 9L, <span class="dt">cutpoint =</span> cut.g2p<span class="op">$</span>cutpoint)</a>
<a class="sourceLine" id="cb49-2" data-line-number="2"></a>
<a class="sourceLine" id="cb49-3" data-line-number="3">ft.g2p_cut.class =<span class="st"> </span><span class="kw"><a href="../reference/evaluateDIMPclass.html">evaluateDIMPclass</a></span>(<span class="dt">LR =</span> ft.g2p_cutp.dmps, <span class="dt">control.names =</span> control.nam,</a>
<a class="sourceLine" id="cb49-4" data-line-number="4">                                 <span class="dt">treatment.names =</span> treatment.nam,</a>
<a class="sourceLine" id="cb49-5" data-line-number="5">                                 <span class="dt">column =</span> <span class="kw"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="dt">hdiv =</span> <span class="ot">TRUE</span>, <span class="dt">TV =</span> <span class="ot">TRUE</span>, </a>
<a class="sourceLine" id="cb49-6" data-line-number="6">                                            <span class="dt">wprob =</span> <span class="ot">TRUE</span>, <span class="dt">pos =</span> <span class="ot">TRUE</span>),</a>
<a class="sourceLine" id="cb49-7" data-line-number="7">                                 <span class="dt">classifier =</span> <span class="st">"pca.lda"</span>, <span class="dt">n.pc =</span> <span class="dv">4</span>, </a>
<a class="sourceLine" id="cb49-8" data-line-number="8">                                 <span class="dt">center =</span> <span class="ot">TRUE</span>, <span class="dt">scale =</span> <span class="ot">TRUE</span>, <span class="dt">num.boot =</span> <span class="dv">300</span>,</a>
<a class="sourceLine" id="cb49-9" data-line-number="9">                                 <span class="dt">output =</span> <span class="st">"all"</span>, <span class="dt">prop =</span> <span class="fl">0.6</span></a>
<a class="sourceLine" id="cb49-10" data-line-number="10">)</a>
<a class="sourceLine" id="cb49-11" data-line-number="11">ft.g2p_cut.class<span class="op">$</span>mc.val</a></code></pre></div>
<pre><code>##     Accuracy     Kappa   AccuracyLower    AccuracyUpper  AccuracyNull   
##  Min.   :1   Min.   :1   Min.   :0.9991   Min.   :1     Min.   :0.9139  
##  1st Qu.:1   1st Qu.:1   1st Qu.:0.9991   1st Qu.:1     1st Qu.:0.9139  
##  Median :1   Median :1   Median :0.9991   Median :1     Median :0.9139  
##  Mean   :1   Mean   :1   Mean   :0.9991   Mean   :1     Mean   :0.9139  
##  3rd Qu.:1   3rd Qu.:1   3rd Qu.:0.9991   3rd Qu.:1     3rd Qu.:0.9139  
##  Max.   :1   Max.   :1   Max.   :0.9991   Max.   :1     Max.   :0.9139  
##                                                                         
##  AccuracyPValue       McnemarPValue  Sensitivity  Specificity Pos Pred Value
##  Min.   :9.096e-154   Min.   : NA   Min.   :1    Min.   :1    Min.   :1     
##  1st Qu.:9.096e-154   1st Qu.: NA   1st Qu.:1    1st Qu.:1    1st Qu.:1     
##  Median :9.096e-154   Median : NA   Median :1    Median :1    Median :1     
##  Mean   :9.096e-154   Mean   :NaN   Mean   :1    Mean   :1    Mean   :1     
##  3rd Qu.:9.096e-154   3rd Qu.: NA   3rd Qu.:1    3rd Qu.:1    3rd Qu.:1     
##  Max.   :9.096e-154   Max.   : NA   Max.   :1    Max.   :1    Max.   :1     
##                       NA's   :300                                           
##  Neg Pred Value   Precision     Recall        F1      Prevalence    
##  Min.   :1      Min.   :1   Min.   :1   Min.   :1   Min.   :0.9139  
##  1st Qu.:1      1st Qu.:1   1st Qu.:1   1st Qu.:1   1st Qu.:0.9139  
##  Median :1      Median :1   Median :1   Median :1   Median :0.9139  
##  Mean   :1      Mean   :1   Mean   :1   Mean   :1   Mean   :0.9139  
##  3rd Qu.:1      3rd Qu.:1   3rd Qu.:1   3rd Qu.:1   3rd Qu.:0.9139  
##  Max.   :1      Max.   :1   Max.   :1   Max.   :1   Max.   :0.9139  
##                                                                     
##  Detection Rate   Detection Prevalence Balanced Accuracy
##  Min.   :0.9139   Min.   :0.9139       Min.   :1        
##  1st Qu.:0.9139   1st Qu.:0.9139       1st Qu.:1        
##  Median :0.9139   Median :0.9139       Median :1        
##  Mean   :0.9139   Mean   :0.9139       Mean   :1        
##  3rd Qu.:0.9139   3rd Qu.:0.9139       3rd Qu.:1        
##  Max.   :0.9139   Max.   :0.9139       Max.   :1        
## </code></pre>
<p>In other words, information on the probability distributions of the natural spontaneous methylation variation in the control and treatment population are essential to discriminate the background noise from the treatment induced signal.</p>
</div>
</div>
<div id="graphics-of-dmp-classification-performance" class="section level2">
<h2 class="hasAnchor">
<a href="#graphics-of-dmp-classification-performance" class="anchor"></a>Graphics of DMP classification performance</h2>
<p>DMP count data:</p>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb51-1" data-line-number="1">dt &lt;-<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/t.html">t</a></span>(<span class="kw"><a href="https://rdrr.io/r/base/cbind.html">rbind</a></span>(<span class="dt">G2P =</span> <span class="kw"><a href="https://rdrr.io/r/base/lapply.html">sapply</a></span>(g2p.dmps, length),</a>
<a class="sourceLine" id="cb51-2" data-line-number="2">              <span class="dt">G3P =</span> <span class="kw"><a href="https://rdrr.io/r/base/lapply.html">sapply</a></span>(g3p.dmps, length),</a>
<a class="sourceLine" id="cb51-3" data-line-number="3">              <span class="dt">FT =</span> <span class="kw"><a href="https://rdrr.io/r/base/lapply.html">sapply</a></span>(ft.dmps, length),</a>
<a class="sourceLine" id="cb51-4" data-line-number="4">              <span class="dt">FT.G2P =</span> <span class="kw"><a href="https://rdrr.io/r/base/lapply.html">sapply</a></span>(ft.g2p.dmps, length),</a>
<a class="sourceLine" id="cb51-5" data-line-number="5">              <span class="dt">FT.SD =</span> <span class="kw"><a href="https://rdrr.io/r/base/lapply.html">sapply</a></span>(ft.g2p_cutp.dmps, length)</a>
<a class="sourceLine" id="cb51-6" data-line-number="6">    ))</a>
<a class="sourceLine" id="cb51-7" data-line-number="7">dt</a></code></pre></div>
<pre><code>##     G2P  G3P   FT FT.G2P FT.SD
## C1  255  251 1730   1055   255
## C2  306  298 1682   1070   306
## C3  281  276 1657   1059   281
## T1 2925 2871 7589   2926  2925
## T2 3032 2965 7646   3032  3032
## T3 2990 2934 7679   2990  2990</code></pre>
<p>The comparison between the approaches FT.G2P and FT.SD (full signal detection on FT output) tells us that only 255, 306, and 281 cytosine sites detected with FT in the control samples C1, C2, and C3, respectively, carry methylation signals comparable (in magnitude) to those signals induced by the treatment.</p>
<p>Classification performance data:</p>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb53-1" data-line-number="1">df &lt;-<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span>(<span class="dt">method =</span> <span class="kw"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="st">"FT"</span>, <span class="st">"FT.G2P"</span>, <span class="st">"FT.SD"</span>, <span class="st">"G2P"</span>, <span class="st">"G3P"</span>), </a>
<a class="sourceLine" id="cb53-2" data-line-number="2">                 <span class="kw"><a href="https://rdrr.io/r/base/cbind.html">rbind</a></span>(</a>
<a class="sourceLine" id="cb53-3" data-line-number="3">                       <span class="kw"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="kw"><a href="https://rdrr.io/r/base/colSums.html">colMeans</a></span>(ft.class<span class="op">$</span>boots)[<span class="kw"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="dv">1</span>, <span class="dv">8</span><span class="op">:</span><span class="dv">11</span>, <span class="dv">18</span>)], <span class="dt">FDR =</span> ft.class<span class="op">$</span>con.mat<span class="op">$</span>FDR),</a>
<a class="sourceLine" id="cb53-4" data-line-number="4">                       <span class="kw"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="kw"><a href="https://rdrr.io/r/base/colSums.html">colMeans</a></span>(ft.g2p.class<span class="op">$</span>boots)[<span class="kw"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="dv">1</span>, <span class="dv">8</span><span class="op">:</span><span class="dv">11</span>, <span class="dv">18</span>)], <span class="dt">FDR =</span> ft.g2p.class<span class="op">$</span>con.mat<span class="op">$</span>FDR),</a>
<a class="sourceLine" id="cb53-5" data-line-number="5">                       <span class="kw"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="kw"><a href="https://rdrr.io/r/base/colSums.html">colMeans</a></span>(ft.g2p_cut.class<span class="op">$</span>boots)[<span class="kw"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="dv">1</span>, <span class="dv">8</span><span class="op">:</span><span class="dv">11</span>, <span class="dv">18</span>)], <span class="dt">FDR =</span> ft.g2p_cut.class<span class="op">$</span>con.mat<span class="op">$</span>FDR),</a>
<a class="sourceLine" id="cb53-6" data-line-number="6">                       <span class="kw"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="kw"><a href="https://rdrr.io/r/base/colSums.html">colMeans</a></span>(g2p.class<span class="op">$</span>boots)[<span class="kw"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="dv">1</span>, <span class="dv">8</span><span class="op">:</span><span class="dv">11</span>, <span class="dv">18</span>)], <span class="dt">FDR =</span> g2p.class<span class="op">$</span>con.mat<span class="op">$</span>FDR),</a>
<a class="sourceLine" id="cb53-7" data-line-number="7">                       <span class="kw"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="kw"><a href="https://rdrr.io/r/base/colSums.html">colMeans</a></span>(g3p.class<span class="op">$</span>boots)[<span class="kw"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="dv">1</span>, <span class="dv">8</span><span class="op">:</span><span class="dv">11</span>, <span class="dv">18</span>)], <span class="dt">FDR =</span> g3p.class<span class="op">$</span>con.mat<span class="op">$</span>FDR)</a>
<a class="sourceLine" id="cb53-8" data-line-number="8">                 ))</a></code></pre></div>
<p>Graphics:</p>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb54-1" data-line-number="1">color &lt;-<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="st">"darkgreen"</span>, <span class="st">"#147714FF"</span>, <span class="st">"#3D9F3DFF"</span>, <span class="st">"#66C666FF"</span>,  <span class="st">"#90EE90FF"</span>)</a>
<a class="sourceLine" id="cb54-2" data-line-number="2">dt &lt;-<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span>(dt, <span class="dt">sample =</span> <span class="kw"><a href="https://rdrr.io/r/base/names.html">names</a></span>(g2p.dmps))</a>
<a class="sourceLine" id="cb54-3" data-line-number="3"></a>
<a class="sourceLine" id="cb54-4" data-line-number="4"><span class="co">## ------------------------- DMP count graphic ---------------------------------</span></a>
<a class="sourceLine" id="cb54-5" data-line-number="5"><span class="kw"><a href="https://rdrr.io/r/graphics/par.html">par</a></span>(<span class="dt">family =</span> <span class="st">"serif"</span>, <span class="dt">lwd =</span> <span class="fl">0.1</span>, <span class="dt">cex =</span> <span class="dv">1</span>, <span class="dt">mar =</span> <span class="kw"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="dv">2</span>,<span class="dv">5</span>,<span class="dv">2</span>,<span class="dv">2</span>), <span class="dt">mfcol =</span> <span class="kw"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="dv">1</span>, <span class="dv">2</span>))</a>
<a class="sourceLine" id="cb54-6" data-line-number="6"><span class="kw"><a href="https://rdrr.io/r/graphics/barplot.html">barplot</a></span>(<span class="kw"><a href="https://rdrr.io/r/base/cbind.html">cbind</a></span>(FT, FT.G2P, FT.SD, G2P, G3P) <span class="op">~</span><span class="st"> </span>sample, </a>
<a class="sourceLine" id="cb54-7" data-line-number="7">        <span class="dt">panel.first=</span>{<span class="kw"><a href="https://rdrr.io/r/graphics/points.html">points</a></span>(<span class="dv">0</span>, <span class="dv">0</span>, <span class="dt">pch=</span><span class="dv">16</span>, <span class="dt">cex=</span><span class="fl">1e6</span>, <span class="dt">col=</span><span class="st">"grey95"</span>)</a>
<a class="sourceLine" id="cb54-8" data-line-number="8">          <span class="kw"><a href="https://rdrr.io/r/graphics/grid.html">grid</a></span>(<span class="dt">col=</span><span class="st">"white"</span>, <span class="dt">lty =</span> <span class="dv">1</span>, <span class="dt">lwd =</span> <span class="dv">1</span>)},</a>
<a class="sourceLine" id="cb54-9" data-line-number="9">        <span class="dt">data =</span> dt, <span class="dt">beside =</span> <span class="ot">TRUE</span>,  <span class="dt">legend.text =</span> <span class="ot">TRUE</span>, <span class="dt">las =</span> <span class="dv">1</span>, <span class="dt">lwd =</span> <span class="fl">0.05</span>, <span class="dt">yaxt =</span> <span class="st">"n"</span>,</a>
<a class="sourceLine" id="cb54-10" data-line-number="10">        <span class="dt">cex.names =</span> <span class="fl">1.4</span>, <span class="dt">font =</span> <span class="dv">3</span>, <span class="dt">xlab =</span> <span class="st">""</span>, <span class="dt">col =</span> color,</a>
<a class="sourceLine" id="cb54-11" data-line-number="11">        <span class="dt">args.legend =</span> <span class="kw"><a href="https://rdrr.io/r/base/list.html">list</a></span>(<span class="dt">x=</span><span class="dv">10</span>, <span class="dt">y=</span><span class="dv">6000</span>, <span class="dt">text.font =</span> <span class="dv">2</span>, <span class="dt">box.lwd =</span> <span class="dv">0</span>, <span class="dt">horiz =</span> <span class="ot">FALSE</span>,</a>
<a class="sourceLine" id="cb54-12" data-line-number="12">                           <span class="dt">adj =</span> <span class="dv">0</span>, <span class="dt">xjust =</span> <span class="fl">0.65</span>, <span class="dt">yjust =</span> <span class="fl">0.8</span>, <span class="dt">bty =</span> <span class="st">"n"</span>, <span class="dt">cex =</span> <span class="fl">1.2</span>,</a>
<a class="sourceLine" id="cb54-13" data-line-number="13">                           <span class="dt">x.intersp =</span> <span class="fl">0.2</span>, <span class="dt">inset =</span> <span class="dv">-1</span>, <span class="dt">ncol =</span> <span class="dv">1</span>, <span class="dt">fill =</span> color))</a>
<a class="sourceLine" id="cb54-14" data-line-number="14"><span class="kw"><a href="https://rdrr.io/r/graphics/axis.html">axis</a></span>(<span class="dv">2</span>, <span class="dt">hadj =</span> <span class="fl">0.9</span>, <span class="dt">las =</span> <span class="dv">2</span>, <span class="dt">lwd =</span> <span class="fl">0.4</span>, <span class="dt">tck =</span> <span class="fl">-0.02</span>, <span class="dt">cex.axis =</span> <span class="fl">1.2</span>, <span class="dt">font =</span> <span class="dv">2</span>, <span class="dt">line =</span> <span class="fl">-0.2</span>)</a>
<a class="sourceLine" id="cb54-15" data-line-number="15"><span class="kw"><a href="https://rdrr.io/r/graphics/mtext.html">mtext</a></span>(<span class="dt">side =</span> <span class="dv">2</span>, <span class="dt">text =</span> <span class="st">"DMP count"</span>, <span class="dt">line =</span> <span class="dv">3</span>, <span class="dt">cex =</span> <span class="fl">1.4</span>, <span class="dt">font =</span> <span class="dv">3</span>)</a>
<a class="sourceLine" id="cb54-16" data-line-number="16"></a>
<a class="sourceLine" id="cb54-17" data-line-number="17"><span class="co">## ------------------ DMP classifiction performance graphic -------------------</span></a>
<a class="sourceLine" id="cb54-18" data-line-number="18">color &lt;-<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="st">"mediumblue"</span>, <span class="st">"#0000FFFF"</span>, <span class="st">"#3949F6FF"</span>, <span class="st">"#566CF2FF"</span>, <span class="st">"#7390EEFF"</span>, <span class="st">"#90B3EAFF"</span>, <span class="st">"#ADD8E6FF"</span>)</a>
<a class="sourceLine" id="cb54-19" data-line-number="19">labs &lt;-<span class="st"> </span>df<span class="op">$</span>method</a>
<a class="sourceLine" id="cb54-20" data-line-number="20">  </a>
<a class="sourceLine" id="cb54-21" data-line-number="21"><span class="kw"><a href="https://rdrr.io/r/graphics/par.html">par</a></span>(<span class="dt">family =</span> <span class="st">"serif"</span>, <span class="dt">lwd =</span> <span class="fl">0.1</span>, <span class="dt">cex =</span> <span class="dv">1</span>, <span class="dt">mar =</span> <span class="kw"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="dv">4</span>,<span class="dv">2</span>,<span class="dv">2</span>,<span class="dv">10</span>))</a>
<a class="sourceLine" id="cb54-22" data-line-number="22">x &lt;-<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/graphics/barplot.html">barplot</a></span>(<span class="kw"><a href="https://rdrr.io/r/base/cbind.html">cbind</a></span>(Accuracy, Sensitivity, Specificity, Pos.Pred.Value, Neg.Pred.Value, </a>
<a class="sourceLine" id="cb54-23" data-line-number="23">              Balanced.Accuracy, FDR) <span class="op">~</span><span class="st"> </span>method, </a>
<a class="sourceLine" id="cb54-24" data-line-number="24">        <span class="dt">panel.first=</span>{<span class="kw"><a href="https://rdrr.io/r/graphics/points.html">points</a></span>(<span class="dv">0</span>, <span class="dv">0</span>, <span class="dt">pch=</span><span class="dv">16</span>, <span class="dt">cex=</span><span class="fl">1e6</span>, <span class="dt">col=</span><span class="st">"grey95"</span>)</a>
<a class="sourceLine" id="cb54-25" data-line-number="25">          <span class="kw"><a href="https://rdrr.io/r/graphics/grid.html">grid</a></span>(<span class="dt">col=</span><span class="st">"white"</span>, <span class="dt">lty =</span> <span class="dv">1</span>, <span class="dt">lwd =</span> <span class="dv">1</span>)}, </a>
<a class="sourceLine" id="cb54-26" data-line-number="26">        <span class="dt">data =</span> df, <span class="dt">beside =</span> <span class="ot">TRUE</span>,  <span class="dt">legend.text =</span> <span class="ot">TRUE</span>, <span class="dt">las =</span> <span class="dv">1</span>, <span class="dt">lwd =</span> <span class="fl">0.1</span>, <span class="dt">yaxt =</span> <span class="st">"n"</span>,</a>
<a class="sourceLine" id="cb54-27" data-line-number="27">        <span class="dt">cex.names =</span> <span class="fl">1.4</span>, <span class="dt">font =</span> <span class="dv">3</span>, <span class="dt">xlab =</span> <span class="st">""</span>, <span class="dt">col =</span> color, <span class="dt">ylim =</span> <span class="kw"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="dv">0</span>,<span class="dv">1</span>), </a>
<a class="sourceLine" id="cb54-28" data-line-number="28">        <span class="dt">args.legend =</span> <span class="kw"><a href="https://rdrr.io/r/base/list.html">list</a></span>(<span class="dt">x =</span> <span class="dv">52</span>, <span class="dt">y =</span> <span class="fl">1.</span>, <span class="dt">text.font =</span> <span class="dv">2</span>, <span class="dt">box.lwd =</span> <span class="dv">0</span>, <span class="dt">horiz =</span> <span class="ot">FALSE</span>,</a>
<a class="sourceLine" id="cb54-29" data-line-number="29">                           <span class="dt">adj =</span> <span class="dv">0</span>, <span class="dt">xjust =</span> <span class="fl">0.65</span>, <span class="dt">yjust =</span> <span class="fl">0.8</span>, <span class="dt">bty =</span> <span class="st">"n"</span>, <span class="dt">cex =</span> <span class="fl">1.2</span>,</a>
<a class="sourceLine" id="cb54-30" data-line-number="30">                           <span class="dt">x.intersp =</span> <span class="fl">0.2</span>, <span class="dt">inset =</span> <span class="dv">-1</span>, <span class="dt">ncol =</span> <span class="dv">1</span>, <span class="dt">fill =</span> color))</a>
<a class="sourceLine" id="cb54-31" data-line-number="31"><span class="kw"><a href="https://rdrr.io/r/graphics/axis.html">axis</a></span>(<span class="dv">2</span>, <span class="dt">hadj =</span> <span class="fl">0.8</span>, <span class="dt">las =</span> <span class="dv">2</span>, <span class="dt">lwd =</span> <span class="fl">0.4</span>, <span class="dt">tck =</span> <span class="fl">-0.02</span>, <span class="dt">cex.axis =</span> <span class="fl">1.2</span>, <span class="dt">font =</span> <span class="dv">2</span>,</a>
<a class="sourceLine" id="cb54-32" data-line-number="32">     <span class="dt">line =</span> <span class="fl">-0.4</span>)</a>
<a class="sourceLine" id="cb54-33" data-line-number="33"><span class="kw"><a href="https://rdrr.io/r/graphics/mtext.html">mtext</a></span>(<span class="dt">side =</span> <span class="dv">2</span>, <span class="dt">text =</span> <span class="st">"Performance value"</span>, <span class="dt">line =</span> <span class="dv">2</span>, <span class="dt">cex =</span> <span class="fl">1.4</span>, <span class="dt">font =</span> <span class="dv">3</span>)</a></code></pre></div>
<p><img src="Cutpoint_estimation_with_Methyl-IT_files/figure-html/dmp_graph-1.png" width="1344"></p>
<p>FT.G2P and FT.SD approaches lead to excellent classification performances on this data set. At this point, we can appeal the parsimony principle, follows from <a href="https://www.britannica.com/topic/Occams-razor">Occam’s razor</a> that states “among competing hypotheses, the hypothesis with the fewest assumptions should be selected. In other words, results indicates that the signal-detection and machine-learning approach is sufficient <span class="citation">(El Naqa et al. 2018; Sanchez et al. 2019)</span>.</p>
</div>
<div id="conclusions" class="section level1">
<h1 class="hasAnchor">
<a href="#conclusions" class="anchor"></a>Conclusions</h1>
<ol style="list-style-type: decimal">
<li><p>A proper discrimination of the methylation signal from the stochastic methylation background requires for the knowledge of probability distributions of the methylation signal from control and treatment population. Such a knowledge permits a suitable estimation of the cutoff value to discriminate the methylation signal induced by the treatment from the stochastic methylation background detected in the control group.</p></li>
<li><p>It does not matter how significant a differentially methylation event for a given cytosine position would be (after the application of some statistical test), but on how big the probability to be observed in the control group is. In simple words, if for a given DMP the probability of to be observed in the control is <em>big enough</em>, then such a DMP did not result from a treatment effect.</p></li>
<li><p>A suitable evaluation on how much the mentioned probability can be <em>big enough</em> derives by estimating an optimal cutpoint. But a classification into two groups results from the cutpoint estimation and the problem on the estimation of such a cutpoint is equivalent to find a discriminatory function (as set by Fisher, <span class="citation">(Fisher 1938; Green 1979)</span>). Cases with function values below some cutoff are classified in one group, while values above the cutoff are put in the other group.</p></li>
<li><p>MethylIT function <a href="https://genomaths.github.io/MethylIT_HTML_Manual/estimateCutPoint.html">estimateCutPoint</a> permits the estimation and search for an optimal cutpoint by confronting the problem as in the spirit of the classical signal detection and as a classification problem. The best model classifier will depend on the dataset under study.So, uses must check for which is the model classifier with the best classification performance for his/her dataset.</p></li>
</ol>
</div>
<div id="references" class="section level1 unnumbered">
<h1 class="hasAnchor">
<a href="#references" class="anchor"></a>References</h1>
<div id="refs" class="references">
<div id="ref-Eldar2010">
<p>Eldar, Avigdor, and Michael B. Elowitz. 2010. “Functional roles for noise in genetic circuits.” Nature Publishing Group. <a href="https://doi.org/10.1038/nature09326">https://doi.org/10.1038/nature09326</a>.</p>
</div>
<div id="ref-ElNaqa2018">
<p>El Naqa, Issam, Dan Ruan, Gilmer Valdes, Andre Dekker, Todd McNutt, Yaorong Ge, Q. Jackie Wu, et al. 2018. “Machine learning and modeling: Data, validation, communication challenges.” <em>Medical Physics</em> 45 (10): e834–e840. <a href="https://doi.org/10.1002/mp.12811">https://doi.org/10.1002/mp.12811</a>.</p>
</div>
<div id="ref-Fisher1938">
<p>Fisher, R.A. 1938. “The statistical utilization of multiple measurents.” <em>Annals of Eugenics</em> 8: 376–86.</p>
</div>
<div id="ref-Green1979">
<p>Green, Bert F. 1979. “The Two Kinds of Linear Discriminant Functions and Their Relationship.” <em>Journal of Educational Statistics</em> 4 (3): 247–63.</p>
</div>
<div id="ref-Koslover2012">
<p>Koslover, Elena F, and Andrew J Spakowitz. 2012. “Force fluctuations impact kinetics of biomolecular systems.” <em>Physical Review. E, Statistical, Nonlinear, and Soft Matter Physics</em> 86 (1 Pt 1): 011906. <a href="http://www.ncbi.nlm.nih.gov/pubmed/23005451">http://www.ncbi.nlm.nih.gov/pubmed/23005451</a>.</p>
</div>
<div id="ref-Min2005">
<p>Min, Wei, Liang Jiang, Ji Yu, S C Kou, Hong Qian, and X Sunney Xie. 2005. “Nonequilibrium steady state of a nanometric biochemical system: Determining the thermodynamic driving force from single enzyme turnover time traces.” <em>Nano Letters</em> 5 (12): 2373–8. <a href="https://doi.org/10.1021/nl0521773">https://doi.org/10.1021/nl0521773</a>.</p>
</div>
<div id="ref-Ngo2016">
<p>Ngo, Thuy T.M., Jejoong Yoo, Qing Dai, Qiucen Zhang, Chuan He, Aleksei Aksimentiev, and Taekjip Ha. 2016. “Effects of cytosine modifications on DNA flexibility and nucleosome mechanical stability.” <em>Nature Communications</em> 7 (February). Nature Publishing Group: 10813. <a href="https://doi.org/10.1038/ncomms10813">https://doi.org/10.1038/ncomms10813</a>.</p>
</div>
<div id="ref-Samoilov2006">
<p>Samoilov, Michael S., Gavin Price, and Adam P. Arkin. 2006. “From fluctuations to phenotypes: the physiology of noise.” <em>Science’s STKE : Signal Transduction Knowledge Environment</em> 2006 (366). <a href="https://doi.org/10.1126/stke.3662006re17">https://doi.org/10.1126/stke.3662006re17</a>.</p>
</div>
<div id="ref-Sanchez2016">
<p>Sanchez, Robersy, and Sally A. Mackenzie. 2016. “Information Thermodynamics of Cytosine DNA Methylation.” Edited by Barbara Bardoni. <em>PLOS ONE</em> 11 (3). Public Library of Science: e0150427. <a href="https://doi.org/10.1371/journal.pone.0150427">https://doi.org/10.1371/journal.pone.0150427</a>.</p>
</div>
<div id="ref-Sanchez2019">
<p>Sanchez, Robersy, Xiaodong Yang, Thomas Maher, and Sally Mackenzie. 2019. “Discrimination of DNA Methylation Signal from Background Variation for Clinical Diagnostics.” <em>Int. J. Mol. Sci.</em> 20 (21): 5343. <a href="https://doi.org/https://doi.org/10.3390/ijms20215343">https://doi.org/https://doi.org/10.3390/ijms20215343</a>.</p>
</div>
<div id="ref-Youden1950">
<p>Youden, W. J. 1950. “Index for rating diagnostic tests.” <em>Cancer</em> 3 (1): 32–35. <a href="https://doi.org/10.1002/1097-0142(1950)3:1&lt;32::AID-CNCR2820030106&gt;3.0.CO;2-3">https://doi.org/10.1002/1097-0142(1950)3:1&lt;32::AID-CNCR2820030106&gt;3.0.CO;2-3</a>.</p>
</div>
</div>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="pkgdown-sidebar">

        <div id="tocnav">
      <h2 class="hasAnchor">
<a href="#tocnav" class="anchor"></a>Contents</h2>
      <ul class="nav nav-pills nav-stacked">
<li><a href="#motivation">Motivation</a></li>
      <li><a href="#data-generation">Data generation</a></li>
      <li><a href="#methylation-level-divergences">Methylation level divergences</a></li>
      <li><a href="#estimation-of-potential-dmps-with-methyl-it">Estimation of potential DMPs with Methyl-IT</a></li>
      <li><a href="#cutpoint-estimation">Cutpoint estimation</a></li>
      <li><a href="#machine-learning-ml-based-approach-to-search-for-an-optimal-cutpoint">Machine-learning (ML) based approach to search for an optimal cutpoint</a></li>
      <li><a href="#dmps-estimated-with-fishers-exact-test-ft">DMPs estimated with Fisher’s exact Test (FT)</a></li>
      <li><a href="#classification-performance-of-dmp-classification">Classification performance of DMP classification</a></li>
      <li><a href="#graphics-of-dmp-classification-performance">Graphics of DMP classification performance</a></li>
      <li><a href="#conclusions">Conclusions</a></li>
      <li><a href="#references">References</a></li>
      </ul>
</div>
      </div>

</div>



      <footer><div class="copyright">
  <p>Developed by Robersy Sanchez.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="https://pkgdown.r-lib.org/">pkgdown</a> 1.4.1.9000.</p>
</div>

      </footer>
</div>

  


  </body>
</html>
