<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Principal Components and Linear Discriminant Analyses with Methyl-IT • MethylIT</title>
<!-- favicons --><link rel="icon" type="image/png" sizes="16x16" href="../favicon-16x16.png">
<link rel="icon" type="image/png" sizes="32x32" href="../favicon-32x32.png">
<link rel="apple-touch-icon" type="image/png" sizes="180x180" href="../apple-touch-icon.png">
<link rel="apple-touch-icon" type="image/png" sizes="120x120" href="../apple-touch-icon-120x120.png">
<link rel="apple-touch-icon" type="image/png" sizes="76x76" href="../apple-touch-icon-76x76.png">
<link rel="apple-touch-icon" type="image/png" sizes="60x60" href="../apple-touch-icon-60x60.png">
<!-- jquery --><script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script><!-- Bootstrap --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha256-bZLfwXAP04zRMK2BjiO8iu9pf4FbLqX6zitd+tIvLhE=" crossorigin="anonymous">
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha256-nuL8/2cJ5NDSSwnKD8VqreErSWHtnEP9E7AySL+1ev4=" crossorigin="anonymous"></script><!-- bootstrap-toc --><link rel="stylesheet" href="../bootstrap-toc.css">
<script src="../bootstrap-toc.js"></script><!-- Font Awesome icons --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/v4-shims.min.css" integrity="sha256-wZjR52fzng1pJHwx4aV2AO3yyTOXrcDW7jBpJtTwVxw=" crossorigin="anonymous">
<!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><!-- headroom.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/headroom.min.js" integrity="sha256-AsUX4SJE1+yuDu5+mAVzJbuYNPHj/WroHuZ8Ir/CkE0=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/jQuery.headroom.min.js" integrity="sha256-ZX/yNShbjqsohH1k95liqY9Gd8uOiE1S4vZc+9KQ1K4=" crossorigin="anonymous"></script><!-- pkgdown --><link href="../pkgdown.css" rel="stylesheet">
<script src="../pkgdown.js"></script><meta property="og:title" content="Principal Components and Linear Discriminant Analyses with Methyl-IT">
<meta property="og:description" content="MethylIT">
<meta property="og:image" content="https://genomaths.github.io/methylit/logo.png">
<!-- mathjax --><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" integrity="sha256-nvJJv9wWKEm88qvoQl9ekL2J+k/RWIsaSScxxlsrv8k=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/TeX-AMS-MML_HTMLorMML.js" integrity="sha256-84DKXVJXs0/F8OTMzX4UR909+jtl4G7SPypPavF+GfA=" crossorigin="anonymous"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body data-spy="scroll" data-target="#toc">
    <div class="container template-article">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">MethylIT</a>
        <span class="version label label-default" data-toggle="tooltip" data-placement="bottom" title="Released version">0.3.2</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../index.html">
    <span class="fas fa fas fa-home fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="../articles/MethylIT.html">Get started</a>
</li>
<li>
  <a href="../reference/index.html">Package functions</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Articles
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li>
      <a href="../articles/MethylIT.html">MethylIT</a>
    </li>
    <li class="divider">
    <li>
      <a href="../articles/Methylation_analysis_with_Methyl-IT.html">Methylation analysis with Methyl-IT</a>
    </li>
    <li class="divider">
    <li>
      <a href="../articles/cancer_example.html">Example of Methylome Analysis with MethylIT using Cancer Datasets</a>
    </li>
    <li class="divider">
    <li>
      <a href="../articles/Cutpoint_estimation_with_Methyl-IT.html">Optimal cutpoint for the methylation signal</a>
    </li>
    <li class="divider">
    <li>
      <a href="../articles/pca_lda_with_methylit.html">Principal Components and Linear Discriminant Analyses with Methyl-IT</a>
    </li>
    <li class="divider">
    <li>
      <a href="../articles/GenExp_Methylation_association_hyper_down-regulated.html">Association Between Gene Expression and Cytosine DNA Methylation at gene-body</a>
    </li>
  </ul>
</li>
<li>
  <a href="../news/index.html">News</a>
</li>
<li>
  <a href="https://github.com/genomaths/MethylIT/">
    <span class="fab fa fab fa-github fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="http://twitter.com/robersysr">
    <span class="fab fa fab fa-twitter fa-lg"></span>
     
  </a>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right"></ul>
</div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      

      </header><div class="row">
  <div class="col-md-9 contents">
    <div class="page-header toc-ignore">
      <h1 data-toc-skip>Principal Components and Linear Discriminant Analyses with Methyl-IT</h1>
            <h3 class="subtitle"><h1>
A <a href="https://github.com/genomaths/MethylIT">Methyl-IT</a> user guide</h1></h3>
                        <h4 class="author">
<div class="line-block">Robersy Sanchez<br><a href="mailto:rus547@psu.edu" class="email">rus547@psu.edu</a><br>
Mackenzie’s lab</div>
<div class="line-block">Department of Biology and Plant Science.<br>
Pennsylvania State University, University Park, PA 16802<br>
Maintainer: Robersy Sanchez</div>
</h4>
            
            <h4 class="date">08 April 2020</h4>
      
      <small class="dont-index">Source: <a href="https://github.com/genomaths/MethylIT/blob/master/vignettes/pca_lda_with_methylit.Rmd"><code>vignettes/pca_lda_with_methylit.Rmd</code></a></small>
      <div class="hidden name"><code>pca_lda_with_methylit.Rmd</code></div>

    </div>

    
        <div class="abstract">
      <p class="abstract">Abstract</p>
      When methylation analysis is intended for diagnostic/prognostic purposes, for example, in clinical applications for patient diagnostics, to know whether the patient would be in healthy or disease stage we would like to have a good predictor tool in our side. It turns out that classical machine learning (ML) tools like hierarchical clustering, principal components and linear discriminant analysis can help us to reach such a goal. The current Methyl-IT downstream analysis is equipped with the mentioned ML tools.
    </div>
    
<style type="text/css">

.list-group-item.active, .list-group-item.active:focus, 
.list-group-item.active:hover {
    z-index: 2;
    color: #fff;
    background-color: #337ab7;
    border-color: #337ab7;
}

.tocify-subheader .tocify-item {
  font-size: 0.75em;
  padding-left: 25px;
  text-indent: 0;
}

.tocify-header .tocify-item {
  font-size: 0.8em;
  padding-left: 20px;
  text-indent: 0;
}

body{ /* Normal  */
      font-size: 16px;
      font-family: "Times New Roman", Times, serif;
      text-align: justify
  }
td {  /* Table  */
  font-size: 8px;
}

h1.title {
   font-size: 36px;
   font-family: "Times New Roman", Times, serif;
   color: DarkRed;
   .subTitle {
       font-size: 24px;
       font-family: "Times New Roman", Times, serif;
       color: DarkRed;
  }
}

h1 { /* Header 1 */
  font-size: 24px;
  font-family: "Times New Roman", Times, serif;
  color: DarkBlue;
}
h2 { /* Header 2 */
    font-size: 22px;
    color: DarkBlue;
    font-family: "Times New Roman", Times, serif;
}
h3 { /* Header 3 */
   font-size: 18px;
   color: DarkBlue;
   font-family: "Times New Roman", Times, serif;
}
code.r{ /* Code block */
    font-size: 12px;
}
pre { /* Code block - determines code spacing between lines */
    font-size: 14px;
}
</style>
<div id="background" class="section level1">
<h1 class="hasAnchor">
<a href="#background" class="anchor"></a>Background</h1>
<p>The discrimination of the methylation signal from the stochastic methylation background resultant from the standard (non-stressful) biological processes is a critical step for the genome-wide methylation analysis. Such a discrimination requires for the knowledge of the probability distribution of the information divergence of methylation levels and a proper evaluation of the classification performance of differentially methylated positions (DMPs) into two classes: DMPs from control and DMPs from treatment.</p>
<p>Once a methylation analysis is performed to detect the genome-wide DMPs, a natural next step is to investigate whether the detected DMPs carries enough discriminatory power to discern between individual groups. Then, we must move from the methylation analysis to statistical/machine learning field (multivariate statistics). To reach our goal, each individual can be represented as a vector from the <span class="math inline">\(N\)</span>-dimensional space of DMPs, where DMPs can be expressed in terms of some suitable measurement as function of the methylation levels. These suitable measurement are information divergences, such as total variation distance (<span class="math inline">\(TV_d\)</span>, the absolute value of methylation levels) and Hellinger divergence (<span class="math inline">\(H\)</span>). It is worthy to observe that methylation levels are uncertainty measurements and, therefore, they do not carry information per se. Information is only carried on measurements expressing uncertainty variations like <span class="math inline">\(TV_d\)</span>, <span class="math inline">\(H\)</span>, Jensen-Shannon Divergence, and in general, the so called information theoretical divergences <span class="citation">(Liese and Vajda 2006)</span>.</p>
<p>The <span class="math inline">\(N\)</span>-dimensional space of DMPs is, usually, too big. So, a first dimension reduction is required. This can be done by splitting the chromosomes into non-overlapping genomic region and next computing some statistic like the <em>sum</em> or <em>mean</em> of some information divergences of methylation levels at DMPs inside of each region. Still we will have to deal with a multidimensional space, but acceptable for a meaningful application of hierarchical clustering (HC), principal component analysis (PCA) and linear discriminant analysis (LDA). In the current examples, Methyl-IT methylation analysis will be applied to a dataset of simulated samples to detect DMPs on then. Next, after space dimension reduction, the mentioned machine learning approached will be applied.</p>
</div>
<div id="data-generation" class="section level1">
<h1 class="hasAnchor">
<a href="#data-generation" class="anchor"></a>Data generation</h1>
<p>For the current example on methylation analysis with Methyl-IT we will use simulated data. Read-count matrices of methylated and unmethylated cytosine are generated with MethylIT.utils function <a href="https://genomaths.github.io/MethylIT_utils_HTML_Manual/simulateCounts.html">simulateCounts</a>. A basic example generating datasets is given in the web page: <a href="https://genomaths.github.io/Methylation_analysis_with_Methyl-IT.html">Methylation analysis with Methyl-IT</a></p>
<div class="sourceCode" id="cb1"><html><body><pre class="r"><span class="fu"><a href="https://rdrr.io/r/base/library.html">library</a></span>(<span class="no">MethylIT</span>)
<span class="fu"><a href="https://rdrr.io/r/base/library.html">library</a></span>(<span class="no">MethylIT.utils</span>)
<span class="fu"><a href="https://rdrr.io/r/base/library.html">library</a></span>(<span class="no">ggplot2</span>)
<span class="fu"><a href="https://rdrr.io/r/base/library.html">library</a></span>(<span class="no">ape</span>)

<span class="no">alpha.ct</span> <span class="kw">&lt;-</span> <span class="fl">0.019</span>
<span class="no">alpha.g1</span> <span class="kw">&lt;-</span> <span class="fl">0.022</span>
<span class="no">alpha.g2</span> <span class="kw">&lt;-</span> <span class="fl">0.025</span>

<span class="co"># The number of cytosine sites to generate</span>
<span class="no">sites</span> <span class="kw">=</span> <span class="fl">1.5e5</span>
<span class="co"># Set a seed for pseudo-random number generation</span>
<span class="fu"><a href="https://rdrr.io/r/base/Random.html">set.seed</a></span>(<span class="fl">124</span>)
<span class="no">control.nam</span> <span class="kw">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="st">"C1"</span>, <span class="st">"C2"</span>, <span class="st">"C3"</span>, <span class="st">"C4"</span>, <span class="st">"C5"</span>)
<span class="no">treatment.nam1</span> <span class="kw">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="st">"T1"</span>, <span class="st">"T2"</span>, <span class="st">"T3"</span>, <span class="st">"T4"</span>, <span class="st">"T5"</span>)
<span class="no">treatment.nam2</span> <span class="kw">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="st">"T6"</span>, <span class="st">"T7"</span>, <span class="st">"T8"</span>, <span class="st">"T9"</span>, <span class="st">"T10"</span>)

<span class="co"># Reference group </span>
<span class="no">ref0</span> <span class="kw">=</span> <span class="fu"><a href="https://rdrr.io/pkg/MethylIT.utils/man/simulateCounts.html">simulateCounts</a></span>(<span class="kw">num.samples</span> <span class="kw">=</span> <span class="fl">3</span>, <span class="kw">sites</span> <span class="kw">=</span> <span class="no">sites</span>, <span class="kw">alpha</span> <span class="kw">=</span> <span class="no">alpha.ct</span>,
                      <span class="kw">beta</span> <span class="kw">=</span> <span class="fl">0.5</span>, <span class="kw">size</span> <span class="kw">=</span> <span class="fl">50</span>, <span class="kw">theta</span> <span class="kw">=</span> <span class="fl">4.5</span>,
                      <span class="kw">sample.ids</span> <span class="kw">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="st">"R1"</span>, <span class="st">"R2"</span>, <span class="st">"R3"</span>))
<span class="co"># Control group </span>
<span class="no">ctrl</span> <span class="kw">=</span> <span class="fu"><a href="https://rdrr.io/pkg/MethylIT.utils/man/simulateCounts.html">simulateCounts</a></span>(<span class="kw">num.samples</span> <span class="kw">=</span> <span class="fl">5</span>, <span class="kw">sites</span> <span class="kw">=</span> <span class="no">sites</span>, <span class="kw">alpha</span> <span class="kw">=</span> <span class="no">alpha.ct</span>,
                      <span class="kw">beta</span> <span class="kw">=</span> <span class="fl">0.5</span>, <span class="kw">size</span> <span class="kw">=</span> <span class="fl">50</span>, <span class="kw">theta</span> <span class="kw">=</span> <span class="fl">4.5</span>,
                      <span class="kw">sample.ids</span> <span class="kw">=</span> <span class="no">control.nam</span>)
<span class="co"># Treatment group II</span>
<span class="no">treat</span> <span class="kw">=</span> <span class="fu"><a href="https://rdrr.io/pkg/MethylIT.utils/man/simulateCounts.html">simulateCounts</a></span>(<span class="kw">num.samples</span> <span class="kw">=</span> <span class="fl">5</span>, <span class="kw">sites</span> <span class="kw">=</span> <span class="no">sites</span>, <span class="kw">alpha</span> <span class="kw">=</span> <span class="no">alpha.g1</span>,
                       <span class="kw">beta</span> <span class="kw">=</span> <span class="fl">0.5</span>, <span class="kw">size</span> <span class="kw">=</span> <span class="fl">50</span>, <span class="kw">theta</span> <span class="kw">=</span> <span class="fl">4.5</span>,
                       <span class="kw">sample.ids</span> <span class="kw">=</span> <span class="no">treatment.nam1</span>)

<span class="co"># Treatment group II</span>
<span class="no">treat2</span> <span class="kw">=</span> <span class="fu"><a href="https://rdrr.io/pkg/MethylIT.utils/man/simulateCounts.html">simulateCounts</a></span>(<span class="kw">num.samples</span> <span class="kw">=</span> <span class="fl">5</span>, <span class="kw">sites</span> <span class="kw">=</span> <span class="no">sites</span>, <span class="kw">alpha</span> <span class="kw">=</span> <span class="no">alpha.g2</span>,
                        <span class="kw">beta</span> <span class="kw">=</span> <span class="fl">0.5</span>, <span class="kw">size</span> <span class="kw">=</span> <span class="fl">50</span>, <span class="kw">theta</span> <span class="kw">=</span> <span class="fl">4.5</span>,
                        <span class="kw">sample.ids</span> <span class="kw">=</span> <span class="no">treatment.nam2</span>)</pre></body></html></div>
<p>A reference sample (virtual individual) is created using individual samples from the control population using function <a href="https://genomaths.github.io/MethylIT_HTML_Manual/poolFromGRlist.html">poolFromGRlist</a>. The reference sample is further used to compute the information divergences of methylation levels, <span class="math inline">\(TV_d\)</span> and <span class="math inline">\(H\)</span>, with function <a href="https://genomaths.github.io/MethylIT_HTML_Manual/estimateDivergence.html">estimateDivergence</a>. This is a first fundamental step to remove the background noise (fluctuations) generated by the inherent stochasticity of the molecular processes in the cells.</p>
<div class="sourceCode" id="cb2"><html><body><pre class="r"><span class="co"># === Methylation level divergences ===</span>
<span class="co"># Reference sample</span>
<span class="no">ref</span> <span class="kw">=</span> <span class="fu"><a href="../reference/poolFromGRlist.html">poolFromGRlist</a></span>(<span class="no">ref0</span>, <span class="kw">stat</span> <span class="kw">=</span> <span class="st">"mean"</span>, <span class="kw">num.cores</span> <span class="kw">=</span> <span class="fl">4L</span>, <span class="kw">verbose</span> <span class="kw">=</span> <span class="fl">FALSE</span>)

<span class="no">divs</span> <span class="kw">&lt;-</span> <span class="fu"><a href="../reference/estimateDivergence.html">estimateDivergence</a></span>(<span class="kw">ref</span> <span class="kw">=</span> <span class="no">ref</span>, <span class="kw">indiv</span> <span class="kw">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="no">ctrl</span>, <span class="no">treat</span>, <span class="no">treat2</span>), <span class="kw">Bayesian</span> <span class="kw">=</span> <span class="fl">TRUE</span>,
                           <span class="kw">num.cores</span> <span class="kw">=</span> <span class="fl">6L</span>, <span class="kw">percentile</span> <span class="kw">=</span> <span class="fl">1</span>, <span class="kw">verbose</span> <span class="kw">=</span> <span class="fl">FALSE</span>)

<span class="co"># To remove hd == 0 to estimate. The methylation signal only is given for  </span>
<span class="no">divs</span> <span class="kw">=</span> <span class="fu"><a href="../reference/lapply.html">lapply</a></span>(<span class="no">divs</span>, <span class="kw">function</span>(<span class="no">div</span>) <span class="no">div</span>[ <span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">abs</a></span>(<span class="no">div</span>$<span class="no">hdiv</span>) <span class="kw">&gt;</span> <span class="fl">0</span> ], <span class="kw">keep.attr</span> <span class="kw">=</span> <span class="fl">TRUE</span>)
<span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span>(<span class="no">divs</span>) <span class="kw">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span>(<span class="no">divs</span>)</pre></body></html></div>
<p>To get some statistical description about the sample is useful. Here, empirical critical values for the probability distribution of <span class="math inline">\(H\)</span> and <span class="math inline">\(TV\)</span> can is obtained using <em>quantile</em> function from the R package <em>stats</em>.</p>
<div class="sourceCode" id="cb3"><html><body><pre class="r"><span class="no">critical.val</span> <span class="kw">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/do.call.html">do.call</a></span>(<span class="no">rbind</span>, <span class="fu"><a href="../reference/lapply.html">lapply</a></span>(<span class="no">divs</span>, <span class="kw">function</span>(<span class="no">x</span>) {
  <span class="no">x</span> <span class="kw">&lt;-</span> <span class="no">x</span>[<span class="no">x</span>$<span class="no">hdiv</span> <span class="kw">&gt;</span> <span class="fl">0</span>]
  <span class="no">hd.95</span> <span class="kw">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/quantile.html">quantile</a></span>(<span class="no">x</span>$<span class="no">hdiv</span>, <span class="fl">0.95</span>)
  <span class="no">tv.95</span> <span class="kw">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/quantile.html">quantile</a></span>(<span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">abs</a></span>(<span class="no">x</span>$<span class="no">bay.TV</span>), <span class="fl">0.95</span>)
  <span class="fu"><a href="https://rdrr.io/r/base/function.html">return</a></span>(<span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="kw">tv</span> <span class="kw">=</span> <span class="no">tv.95</span>, <span class="kw">hd</span> <span class="kw">=</span> <span class="no">hd.95</span>))
}))
<span class="no">critical.val</span></pre></body></html></div>
<pre><code>##        tv.95%    hd.95%
## C1  0.6523410  62.26835
## C2  0.6500774  60.89741
## C3  0.6508289  61.48977
## C4  0.4856903  56.60726
## C5  0.4967501  58.12772
## T1  0.9236788 126.34287
## T2  0.9136199 120.45119
## T3  0.9137842 121.99485
## T4  0.9192167 124.54324
## T5  0.9225962 124.25515
## T6  0.9447952 132.69525
## T7  0.9447369 134.88511
## T8  0.9408397 131.80632
## T9  0.9482647 134.69034
## T10 0.9456276 133.87224</code></pre>
</div>
<div id="modeling-the-methylation-signal" class="section level1">
<h1 class="hasAnchor">
<a href="#modeling-the-methylation-signal" class="anchor"></a>Modeling the methylation signal</h1>
<p>Here, the methylation signal is expressed in terms of Hellinger divergence of methylation levels. Here, the signal distribution is modelled by a Weibull probability distribution model. Basically, the model could be a member of the generalized gamma distribution family. For example, it could be gamma distribution, Weibull, or log-normal. To describe the signal, we may prefer a model with a cross-validations: R.Cross.val &gt; 0.95. Cross-validations for the nonlinear regressions are performed in each methylome as described in <span class="citation">(Stevens 2009)</span>. The non-linear fit is performed through the function <a href="https://genomaths.github.io/MethylIT_HTML_Manual/nonlinearFitDist.html">nonlinearFitDist</a></p>
<p>The best model excluding “GGamma3P” model, for which the computation is computationally expensive:</p>
<div class="sourceCode" id="cb5"><html><body><pre class="r"><span class="no">d</span> <span class="kw">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="st">"Weibull2P"</span>, <span class="st">"Weibull3P"</span>, <span class="st">"Gamma2P"</span>, <span class="st">"Gamma3P"</span>)
<span class="no">gof</span> <span class="kw">&lt;-</span> <span class="fu"><a href="../reference/gofReport.html">gofReport</a></span>(<span class="kw">HD</span> <span class="kw">=</span> <span class="no">divs</span>, <span class="kw">column</span> <span class="kw">=</span> <span class="fl">9L</span>, <span class="kw">model</span> <span class="kw">=</span> <span class="no">d</span>, <span class="kw">num.cores</span> <span class="kw">=</span> <span class="fl">6L</span>,
                    <span class="kw">output</span> <span class="kw">=</span> <span class="st">"all"</span>, <span class="kw">verbose</span> <span class="kw">=</span> <span class="fl">FALSE</span>)</pre></body></html></div>
<div class="sourceCode" id="cb6"><html><body><pre class="r"><span class="no">gof</span>$<span class="no">bestModel</span></pre></body></html></div>
<pre><code>##          C1          C2          C3          C4          C5          T1 
## "Weibull3P" "Weibull3P" "Weibull3P" "Weibull3P" "Weibull3P" "Weibull3P" 
##          T2          T3          T4          T5          T6          T7 
## "Weibull3P" "Weibull3P" "Weibull3P" "Weibull3P" "Weibull3P" "Weibull3P" 
##          T8          T9         T10 
## "Weibull3P" "Weibull3P" "Weibull3P"</code></pre>
<p>Although we did not included the main member of the generalized gamma distribution family (“GGamma3P”), the Cross-validations correlation coefficient <em>w3p_R.Cross.val</em> values above 0.99 gives us some peace of mind on our confidence on the model prediction power/performance when confronted with external data sets (AIC and BIC are not conceived to provide such an information).</p>
<div class="sourceCode" id="cb8"><html><body><pre class="r"><span class="no">gof</span>$<span class="no">stats</span></pre></body></html></div>
<pre><code>##       w2p_AIC w2p_R.Cross.val   w3p_AIC w3p_R.Cross.val   g2p_AIC
## C1  -172642.0       0.9994639 -174557.7       0.9994972 -164820.3
## C2  -175594.8       0.9995131 -177009.1       0.9995353 -167532.6
## C3  -177238.3       0.9995420 -178755.3       0.9995651 -169774.1
## C4  -219269.6       0.9994956 -264072.9       0.9998548 -206343.4
## C5  -217500.5       0.9994373 -273018.4       0.9998799 -205306.2
## T1  -168079.8       0.9972704 -225575.8       0.9994669 -160887.9
## T2  -167286.1       0.9972728 -226888.2       0.9995015 -160748.6
## T3  -170301.7       0.9974336 -227799.2       0.9995013 -163997.9
## T4  -168551.1       0.9973219 -225182.0       0.9994659 -162169.6
## T5  -167122.0       0.9972265 -227207.9       0.9994983 -160694.2
## T6  -173245.4       0.9971877 -229256.8       0.9993947 -165656.4
## T7  -170905.0       0.9970144 -228452.3       0.9993817 -163341.9
## T8  -171372.5       0.9970760 -229286.8       0.9994005 -163649.4
## T9  -170096.9       0.9969618 -227490.3       0.9993672 -162250.4
## T10 -171266.7       0.9970281 -228041.3       0.9993709 -163857.2
##     g2p_R.Cross.val   g3p_AIC g3p_R.Cross.val      bestModel
## C1        0.9993929 -166320.3       0.9994541            w3p
## C2        0.9994499 -168751.9       0.9994939            w3p
## C3        0.9994861 -170986.9       0.9995260            w3p
## C4        0.9993142 -262797.6       0.9998669 Needs revision
## C5        0.9992290 -267887.9       0.9998753            w3p
## T1        0.9963828 -205273.7       0.9989377            w3p
## T2        0.9964685 -206912.6       0.9990147            w3p
## T3        0.9966887 -208521.3       0.9990291            w3p
## T4        0.9965315 -205648.9       0.9989541            w3p
## T5        0.9964091 -206816.6       0.9989987            w3p
## T6        0.9962174 -208521.5       0.9988035            w3p
## T7        0.9959979 -206833.2       0.9987503            w3p
## T8        0.9960769 -207922.5       0.9988038            w3p
## T9        0.9958861 -205571.5       0.9987166            w3p
## T10       0.9960165 -206551.4       0.9987330            w3p</code></pre>
</div>
<div id="estimation-of-an-optimal-cutpoint-to-discriminate-the-signal-induced-by-the-treatment" class="section level1">
<h1 class="hasAnchor">
<a href="#estimation-of-an-optimal-cutpoint-to-discriminate-the-signal-induced-by-the-treatment" class="anchor"></a>Estimation of an optimal cutpoint to discriminate the signal induced by the treatment</h1>
<p>The above statistical description of the dataset (evidently) suggests that there two main groups: control and treatments, while treatment group would split into two subgroups of samples. In the current case, to search for a good cutpoint, we do not need to use all the samples. The critical value <span class="math inline">\(H_{\alpha=0.05}=33.51223\)</span> suggests that any optimal cutpoint for the subset of samples T1 to T5 will be optimal for the samples T6 to T10 as well.</p>
<p>Below, we are letting the PCA+LDA model classifier to take the decision on whether a differentially methylated cytosine position is a treatment DMP. To do it, Methyl-IT function <a href="https://genomaths.github.io/MethylIT_HTML_Manual/getPotentialDIMP.html">getPotentialDIMP</a> is used to get methylation signal probabilities of the observed <span class="math inline">\(H\)</span> values for all cytosine site (alpha = 1), in accordance with the 2-parameter Weibull distribution model. Next, this information will be used to identify DMPs using Methyl-IT function <a href="https://genomaths.github.io/MethylIT_HTML_Manual/estimateCutPoint.html">estimateCutPoint</a>. Cytosine positions with <span class="math inline">\(H\)</span> values above the cutpoint are considered DMPs. Finally, a PCA + QDA model classifier will be fitted to classify DMPs into two classes: DMPs from control and those from treatment.</p>
<div class="sourceCode" id="cb10"><html><body><pre class="r"><span class="no">dmps</span> <span class="kw">&lt;-</span> <span class="fu"><a href="../reference/getPotentialDIMP.html">getPotentialDIMP</a></span>(<span class="kw">LR</span> <span class="kw">=</span> <span class="no">divs</span>,
                         <span class="kw">nlms</span> <span class="kw">=</span> <span class="no">gof</span>$<span class="no">nlms</span>,  <span class="kw">div.col</span> <span class="kw">=</span> <span class="fl">9L</span>,
                         <span class="kw">tv.cut</span> <span class="kw">=</span> <span class="fl">0.461</span>, <span class="kw">tv.col</span> <span class="kw">=</span> <span class="fl">8</span>, <span class="kw">alpha</span> <span class="kw">=</span> <span class="fl">0.05</span>,
                         <span class="kw">dist.name</span> <span class="kw">=</span> <span class="no">gof</span>$<span class="no">bestModel</span>)
<span class="no">cutp</span> <span class="kw">=</span> <span class="fu"><a href="../reference/estimateCutPoint.html">estimateCutPoint</a></span>(<span class="kw">LR</span> <span class="kw">=</span> <span class="no">dmps</span>, <span class="kw">simple</span> <span class="kw">=</span> <span class="fl">FALSE</span>,
                        <span class="kw">column</span> <span class="kw">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="kw">hdiv</span> <span class="kw">=</span> <span class="fl">TRUE</span>, <span class="kw">TV</span> <span class="kw">=</span> <span class="fl">TRUE</span>,
                                   <span class="kw">wprob</span> <span class="kw">=</span> <span class="fl">TRUE</span>, <span class="kw">pos</span> <span class="kw">=</span> <span class="fl">TRUE</span>),
                        <span class="kw">classifier1</span> <span class="kw">=</span> <span class="st">"pca.lda"</span>,
                        <span class="kw">classifier2</span> <span class="kw">=</span> <span class="st">"pca.qda"</span>, <span class="kw">tv.cut</span> <span class="kw">=</span> <span class="fl">0.461</span>,
                        <span class="kw">control.names</span> <span class="kw">=</span> <span class="no">control.nam</span>,
                        <span class="kw">treatment.names</span> <span class="kw">=</span> <span class="no">treatment.nam1</span>,
                        <span class="kw">post.cut</span> <span class="kw">=</span> <span class="fl">0.5</span>, <span class="kw">cut.values</span> <span class="kw">=</span> <span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq</a></span>(<span class="fl">15</span>, <span class="fl">38</span>, <span class="fl">1</span>),
                        <span class="kw">clas.perf</span> <span class="kw">=</span> <span class="fl">TRUE</span>, <span class="kw">prop</span> <span class="kw">=</span> <span class="fl">0.6</span>,
                        <span class="kw">center</span> <span class="kw">=</span> <span class="fl">FALSE</span>, <span class="kw">scale</span> <span class="kw">=</span> <span class="fl">FALSE</span>,
                        <span class="kw">n.pc</span> <span class="kw">=</span> <span class="fl">4</span>, <span class="kw">div.col</span> <span class="kw">=</span> <span class="fl">9L</span>, <span class="kw">stat</span> <span class="kw">=</span> <span class="fl">0</span>)
<span class="no">cutp</span></pre></body></html></div>
<pre><code>## Cutpoint estimation with 'pca.lda' classifier 
## Cutpoint search performed using model posterior probabilities 
## 
## Posterior probability used to get the cutpoint = 0.5 
## Cytosine sites with treatment PostProbCut &gt;= 0.5 have a 
## divergence value &gt;= 92.13839 
## 
## Optimized statistic: Accuracy = 1 
## Cutpoint = 92.138 
## 
## Model classifier 'pca.qda' 
## 
## The accessible objects in the output list are: 
##                    Length Class           Mode     
## cutpoint           1      -none-          numeric  
## testSetPerformance 6      confusionMatrix list     
## testSetModel.FDR   1      -none-          numeric  
## model              2      pcaQDA          list     
## modelConfMatrix    6      confusionMatrix list     
## initModel          1      -none-          character
## postProbCut        1      -none-          numeric  
## postCut            1      -none-          numeric  
## classifier         1      -none-          character
## statistic          1      -none-          character
## optStatVal         1      -none-          numeric  
## cutpData           1      -none-          logical</code></pre>
<p>In this case, the cutpoint <span class="math inline">\(H_{cutpoint}=92.138\)</span> is lower from what is expected from the higher treatment empirical <span class="math inline">\(H_{\alpha = 0.05}^{TT_{Emp}}=120.45119\)</span> critical value: <span class="math inline">\(H_{cutpoint} &lt; H_{\alpha = 0.05}^{TT_{Emp}}\)</span>.</p>
<p>The model performance in in the test dataset is:</p>
<div class="sourceCode" id="cb12"><html><body><pre class="r"><span class="no">cutp</span>$<span class="no">testSetPerformance</span></pre></body></html></div>
<pre><code>## Confusion Matrix and Statistics
## 
##           Reference
## Prediction   CT   TT
##         CT 2464    0
##         TT    0 5278
##                                      
##                Accuracy : 1          
##                  95% CI : (0.9995, 1)
##     No Information Rate : 0.6817     
##     P-Value [Acc &gt; NIR] : &lt; 2.2e-16  
##                                      
##                   Kappa : 1          
##                                      
##  Mcnemar's Test P-Value : NA         
##                                      
##             Sensitivity : 1.0000     
##             Specificity : 1.0000     
##          Pos Pred Value : 1.0000     
##          Neg Pred Value : 1.0000     
##              Prevalence : 0.6817     
##          Detection Rate : 0.6817     
##    Detection Prevalence : 0.6817     
##       Balanced Accuracy : 1.0000     
##                                      
##        'Positive' Class : TT         
## </code></pre>
</div>
<div id="representing-individual-samples-as-vectors-from-the-n-dimensional-space" class="section level1">
<h1 class="hasAnchor">
<a href="#representing-individual-samples-as-vectors-from-the-n-dimensional-space" class="anchor"></a>Representing individual samples as vectors from the <em>N</em>-dimensional space</h1>
<p>The above cutpoint can be used to identify DMPs from control and treatment. The PCA+QDA model classifier can be used any time to discriminate control DMPs from those treatment. DMPs are retrieved using <a href="https://genomaths.github.io/MethylIT_HTML_Manual/selectDIMP.html">selectDIMP</a> function (<code>selectDIMP</code>):</p>
<div class="sourceCode" id="cb14"><html><body><pre class="r"><span class="no">dmps</span> <span class="kw">&lt;-</span> <span class="fu"><a href="../reference/selectDIMP.html">selectDIMP</a></span>(<span class="kw">LR</span> <span class="kw">=</span> <span class="no">divs</span>, <span class="kw">div.col</span> <span class="kw">=</span> <span class="fl">9L</span>, <span class="kw">cutpoint</span> <span class="kw">=</span> <span class="no">cutp</span>$<span class="no">cutpoint</span>,
                   <span class="kw">tv.cut</span> <span class="kw">=</span> <span class="fl">0.34</span>, <span class="kw">tv.col</span> <span class="kw">=</span> <span class="fl">7</span>)
<span class="fu"><a href="https://rdrr.io/r/base/lapply.html">sapply</a></span>(<span class="no">dmps</span>,<span class="no">length</span>)</pre></body></html></div>
<pre><code>##   C1   C2   C3   C4   C5   T1   T2   T3   T4   T5   T6   T7   T8   T9  T10 
##  450  428  410  522  578 2808 2651 2632 2735 2768 3170 3233 3210 3318 3239</code></pre>
<p>Next, to represent individual samples as vectors from the <em>N</em>-dimensional space, we can use <a href="https://genomaths.github.io/MethylIT_utils_HTML_Manual/getGRegionsStat-methods.html">getGRegionsStat</a> function from <a href="https://github.com/genomaths/MethylIT.utils">MethylIT.utils</a> R package. Here, the simulated “chromosome” is split into regions of 450bp non-overlapping windows. and the <em>density</em> of Hellinger divergences values is taken for each windows.</p>
<div class="sourceCode" id="cb16"><html><body><pre class="r"><span class="no">ns</span> <span class="kw">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span>(<span class="no">dmps</span>)
<span class="no">DMRs</span> <span class="kw">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/MethylIT.utils/man/getGRegionsStat-methods.html">getGRegionsStat</a></span>(<span class="kw">GR</span> <span class="kw">=</span> <span class="no">dmps</span>, <span class="kw">win.size</span> <span class="kw">=</span> <span class="fl">150</span>, <span class="kw">step.size</span> <span class="kw">=</span> <span class="fl">150</span>,
                        <span class="kw">stat</span> <span class="kw">=</span> <span class="st">"density"</span>, <span class="kw">column</span> <span class="kw">=</span> <span class="fl">9L</span>, <span class="kw">scaling</span> <span class="kw">=</span> <span class="fl">1</span>)
<span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span>(<span class="no">DMRs</span>) <span class="kw">&lt;-</span> <span class="no">ns</span>
<span class="fu">as</span>(<span class="no">DMRs</span>, <span class="st">"GRangesList"</span>)</pre></body></html></div>
</div>
<div id="hierarchical-clustering" class="section level1">
<h1 class="hasAnchor">
<a href="#hierarchical-clustering" class="anchor"></a>Hierarchical Clustering</h1>
<p>Hierarchical clustering (HC) is an unsupervised machine learning approach. HC can provide an initial estimation of the number of possible groups and information on their members. However, the effectivity of HC will depend on the experimental dataset, the metric used, and the agglomeration algorithm applied. For an unknown reason (and based on the personal experience of the author working in numerical taxonomy), Ward’s agglomeration algorithm performs much better on biological experimental datasets than the rest of the available algorithms like UPGMA, UPGMC, etc.</p>
<div class="sourceCode" id="cb17"><html><body><pre class="r"><span class="no">dmgm</span> <span class="kw">&lt;-</span> <span class="fu"><a href="../reference/uniqueGRanges.html">uniqueGRanges</a></span>(<span class="no">DMRs</span>, <span class="kw">verbose</span> <span class="kw">=</span> <span class="fl">FALSE</span>)
<span class="no">dmgm</span> <span class="kw">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/t.html">t</a></span>(<span class="fu"><a href="https://rdrr.io/r/base/matrix.html">as.matrix</a></span>(<span class="fu">mcols</span>(<span class="no">dmgm</span>)))
<span class="fu"><a href="https://rdrr.io/r/base/colnames.html">rownames</a></span>(<span class="no">dmgm</span>) <span class="kw">&lt;-</span> <span class="no">ns</span>
<span class="no">sampleNames</span> <span class="kw">&lt;-</span> <span class="no">ns</span>

<span class="no">hc</span> <span class="kw">=</span> <span class="fu"><a href="https://rdrr.io/r/stats/hclust.html">hclust</a></span>(<span class="fu"><a href="https://rdrr.io/r/stats/dist.html">dist</a></span>(<span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span>( <span class="no">dmgm</span> ))^<span class="fl">2</span>, <span class="kw">method</span> <span class="kw">=</span> <span class="st">'ward.D'</span>)
<span class="no">hc.rsq</span> <span class="kw">=</span> <span class="no">hc</span>
<span class="no">hc.rsq</span>$<span class="no">height</span> <span class="kw">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">sqrt</a></span>( <span class="no">hc</span>$<span class="no">height</span> )</pre></body></html></div>
<div id="dendrogram" class="section level2">
<h2 class="hasAnchor">
<a href="#dendrogram" class="anchor"></a>Dendrogram</h2>
<div class="sourceCode" id="cb18"><html><body><pre class="r"><span class="no">colors</span> <span class="kw">=</span> <span class="no">sampleNames</span>
<span class="no">colors</span>[<span class="fu"><a href="https://rdrr.io/r/base/grep.html">grep</a></span>(<span class="st">"C"</span>, <span class="no">colors</span>)] <span class="kw">&lt;-</span> <span class="st">"green4"</span>
<span class="no">colors</span>[<span class="fu"><a href="https://rdrr.io/r/base/grep.html">grep</a></span>(<span class="st">"T[6-9]{1}"</span>, <span class="no">colors</span>)] <span class="kw">&lt;-</span> <span class="st">"red"</span>
<span class="no">colors</span>[<span class="fu"><a href="https://rdrr.io/r/base/grep.html">grep</a></span>(<span class="st">"T10"</span>, <span class="no">colors</span>)] <span class="kw">&lt;-</span> <span class="st">"red"</span>
<span class="no">colors</span>[<span class="fu"><a href="https://rdrr.io/r/base/grep.html">grep</a></span>(<span class="st">"T[1-5]"</span>, <span class="no">colors</span>)] <span class="kw">&lt;-</span> <span class="st">"blue"</span>

<span class="co"># rgb(red, green, blue, alpha, names = NULL, maxColorValue = 1)</span>
<span class="no">clusters.color</span> <span class="kw">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="fu"><a href="https://rdrr.io/r/grDevices/rgb.html">rgb</a></span>(<span class="fl">0</span>, <span class="fl">0.7</span>, <span class="fl">0</span>, <span class="fl">0.1</span>), <span class="fu"><a href="https://rdrr.io/r/grDevices/rgb.html">rgb</a></span>(<span class="fl">0</span>, <span class="fl">0</span>, <span class="fl">1</span>, <span class="fl">0.1</span>), <span class="fu"><a href="https://rdrr.io/r/grDevices/rgb.html">rgb</a></span>(<span class="fl">1</span>, <span class="fl">0.2</span>, <span class="fl">0</span>, <span class="fl">0.1</span>))

<span class="fu"><a href="https://rdrr.io/r/graphics/par.html">par</a></span>(<span class="kw">font.lab</span><span class="kw">=</span><span class="fl">2</span>,<span class="kw">font</span><span class="kw">=</span><span class="fl">3</span>,<span class="kw">font.axis</span><span class="kw">=</span><span class="fl">2</span>, <span class="kw">mar</span><span class="kw">=</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="fl">0</span>,<span class="fl">3</span>,<span class="fl">2</span>,<span class="fl">0</span>), <span class="kw">family</span><span class="kw">=</span><span class="st">"serif"</span> , <span class="kw">lwd</span> <span class="kw">=</span> <span class="fl">0.4</span>)
<span class="fu"><a href="https://rdrr.io/r/graphics/plot.html">plot</a></span>(<span class="fu"><a href="https://rdrr.io/pkg/ape/man/as.phylo.html">as.phylo</a></span>(<span class="no">hc.rsq</span>), <span class="kw">tip.color</span> <span class="kw">=</span> <span class="no">colors</span>, <span class="kw">label.offset</span> <span class="kw">=</span> <span class="fl">0.5</span>, <span class="kw">font</span> <span class="kw">=</span> <span class="fl">2</span>, <span class="kw">cex</span> <span class="kw">=</span> <span class="fl">0.9</span>,
     <span class="kw">edge.width</span>  <span class="kw">=</span> <span class="fl">0.4</span>, <span class="kw">direction</span> <span class="kw">=</span> <span class="st">"downwards"</span>, <span class="kw">no.margin</span> <span class="kw">=</span> <span class="fl">FALSE</span>,
     <span class="kw">align.tip.label</span> <span class="kw">=</span> <span class="fl">TRUE</span>, <span class="kw">adj</span> <span class="kw">=</span> <span class="fl">0</span>)
<span class="fu"><a href="https://rdrr.io/pkg/ape/man/axisPhylo.html">axisPhylo</a></span>( <span class="fl">2</span>, <span class="kw">las</span> <span class="kw">=</span> <span class="fl">1</span>, <span class="kw">lwd</span> <span class="kw">=</span> <span class="fl">0.4</span>, <span class="kw">cex.axis</span> <span class="kw">=</span> <span class="fl">1.4</span>, <span class="kw">hadj</span> <span class="kw">=</span> <span class="fl">0.8</span>, <span class="kw">tck</span> <span class="kw">=</span> -<span class="fl">0.01</span> )
<span class="co">## cuts = c(xleft, ybottom, xright, ytop)</span>
<span class="fu"><a href="https://rdrr.io/pkg/MethylIT.utils/man/hclust_rect.html">hclust_rect</a></span>(<span class="no">hc.rsq</span>, <span class="kw">k</span> <span class="kw">=</span> <span class="fl">3L</span>, <span class="kw">border</span> <span class="kw">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="st">"green4"</span>, <span class="st">"blue"</span>, <span class="st">"red"</span>),
            <span class="kw">color</span> <span class="kw">=</span> <span class="no">clusters.color</span>, <span class="kw">cuts</span> <span class="kw">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="fl">0.56</span>, <span class="fl">1.4</span>, <span class="fl">0.41</span>, <span class="fl">34</span>))</pre></body></html></div>
<p><img src="pca_lda_with_methylit_files/figure-html/dendrogram-1.png" width="700"></p>
<p>Here, we have use function <a href="https://www.rdocumentation.org/packages/ape/versions/5.3/topics/as.phylo">as.phylo</a> from the R package <a href="https://www.rdocumentation.org/packages/ape/versions/5.3">ape</a> for better dendrogram visualization and function <a href="https://genomaths.github.io/MethylIT_utils_HTML_Manual/hclust_rect.html">hclust_rect</a> from <a href="https://github.com/genomaths/MethylIT.utils">MethylIT.utils</a> R package to draw rectangles with background colors around the branches of a dendrogram highlighting the corresponding clusters.</p>
</div>
</div>
<div id="pca-lda" class="section level1">
<h1 class="hasAnchor">
<a href="#pca-lda" class="anchor"></a>PCA + LDA</h1>
<p>MethylIT function <a href="https://genomaths.github.io/MethylIT_HTML_Manual/pcaLDA.html">pcaLDA</a> will be used to perform the PCA and PCA + LDA analyses. The function returns a list of two objects: 1) ‘lda’: an object of class ‘lda’ from package ‘MASS’. 2) ‘pca’: an object of class ‘prcomp’ from package ‘stats’. For information on how to use these objects see ?lda and ?prcomp.</p>
<p>Unlike hierarchical clustering (HC), LDA is a supervised machine learning approach. So, we must provide a prior classification of the individuals, which can be derived, for example, from the HC, or from a previous exploratory analysis with PCA.</p>
<div class="sourceCode" id="cb19"><html><body><pre class="r"><span class="co"># A prior classification derived from HC</span>
<span class="no">grps</span> <span class="kw">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/cutree.html">cutree</a></span>(<span class="no">hc</span>, <span class="kw">k</span> <span class="kw">=</span> <span class="fl">3</span>)
<span class="no">grps</span>[<span class="fu"><a href="https://rdrr.io/r/base/grep.html">grep</a></span>(<span class="fl">1</span>, <span class="no">grps</span>)] <span class="kw">&lt;-</span> <span class="st">"CT"</span>
<span class="no">grps</span>[<span class="fu"><a href="https://rdrr.io/r/base/grep.html">grep</a></span>(<span class="fl">2</span>, <span class="no">grps</span>)] <span class="kw">&lt;-</span> <span class="st">"T1"</span>
<span class="no">grps</span>[<span class="fu"><a href="https://rdrr.io/r/base/grep.html">grep</a></span>(<span class="fl">3</span>, <span class="no">grps</span>)] <span class="kw">&lt;-</span> <span class="st">"T2"</span>
<span class="no">grps</span> <span class="kw">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span>(<span class="no">grps</span>)

<span class="no">ld</span> <span class="kw">&lt;-</span> <span class="fu"><a href="../reference/pcaLDA.html">pcaLDA</a></span>(<span class="kw">data</span> <span class="kw">=</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span>(<span class="no">dmgm</span>), <span class="kw">grouping</span> <span class="kw">=</span> <span class="no">grps</span>, <span class="kw">n.pc</span> <span class="kw">=</span> <span class="fl">3</span>, <span class="kw">max.pc</span> <span class="kw">=</span> <span class="fl">3</span>,
             <span class="kw">scale</span> <span class="kw">=</span> <span class="fl">FALSE</span>, <span class="kw">center</span> <span class="kw">=</span> <span class="fl">FALSE</span>, <span class="kw">tol</span> <span class="kw">=</span> <span class="fl">1e-6</span>)
<span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span>(<span class="no">ld</span>$<span class="no">pca</span>)</pre></body></html></div>
<pre><code>## Importance of first k=3 (out of 15) components:
##                            PC1      PC2      PC3
## Standard deviation     88.6316 18.77508 17.76740
## Proportion of Variance  0.7503  0.03367  0.03015
## Cumulative Proportion   0.7503  0.78397  0.81412</code></pre>
<p>We may retain enough components so that the cumulative percent of variance accounted for at least 70 to 80%. By setting <span class="math inline">\(scale=TRUE\)</span> and <span class="math inline">\(center=TRUE\)</span>, we could have different results and would improve or not our results. In particular, these settings are essentials if the <em>N</em>-dimensional space is integrated by variables from different measurement scales/units, for example, Kg and g, or Kg and Km.</p>
<div id="pca" class="section level2">
<h2 class="hasAnchor">
<a href="#pca" class="anchor"></a>PCA</h2>
<p>The individual coordinates in the principal components (PCs) are returned by function <a href="https://genomaths.github.io/MethylIT_HTML_Manual/pcaLDA.html">pcaLDA</a>. In the current case, based on the cumulative proportion of variance, the two firsts PCs carried about the 84% of the total sample variance and could split the sample into meaningful groups.</p>
<div class="sourceCode" id="cb21"><html><body><pre class="r"><span class="no">pca.coord</span> <span class="kw">&lt;-</span> <span class="no">ld</span>$<span class="no">pca</span>$<span class="no">x</span>
<span class="no">pca.coord</span></pre></body></html></div>
<pre><code>##            PC1          PC2           PC3
## C1   -11.39339   0.73196138 -1.199633e+00
## C2   -10.71536   0.48622693  5.576992e-01
## C3   -10.00940   0.07651213  7.513925e-04
## C4   -14.06040  -0.11428258  1.205347e-02
## C5   -16.37363   1.14631960 -4.860525e-01
## T1   -96.87684  -8.04544065 -7.159331e+00
## T2   -90.76257  -5.90764558 -1.720100e+01
## T3   -91.83798   7.45707501 -9.670131e+00
## T4   -95.43765 -19.34742098 -3.246208e+00
## T5   -95.39837   2.81236674  1.892934e+00
## T6  -111.55967  10.34243038 -3.751185e+01
## T7  -115.54814 -20.09126989  3.418617e+01
## T8  -111.81608  15.49965462 -1.431783e+01
## T9  -116.12664  48.85621553  3.217684e+01
## T10 -114.52363 -35.46378545  1.210757e+01</code></pre>
</div>
<div id="graphic-pc1-vs-pc2" class="section level2">
<h2 class="hasAnchor">
<a href="#graphic-pc1-vs-pc2" class="anchor"></a>Graphic PC1 vs PC2</h2>
<p>Next, the graphic for individual coordinates in the two firsts PCs can be easily visualized now:</p>
<div class="sourceCode" id="cb23"><html><body><pre class="r"><span class="no">dt</span> <span class="kw">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span>(<span class="no">pca.coord</span>[, <span class="fl">1</span>:<span class="fl">2</span>], <span class="kw">subgrp</span> <span class="kw">=</span> <span class="no">grps</span>)

<span class="no">p0</span> <span class="kw">&lt;-</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/theme.html">theme</a></span>(
  <span class="kw">axis.text.x</span>  <span class="kw">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_text</a></span>( <span class="kw">face</span> <span class="kw">=</span> <span class="st">"bold"</span>, <span class="kw">size</span> <span class="kw">=</span> <span class="fl">18</span>, <span class="kw">color</span><span class="kw">=</span><span class="st">"black"</span>,
                               <span class="co"># hjust = 0.5, vjust = 0.5, </span>
                               <span class="kw">family</span> <span class="kw">=</span> <span class="st">"serif"</span>, <span class="kw">angle</span> <span class="kw">=</span> <span class="fl">0</span>,
                               <span class="kw">margin</span> <span class="kw">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">margin</a></span>(<span class="fl">1</span>,<span class="fl">0</span>,<span class="fl">1</span>,<span class="fl">0</span>, <span class="kw">unit</span> <span class="kw">=</span> <span class="st">"pt"</span> )),
  <span class="kw">axis.text.y</span>  <span class="kw">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_text</a></span>( <span class="kw">face</span> <span class="kw">=</span> <span class="st">"bold"</span>, <span class="kw">size</span> <span class="kw">=</span> <span class="fl">18</span>, <span class="kw">color</span><span class="kw">=</span><span class="st">"black"</span>,
                               <span class="kw">family</span> <span class="kw">=</span> <span class="st">"serif"</span>,
                               <span class="kw">margin</span> <span class="kw">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">margin</a></span>( <span class="fl">0</span>,<span class="fl">0.1</span>,<span class="fl">0</span>,<span class="fl">0</span>, <span class="kw">unit</span> <span class="kw">=</span> <span class="st">"mm"</span> )),
  <span class="kw">axis.title.x</span> <span class="kw">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_text</a></span>(<span class="kw">face</span> <span class="kw">=</span> <span class="st">"bold"</span>, <span class="kw">family</span> <span class="kw">=</span> <span class="st">"serif"</span>, <span class="kw">size</span> <span class="kw">=</span> <span class="fl">18</span>,
                              <span class="kw">color</span><span class="kw">=</span><span class="st">"black"</span>, <span class="kw">vjust</span> <span class="kw">=</span> <span class="fl">0</span> ),
  <span class="kw">axis.title.y</span> <span class="kw">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_text</a></span>(<span class="kw">face</span> <span class="kw">=</span> <span class="st">"bold"</span>, <span class="kw">family</span> <span class="kw">=</span> <span class="st">"serif"</span>, <span class="kw">size</span> <span class="kw">=</span> <span class="fl">18</span>,
                              <span class="kw">color</span><span class="kw">=</span><span class="st">"black"</span>,
                              <span class="kw">margin</span> <span class="kw">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">margin</a></span>( <span class="fl">0</span>,<span class="fl">2</span>,<span class="fl">0</span>,<span class="fl">0</span>, <span class="kw">unit</span> <span class="kw">=</span> <span class="st">"mm"</span> ) ),
  <span class="kw">legend.title</span><span class="kw">=</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_blank</a></span>(),
  <span class="kw">legend.text</span> <span class="kw">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_text</a></span>(<span class="kw">size</span> <span class="kw">=</span> <span class="fl">20</span>, <span class="kw">face</span> <span class="kw">=</span> <span class="st">"bold"</span>, <span class="kw">family</span> <span class="kw">=</span> <span class="st">"serif"</span>),
  <span class="kw">legend.position</span> <span class="kw">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="fl">0.88</span>, <span class="fl">0.14</span>),

  <span class="kw">panel.border</span> <span class="kw">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_rect</a></span>(<span class="kw">fill</span><span class="kw">=</span><span class="fl">NA</span>, <span class="kw">colour</span> <span class="kw">=</span> <span class="st">"black"</span>,<span class="kw">size</span><span class="kw">=</span><span class="fl">0.07</span>),
  <span class="kw">panel.grid.minor</span> <span class="kw">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_line</a></span>(<span class="kw">color</span><span class="kw">=</span> <span class="st">"white"</span>,<span class="kw">size</span> <span class="kw">=</span> <span class="fl">0.2</span>),
  <span class="kw">axis.ticks</span> <span class="kw">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_line</a></span>(<span class="kw">size</span> <span class="kw">=</span> <span class="fl">0.1</span>), <span class="kw">axis.ticks.length</span> <span class="kw">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/reexports.html">unit</a></span>(<span class="fl">0.5</span>, <span class="st">"mm"</span>),
  <span class="kw">plot.margin</span> <span class="kw">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/reexports.html">unit</a></span>(<span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="fl">1</span>,<span class="fl">1</span>,<span class="fl">0</span>,<span class="fl">0</span>), <span class="st">"lines"</span>))

<span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span>(<span class="no">dt</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span>(<span class="kw">x</span> <span class="kw">=</span> <span class="no">PC1</span>, <span class="kw">y</span> <span class="kw">=</span> <span class="no">PC2</span>, <span class="kw">colour</span> <span class="kw">=</span> <span class="no">grps</span>)) +
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_abline.html">geom_vline</a></span>(<span class="kw">xintercept</span> <span class="kw">=</span> <span class="fl">0</span>, <span class="kw">color</span> <span class="kw">=</span> <span class="st">"white"</span>, <span class="kw">size</span> <span class="kw">=</span> <span class="fl">1</span>) +
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_abline.html">geom_hline</a></span>(<span class="kw">yintercept</span> <span class="kw">=</span> <span class="fl">0</span>, <span class="kw">color</span> <span class="kw">=</span> <span class="st">"white"</span>, <span class="kw">size</span> <span class="kw">=</span> <span class="fl">1</span>) +
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span>(<span class="kw">size</span> <span class="kw">=</span> <span class="fl">6</span>) +
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_manual.html">scale_color_manual</a></span>(<span class="kw">values</span> <span class="kw">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="st">"green4"</span>,<span class="st">"blue"</span>,<span class="st">"brown1"</span>)) +
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/stat_ellipse.html">stat_ellipse</a></span>(<span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span>(<span class="kw">x</span> <span class="kw">=</span> <span class="no">PC1</span>, <span class="kw">y</span> <span class="kw">=</span> <span class="no">PC2</span>, <span class="kw">fill</span> <span class="kw">=</span> <span class="no">subgrp</span>), <span class="kw">data</span> <span class="kw">=</span> <span class="no">dt</span>, <span class="kw">type</span> <span class="kw">=</span> <span class="st">"norm"</span>,
               <span class="kw">geom</span> <span class="kw">=</span> <span class="st">"polygon"</span>, <span class="kw">level</span> <span class="kw">=</span> <span class="fl">0.5</span>, <span class="kw">alpha</span><span class="kw">=</span><span class="fl">0.2</span>, <span class="kw">show.legend</span> <span class="kw">=</span> <span class="fl">FALSE</span>) +
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_manual.html">scale_fill_manual</a></span>(<span class="kw">values</span> <span class="kw">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="st">"green4"</span>,<span class="st">"blue"</span>,<span class="st">"brown1"</span>)) + <span class="no">p0</span></pre></body></html></div>
<p><img src="pca_lda_with_methylit_files/figure-html/pcaGraphic-1.png" width="700"></p>
</div>
<div id="graphic-ld1-vs-ld2" class="section level2">
<h2 class="hasAnchor">
<a href="#graphic-ld1-vs-ld2" class="anchor"></a>Graphic LD1 vs LD2</h2>
<p>In the current case, better resolution is obtained with the linear discriminant functions, which is based on the three firsts PCs. Notice that the number principal components used the LDA step must be lower than the number of individuals (<span class="math inline">\(N\)</span>) divided by 3: <span class="math inline">\(N/3\)</span>.</p>
<div class="sourceCode" id="cb24"><html><body><pre class="r"><span class="no">ind.coord</span> <span class="kw">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/predict.html">predict</a></span>(<span class="no">ld</span>, <span class="kw">newdata</span> <span class="kw">=</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span>(<span class="no">dmgm</span>), <span class="kw">type</span> <span class="kw">=</span> <span class="st">"scores"</span>)
<span class="no">dt</span> <span class="kw">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span>(<span class="no">ind.coord</span>, <span class="kw">subgrp</span> <span class="kw">=</span> <span class="no">grps</span>)

<span class="no">p0</span> <span class="kw">&lt;-</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/theme.html">theme</a></span>(
  <span class="kw">axis.text.x</span>  <span class="kw">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_text</a></span>( <span class="kw">face</span> <span class="kw">=</span> <span class="st">"bold"</span>, <span class="kw">size</span> <span class="kw">=</span> <span class="fl">18</span>, <span class="kw">color</span><span class="kw">=</span><span class="st">"black"</span>,
                               <span class="co"># hjust = 0.5, vjust = 0.5, </span>
                               <span class="kw">family</span> <span class="kw">=</span> <span class="st">"serif"</span>, <span class="kw">angle</span> <span class="kw">=</span> <span class="fl">0</span>,
                               <span class="kw">margin</span> <span class="kw">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">margin</a></span>(<span class="fl">1</span>,<span class="fl">0</span>,<span class="fl">1</span>,<span class="fl">0</span>, <span class="kw">unit</span> <span class="kw">=</span> <span class="st">"pt"</span> )),
  <span class="kw">axis.text.y</span>  <span class="kw">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_text</a></span>( <span class="kw">face</span> <span class="kw">=</span> <span class="st">"bold"</span>, <span class="kw">size</span> <span class="kw">=</span> <span class="fl">18</span>, <span class="kw">color</span><span class="kw">=</span><span class="st">"black"</span>,
                               <span class="kw">family</span> <span class="kw">=</span> <span class="st">"serif"</span>,
                               <span class="kw">margin</span> <span class="kw">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">margin</a></span>( <span class="fl">0</span>,<span class="fl">0.1</span>,<span class="fl">0</span>,<span class="fl">0</span>, <span class="kw">unit</span> <span class="kw">=</span> <span class="st">"mm"</span> )),
  <span class="kw">axis.title.x</span> <span class="kw">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_text</a></span>(<span class="kw">face</span> <span class="kw">=</span> <span class="st">"bold"</span>, <span class="kw">family</span> <span class="kw">=</span> <span class="st">"serif"</span>, <span class="kw">size</span> <span class="kw">=</span> <span class="fl">18</span>,
                              <span class="kw">color</span><span class="kw">=</span><span class="st">"black"</span>, <span class="kw">vjust</span> <span class="kw">=</span> <span class="fl">0</span> ),
  <span class="kw">axis.title.y</span> <span class="kw">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_text</a></span>(<span class="kw">face</span> <span class="kw">=</span> <span class="st">"bold"</span>, <span class="kw">family</span> <span class="kw">=</span> <span class="st">"serif"</span>, <span class="kw">size</span> <span class="kw">=</span> <span class="fl">18</span>,
                              <span class="kw">color</span><span class="kw">=</span><span class="st">"black"</span>,
                              <span class="kw">margin</span> <span class="kw">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">margin</a></span>( <span class="fl">0</span>,<span class="fl">2</span>,<span class="fl">0</span>,<span class="fl">0</span>, <span class="kw">unit</span> <span class="kw">=</span> <span class="st">"mm"</span> ) ),
  <span class="kw">legend.title</span><span class="kw">=</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_blank</a></span>(),
  <span class="kw">legend.text</span> <span class="kw">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_text</a></span>(<span class="kw">size</span> <span class="kw">=</span> <span class="fl">20</span>, <span class="kw">face</span> <span class="kw">=</span> <span class="st">"bold"</span>, <span class="kw">family</span> <span class="kw">=</span> <span class="st">"serif"</span>),
  <span class="kw">legend.position</span> <span class="kw">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="fl">0.15</span>, <span class="fl">0.83</span>),

  <span class="kw">panel.border</span> <span class="kw">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_rect</a></span>(<span class="kw">fill</span><span class="kw">=</span><span class="fl">NA</span>, <span class="kw">colour</span> <span class="kw">=</span> <span class="st">"black"</span>,<span class="kw">size</span><span class="kw">=</span><span class="fl">0.07</span>),
  <span class="kw">panel.grid.minor</span> <span class="kw">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_line</a></span>(<span class="kw">color</span><span class="kw">=</span> <span class="st">"white"</span>,<span class="kw">size</span> <span class="kw">=</span> <span class="fl">0.2</span>),
  <span class="kw">axis.ticks</span> <span class="kw">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_line</a></span>(<span class="kw">size</span> <span class="kw">=</span> <span class="fl">0.1</span>), <span class="kw">axis.ticks.length</span> <span class="kw">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/reexports.html">unit</a></span>(<span class="fl">0.5</span>, <span class="st">"mm"</span>),
  <span class="kw">plot.margin</span> <span class="kw">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/reexports.html">unit</a></span>(<span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="fl">1</span>,<span class="fl">1</span>,<span class="fl">0</span>,<span class="fl">0</span>), <span class="st">"lines"</span>))

<span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span>(<span class="no">dt</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span>(<span class="kw">x</span> <span class="kw">=</span> <span class="no">LD1</span>, <span class="kw">y</span> <span class="kw">=</span> <span class="no">LD2</span>, <span class="kw">colour</span> <span class="kw">=</span> <span class="no">grps</span>)) +
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_abline.html">geom_vline</a></span>(<span class="kw">xintercept</span> <span class="kw">=</span> <span class="fl">0</span>, <span class="kw">color</span> <span class="kw">=</span> <span class="st">"white"</span>, <span class="kw">size</span> <span class="kw">=</span> <span class="fl">1</span>) +
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_abline.html">geom_hline</a></span>(<span class="kw">yintercept</span> <span class="kw">=</span> <span class="fl">0</span>, <span class="kw">color</span> <span class="kw">=</span> <span class="st">"white"</span>, <span class="kw">size</span> <span class="kw">=</span> <span class="fl">1</span>) +
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span>(<span class="kw">size</span> <span class="kw">=</span> <span class="fl">6</span>) +
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_manual.html">scale_color_manual</a></span>(<span class="kw">values</span> <span class="kw">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="st">"green4"</span>,<span class="st">"blue"</span>,<span class="st">"brown1"</span>)) +
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/stat_ellipse.html">stat_ellipse</a></span>(<span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span>(<span class="kw">x</span> <span class="kw">=</span> <span class="no">LD1</span>, <span class="kw">y</span> <span class="kw">=</span> <span class="no">LD2</span>, <span class="kw">fill</span> <span class="kw">=</span> <span class="no">subgrp</span>), <span class="kw">data</span> <span class="kw">=</span> <span class="no">dt</span>, <span class="kw">type</span> <span class="kw">=</span> <span class="st">"norm"</span>,
               <span class="kw">geom</span> <span class="kw">=</span> <span class="st">"polygon"</span>, <span class="kw">level</span> <span class="kw">=</span> <span class="fl">0.5</span>, <span class="kw">alpha</span><span class="kw">=</span><span class="fl">0.2</span>, <span class="kw">show.legend</span> <span class="kw">=</span> <span class="fl">FALSE</span>) +
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_manual.html">scale_fill_manual</a></span>(<span class="kw">values</span> <span class="kw">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="st">"green4"</span>,<span class="st">"blue"</span>,<span class="st">"brown1"</span>)) + <span class="no">p0</span></pre></body></html></div>
<p><img src="pca_lda_with_methylit_files/figure-html/ldaGraphic-1.png" width="700"></p>
</div>
</div>
<div id="references" class="section level1">
<h1 class="hasAnchor">
<a href="#references" class="anchor"></a>References</h1>
<div id="refs">
<div id="ref-Liese2006">
<p>Liese, Friedrich, and Igor Vajda. 2006. “On divergences and informations in statistics and information theory.” <em>IEEE Transactions on Information Theory</em> 52 (10): 4394–4412. <a href="https://doi.org/10.1109/TIT.2006.881731">https://doi.org/10.1109/TIT.2006.881731</a>.</p>
</div>
<div id="ref-Stevens2009">
<p>Stevens, James P. 2009. <em>Applied Multivariate Statistics for the Social Sciences</em>. Fifth Edit. Routledge Academic.</p>
</div>
</div>
</div>
<div id="session-info" class="section level1 unnumbered">
<h1 class="hasAnchor">
<a href="#session-info" class="anchor"></a>Session info</h1>
<p>Here is the output of <code><a href="https://rdrr.io/r/utils/sessionInfo.html">sessionInfo()</a></code> on the system on which this document was compiled running pandoc 2.3.1:</p>
<pre><code>## R version 3.6.3 (2020-02-29)
## Platform: x86_64-pc-linux-gnu (64-bit)
## Running under: Ubuntu 18.04.4 LTS
## 
## Matrix products: default
## BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
## LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1
## 
## locale:
##  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
##  [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
##  [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
##  [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
##  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
## [11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
## 
## attached base packages:
## [1] parallel  stats4    stats     graphics  grDevices utils     datasets 
## [8] methods   base     
## 
## other attached packages:
##  [1] ape_5.3              ggplot2_3.3.0        MethylIT.utils_0.1  
##  [4] MethylIT_0.3.2       rtracklayer_1.44.4   GenomicRanges_1.36.1
##  [7] GenomeInfoDb_1.20.0  IRanges_2.18.3       S4Vectors_0.22.1    
## [10] BiocGenerics_0.30.0 
## 
## loaded via a namespace (and not attached):
##   [1] colorspace_1.4-1            ellipsis_0.3.0             
##   [3] class_7.3-16                modeltools_0.2-23          
##   [5] mclust_5.4.5                rprojroot_1.3-2            
##   [7] XVector_0.24.0              ArgumentCheck_0.10.2       
##   [9] fs_1.4.0                    rstudioapi_0.11            
##  [11] farver_2.0.3                flexmix_2.3-15             
##  [13] bit64_0.9-7                 AnnotationDbi_1.46.1       
##  [15] prodlim_2019.11.13          fansi_0.4.1                
##  [17] lubridate_1.7.4             codetools_0.2-16           
##  [19] splines_3.6.3               knitr_1.28                 
##  [21] Formula_1.2-3               pROC_1.16.2                
##  [23] Rsamtools_2.0.3             caret_6.0-86               
##  [25] annotate_1.56.1             kernlab_0.9-29             
##  [27] compiler_3.6.3              backports_1.1.5            
##  [29] assertthat_0.2.1            Matrix_1.2-18              
##  [31] cli_2.0.2                   htmltools_0.4.0            
##  [33] tools_3.6.3                 gtable_0.3.0               
##  [35] glue_1.3.2                  GenomeInfoDbData_1.2.1     
##  [37] reshape2_1.4.3              dplyr_0.8.5                
##  [39] Rcpp_1.0.4                  Biobase_2.44.0             
##  [41] pkgdown_1.5.0               vctrs_0.2.4                
##  [43] Biostrings_2.52.0           nlme_3.1-145               
##  [45] iterators_1.0.12            betareg_3.1-3              
##  [47] lmtest_0.9-37               timeDate_3043.102          
##  [49] gower_0.2.1                 xfun_0.12                  
##  [51] stringr_1.4.0               lifecycle_0.2.0            
##  [53] XML_3.99-0.3                zlibbioc_1.30.0            
##  [55] MASS_7.3-51.5               zoo_1.8-7                  
##  [57] scales_1.1.0                ipred_0.9-9                
##  [59] SummarizedExperiment_1.14.1 sandwich_2.5-1             
##  [61] yaml_2.2.1                  memoise_1.1.0              
##  [63] segmented_1.1-0             rpart_4.1-15               
##  [65] stringi_1.4.6               RSQLite_2.2.0              
##  [67] genefilter_1.66.0           desc_1.2.0                 
##  [69] foreach_1.5.0               e1071_1.7-3                
##  [71] BiocParallel_1.18.1         lava_1.6.7                 
##  [73] rlang_0.4.5                 pkgconfig_2.0.3            
##  [75] matrixStats_0.56.0          bitops_1.0-6               
##  [77] evaluate_0.14               lattice_0.20-40            
##  [79] purrr_0.3.3                 labeling_0.3               
##  [81] GenomicAlignments_1.20.1    recipes_0.1.10             
##  [83] bit_1.1-15.2                tidyselect_1.0.0           
##  [85] plyr_1.8.6                  magrittr_1.5               
##  [87] nls2_0.2                    R6_2.4.1                   
##  [89] generics_0.0.2              DelayedArray_0.10.0        
##  [91] DBI_1.1.0                   pillar_1.4.3               
##  [93] withr_2.1.2                 mixtools_1.2.0             
##  [95] survival_3.1-11             RCurl_1.98-1.1             
##  [97] nnet_7.3-13                 tibble_3.0.0               
##  [99] crayon_1.3.4                rmarkdown_2.1.1            
## [101] grid_3.6.3                  minpack.lm_1.2-1           
## [103] data.table_1.12.8           blob_1.2.1                 
## [105] ModelMetrics_1.2.2.2        digest_0.6.25              
## [107] xtable_1.8-4                munsell_0.5.0</code></pre>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="pkgdown-sidebar">

        <nav id="toc" data-toggle="toc"><h2 data-toc-skip>Contents</h2>
    </nav>
</div>

</div>



      <footer><div class="copyright">
  <p>Developed by Robersy Sanchez.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="https://pkgdown.r-lib.org/">pkgdown</a> 1.5.0.</p>
</div>

      </footer>
</div>

  


  </body>
</html>
